package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

type rpcMethod struct {
	Name     string
	Request  string
	Response string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "gzc-rpcproto-gen: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	var protoPath string
	var goRPCAPIOut string
	flags := flag.NewFlagSet("gzc-rpcproto-gen", flag.ContinueOnError)
	flags.StringVar(&protoPath, "proto", "api/rpc/peer.proto", "Peer RPC protobuf schema with method request/response comments")
	flags.StringVar(&goRPCAPIOut, "go-rpcapi-out", "", "Generated Go rpcapi payload map output path")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if goRPCAPIOut == "" {
		return errors.New("-go-rpcapi-out is required")
	}
	methods, err := loadRPCMethods(protoPath)
	if err != nil {
		return err
	}
	out := emitGoRPCAPIPayloadMap(methods)
	return writeIfChanged(goRPCAPIOut, out)
}

func loadRPCMethods(path string) ([]rpcMethod, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	commentRe := regexp.MustCompile(`^\s*//\s*rpc:\s+(\S+)\s+request=(\w+)\s+response=(\w+)\s*$`)
	entryRe := regexp.MustCompile(`^\s*RPC_METHOD_[A-Z0-9_]+\s*=\s*(-?\d+)\s*;`)
	var out []rpcMethod
	var pending *rpcMethod
	seen := map[string]bool{}
	for _, line := range strings.Split(string(data), "\n") {
		if match := commentRe.FindStringSubmatch(line); match != nil {
			pending = &rpcMethod{Name: match[1], Request: match[2], Response: match[3]}
			continue
		}
		if entryRe.FindStringSubmatch(line) == nil {
			continue
		}
		if pending == nil {
			if strings.Contains(line, "RPC_METHOD_UNSPECIFIED") {
				continue
			}
			return nil, fmt.Errorf("%s: RpcMethod entry missing rpc comment: %s", path, strings.TrimSpace(line))
		}
		if seen[pending.Name] {
			return nil, fmt.Errorf("%s: duplicate rpc method %q", path, pending.Name)
		}
		out = append(out, *pending)
		seen[pending.Name] = true
		pending = nil
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no rpc methods found", path)
	}
	return out, nil
}

func emitGoRPCAPIPayloadMap(methods []rpcMethod) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gzc-rpcproto-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package rpcapi\n\n")
	buf.WriteString("var rpcRequestPayloadMessages = map[RPCMethod]string{\n")
	for _, method := range methods {
		fmt.Fprintf(&buf, "\t%s: %q,\n", goRPCMethodConst(method.Name), method.Request)
	}
	buf.WriteString("}\n\n")
	buf.WriteString("var rpcResponsePayloadMessages = map[RPCMethod]string{\n")
	for _, method := range methods {
		fmt.Fprintf(&buf, "\t%s: %q,\n", goRPCMethodConst(method.Name), method.Response)
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func goRPCMethodConst(method string) string {
	return "RPCMethod" + upperCamel(method)
}

func upperCamel(value string) string {
	parts := regexp.MustCompile(`[^A-Za-z0-9]+`).Split(value, -1)
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		out.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			out.WriteString(part[1:])
		}
	}
	if out.Len() == 0 {
		return "Value"
	}
	return out.String()
}

func writeIfChanged(path string, data []byte) error {
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}
