// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/telemetry/peer_telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryFrame struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sequence         uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,2,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	Observations     []*Observation         `protobuf:"bytes,3,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetryFrame) Reset() {
	*x = TelemetryFrame{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryFrame) ProtoMessage() {}

func (x *TelemetryFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryFrame.ProtoReflect.Descriptor instead.
func (*TelemetryFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryFrame) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TelemetryFrame) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *TelemetryFrame) GetObservations() []*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type Observation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ObservedAtDeltaMs int32                  `protobuf:"varint,1,opt,name=observed_at_delta_ms,json=observedAtDeltaMs,proto3" json:"observed_at_delta_ms,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Observation_Battery
	//	*Observation_Gnss
	//	*Observation_Network
	//	*Observation_System
	Body          isObservation_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Observation) GetObservedAtDeltaMs() int32 {
	if x != nil {
		return x.ObservedAtDeltaMs
	}
	return 0
}

func (x *Observation) GetBody() isObservation_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Observation) GetBattery() *BatteryObservation {
	if x != nil {
		if x, ok := x.Body.(*Observation_Battery); ok {
			return x.Battery
		}
	}
	return nil
}

func (x *Observation) GetGnss() *GnssObservation {
	if x != nil {
		if x, ok := x.Body.(*Observation_Gnss); ok {
			return x.Gnss
		}
	}
	return nil
}

func (x *Observation) GetNetwork() *NetworkObservation {
	if x != nil {
		if x, ok := x.Body.(*Observation_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *Observation) GetSystem() *SystemObservation {
	if x != nil {
		if x, ok := x.Body.(*Observation_System); ok {
			return x.System
		}
	}
	return nil
}

type isObservation_Body interface {
	isObservation_Body()
}

type Observation_Battery struct {
	Battery *BatteryObservation `protobuf:"bytes,10,opt,name=battery,proto3,oneof"`
}

type Observation_Gnss struct {
	Gnss *GnssObservation `protobuf:"bytes,11,opt,name=gnss,proto3,oneof"`
}

type Observation_Network struct {
	Network *NetworkObservation `protobuf:"bytes,12,opt,name=network,proto3,oneof"`
}

type Observation_System struct {
	System *SystemObservation `protobuf:"bytes,13,opt,name=system,proto3,oneof"`
}

func (*Observation_Battery) isObservation_Body() {}

func (*Observation_Gnss) isObservation_Body() {}

func (*Observation_Network) isObservation_Body() {}

func (*Observation_System) isObservation_Body() {}

type BatteryObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       *float64               `protobuf:"fixed64,1,opt,name=percent,proto3,oneof" json:"percent,omitempty"`
	Charging      *bool                  `protobuf:"varint,2,opt,name=charging,proto3,oneof" json:"charging,omitempty"`
	VoltageMv     *float64               `protobuf:"fixed64,3,opt,name=voltage_mv,json=voltageMv,proto3,oneof" json:"voltage_mv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryObservation) Reset() {
	*x = BatteryObservation{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryObservation) ProtoMessage() {}

func (x *BatteryObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryObservation.ProtoReflect.Descriptor instead.
func (*BatteryObservation) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *BatteryObservation) GetPercent() float64 {
	if x != nil && x.Percent != nil {
		return *x.Percent
	}
	return 0
}

func (x *BatteryObservation) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

func (x *BatteryObservation) GetVoltageMv() float64 {
	if x != nil && x.VoltageMv != nil {
		return *x.VoltageMv
	}
	return 0
}

type GnssObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AltitudeM     *float64               `protobuf:"fixed64,3,opt,name=altitude_m,json=altitudeM,proto3,oneof" json:"altitude_m,omitempty"`
	AccuracyM     *float64               `protobuf:"fixed64,4,opt,name=accuracy_m,json=accuracyM,proto3,oneof" json:"accuracy_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GnssObservation) Reset() {
	*x = GnssObservation{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GnssObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GnssObservation) ProtoMessage() {}

func (x *GnssObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GnssObservation.ProtoReflect.Descriptor instead.
func (*GnssObservation) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *GnssObservation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GnssObservation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GnssObservation) GetAltitudeM() float64 {
	if x != nil && x.AltitudeM != nil {
		return *x.AltitudeM
	}
	return 0
}

func (x *GnssObservation) GetAccuracyM() float64 {
	if x != nil && x.AccuracyM != nil {
		return *x.AccuracyM
	}
	return 0
}

type NetworkObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RssiDbm       *float64               `protobuf:"fixed64,1,opt,name=rssi_dbm,json=rssiDbm,proto3,oneof" json:"rssi_dbm,omitempty"`
	SignalLevel   *float64               `protobuf:"fixed64,2,opt,name=signal_level,json=signalLevel,proto3,oneof" json:"signal_level,omitempty"`
	Rat           *string                `protobuf:"bytes,3,opt,name=rat,proto3,oneof" json:"rat,omitempty"`
	Operator      *string                `protobuf:"bytes,4,opt,name=operator,proto3,oneof" json:"operator,omitempty"`
	Connected     *bool                  `protobuf:"varint,5,opt,name=connected,proto3,oneof" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkObservation) Reset() {
	*x = NetworkObservation{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkObservation) ProtoMessage() {}

func (x *NetworkObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkObservation.ProtoReflect.Descriptor instead.
func (*NetworkObservation) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkObservation) GetRssiDbm() float64 {
	if x != nil && x.RssiDbm != nil {
		return *x.RssiDbm
	}
	return 0
}

func (x *NetworkObservation) GetSignalLevel() float64 {
	if x != nil && x.SignalLevel != nil {
		return *x.SignalLevel
	}
	return 0
}

func (x *NetworkObservation) GetRat() string {
	if x != nil && x.Rat != nil {
		return *x.Rat
	}
	return ""
}

func (x *NetworkObservation) GetOperator() string {
	if x != nil && x.Operator != nil {
		return *x.Operator
	}
	return ""
}

func (x *NetworkObservation) GetConnected() bool {
	if x != nil && x.Connected != nil {
		return *x.Connected
	}
	return false
}

type SystemObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds   *float64               `protobuf:"fixed64,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3,oneof" json:"uptime_seconds,omitempty"`
	FreeMemoryBytes *float64               `protobuf:"fixed64,2,opt,name=free_memory_bytes,json=freeMemoryBytes,proto3,oneof" json:"free_memory_bytes,omitempty"`
	TemperatureC    *float64               `protobuf:"fixed64,3,opt,name=temperature_c,json=temperatureC,proto3,oneof" json:"temperature_c,omitempty"`
	FirmwareVersion *string                `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3,oneof" json:"firmware_version,omitempty"`
	SoftwareVersion *string                `protobuf:"bytes,5,opt,name=software_version,json=softwareVersion,proto3,oneof" json:"software_version,omitempty"`
	HardwareVersion *string                `protobuf:"bytes,6,opt,name=hardware_version,json=hardwareVersion,proto3,oneof" json:"hardware_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemObservation) Reset() {
	*x = SystemObservation{}
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemObservation) ProtoMessage() {}

func (x *SystemObservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_telemetry_peer_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemObservation.ProtoReflect.Descriptor instead.
func (*SystemObservation) Descriptor() ([]byte, []int) {
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *SystemObservation) GetUptimeSeconds() float64 {
	if x != nil && x.UptimeSeconds != nil {
		return *x.UptimeSeconds
	}
	return 0
}

func (x *SystemObservation) GetFreeMemoryBytes() float64 {
	if x != nil && x.FreeMemoryBytes != nil {
		return *x.FreeMemoryBytes
	}
	return 0
}

func (x *SystemObservation) GetTemperatureC() float64 {
	if x != nil && x.TemperatureC != nil {
		return *x.TemperatureC
	}
	return 0
}

func (x *SystemObservation) GetFirmwareVersion() string {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return ""
}

func (x *SystemObservation) GetSoftwareVersion() string {
	if x != nil && x.SoftwareVersion != nil {
		return *x.SoftwareVersion
	}
	return ""
}

func (x *SystemObservation) GetHardwareVersion() string {
	if x != nil && x.HardwareVersion != nil {
		return *x.HardwareVersion
	}
	return ""
}

var File_api_proto_telemetry_peer_telemetry_proto protoreflect.FileDescriptor

const file_api_proto_telemetry_peer_telemetry_proto_rawDesc = "" +
	"\n" +
	"(api/proto/telemetry/peer_telemetry.proto\x12\x14gizclaw.telemetry.v1\"\xa2\x01\n" +
	"\x0eTelemetryFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12-\n" +
	"\x13observed_at_unix_ms\x18\x02 \x01(\x03R\x10observedAtUnixMs\x12E\n" +
	"\fobservations\x18\x03 \x03(\v2!.gizclaw.telemetry.v1.ObservationR\fobservations\"\xd2\x02\n" +
	"\vObservation\x12/\n" +
	"\x14observed_at_delta_ms\x18\x01 \x01(\x05R\x11observedAtDeltaMs\x12D\n" +
	"\abattery\x18\n" +
	" \x01(\v2(.gizclaw.telemetry.v1.BatteryObservationH\x00R\abattery\x12;\n" +
	"\x04gnss\x18\v \x01(\v2%.gizclaw.telemetry.v1.GnssObservationH\x00R\x04gnss\x12D\n" +
	"\anetwork\x18\f \x01(\v2(.gizclaw.telemetry.v1.NetworkObservationH\x00R\anetwork\x12A\n" +
	"\x06system\x18\r \x01(\v2'.gizclaw.telemetry.v1.SystemObservationH\x00R\x06systemB\x06\n" +
	"\x04body\"\xa0\x01\n" +
	"\x12BatteryObservation\x12\x1d\n" +
	"\apercent\x18\x01 \x01(\x01H\x00R\apercent\x88\x01\x01\x12\x1f\n" +
	"\bcharging\x18\x02 \x01(\bH\x01R\bcharging\x88\x01\x01\x12\"\n" +
	"\n" +
	"voltage_mv\x18\x03 \x01(\x01H\x02R\tvoltageMv\x88\x01\x01B\n" +
	"\n" +
	"\b_percentB\v\n" +
	"\t_chargingB\r\n" +
	"\v_voltage_mv\"\xb1\x01\n" +
	"\x0fGnssObservation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\"\n" +
	"\n" +
	"altitude_m\x18\x03 \x01(\x01H\x00R\taltitudeM\x88\x01\x01\x12\"\n" +
	"\n" +
	"accuracy_m\x18\x04 \x01(\x01H\x01R\taccuracyM\x88\x01\x01B\r\n" +
	"\v_altitude_mB\r\n" +
	"\v_accuracy_m\"\xf8\x01\n" +
	"\x12NetworkObservation\x12\x1e\n" +
	"\brssi_dbm\x18\x01 \x01(\x01H\x00R\arssiDbm\x88\x01\x01\x12&\n" +
	"\fsignal_level\x18\x02 \x01(\x01H\x01R\vsignalLevel\x88\x01\x01\x12\x15\n" +
	"\x03rat\x18\x03 \x01(\tH\x02R\x03rat\x88\x01\x01\x12\x1f\n" +
	"\boperator\x18\x04 \x01(\tH\x03R\boperator\x88\x01\x01\x12!\n" +
	"\tconnected\x18\x05 \x01(\bH\x04R\tconnected\x88\x01\x01B\v\n" +
	"\t_rssi_dbmB\x0f\n" +
	"\r_signal_levelB\x06\n" +
	"\x04_ratB\v\n" +
	"\t_operatorB\f\n" +
	"\n" +
	"_connected\"\xa4\x03\n" +
	"\x11SystemObservation\x12*\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x01H\x00R\ruptimeSeconds\x88\x01\x01\x12/\n" +
	"\x11free_memory_bytes\x18\x02 \x01(\x01H\x01R\x0ffreeMemoryBytes\x88\x01\x01\x12(\n" +
	"\rtemperature_c\x18\x03 \x01(\x01H\x02R\ftemperatureC\x88\x01\x01\x12.\n" +
	"\x10firmware_version\x18\x04 \x01(\tH\x03R\x0ffirmwareVersion\x88\x01\x01\x12.\n" +
	"\x10software_version\x18\x05 \x01(\tH\x04R\x0fsoftwareVersion\x88\x01\x01\x12.\n" +
	"\x10hardware_version\x18\x06 \x01(\tH\x05R\x0fhardwareVersion\x88\x01\x01B\x11\n" +
	"\x0f_uptime_secondsB\x14\n" +
	"\x12_free_memory_bytesB\x10\n" +
	"\x0e_temperature_cB\x13\n" +
	"\x11_firmware_versionB\x13\n" +
	"\x11_software_versionB\x13\n" +
	"\x11_hardware_versionBFZDgithub.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/telemetry;telemetrypbb\x06proto3"

var (
	file_api_proto_telemetry_peer_telemetry_proto_rawDescOnce sync.Once
	file_api_proto_telemetry_peer_telemetry_proto_rawDescData []byte
)

func file_api_proto_telemetry_peer_telemetry_proto_rawDescGZIP() []byte {
	file_api_proto_telemetry_peer_telemetry_proto_rawDescOnce.Do(func() {
		file_api_proto_telemetry_peer_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_telemetry_peer_telemetry_proto_rawDesc), len(file_api_proto_telemetry_peer_telemetry_proto_rawDesc)))
	})
	return file_api_proto_telemetry_peer_telemetry_proto_rawDescData
}

var file_api_proto_telemetry_peer_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_telemetry_peer_telemetry_proto_goTypes = []any{
	(*TelemetryFrame)(nil),     // 0: gizclaw.telemetry.v1.TelemetryFrame
	(*Observation)(nil),        // 1: gizclaw.telemetry.v1.Observation
	(*BatteryObservation)(nil), // 2: gizclaw.telemetry.v1.BatteryObservation
	(*GnssObservation)(nil),    // 3: gizclaw.telemetry.v1.GnssObservation
	(*NetworkObservation)(nil), // 4: gizclaw.telemetry.v1.NetworkObservation
	(*SystemObservation)(nil),  // 5: gizclaw.telemetry.v1.SystemObservation
}
var file_api_proto_telemetry_peer_telemetry_proto_depIdxs = []int32{
	1, // 0: gizclaw.telemetry.v1.TelemetryFrame.observations:type_name -> gizclaw.telemetry.v1.Observation
	2, // 1: gizclaw.telemetry.v1.Observation.battery:type_name -> gizclaw.telemetry.v1.BatteryObservation
	3, // 2: gizclaw.telemetry.v1.Observation.gnss:type_name -> gizclaw.telemetry.v1.GnssObservation
	4, // 3: gizclaw.telemetry.v1.Observation.network:type_name -> gizclaw.telemetry.v1.NetworkObservation
	5, // 4: gizclaw.telemetry.v1.Observation.system:type_name -> gizclaw.telemetry.v1.SystemObservation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_telemetry_peer_telemetry_proto_init() }
func file_api_proto_telemetry_peer_telemetry_proto_init() {
	if File_api_proto_telemetry_peer_telemetry_proto != nil {
		return
	}
	file_api_proto_telemetry_peer_telemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*Observation_Battery)(nil),
		(*Observation_Gnss)(nil),
		(*Observation_Network)(nil),
		(*Observation_System)(nil),
	}
	file_api_proto_telemetry_peer_telemetry_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_telemetry_peer_telemetry_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_telemetry_peer_telemetry_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_telemetry_peer_telemetry_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_telemetry_peer_telemetry_proto_rawDesc), len(file_api_proto_telemetry_peer_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_telemetry_peer_telemetry_proto_goTypes,
		DependencyIndexes: file_api_proto_telemetry_peer_telemetry_proto_depIdxs,
		MessageInfos:      file_api_proto_telemetry_peer_telemetry_proto_msgTypes,
	}.Build()
	File_api_proto_telemetry_peer_telemetry_proto = out.File
	file_api_proto_telemetry_peer_telemetry_proto_goTypes = nil
	file_api_proto_telemetry_peer_telemetry_proto_depIdxs = nil
}
