/* Code generated by tools/gzc-rpcgen. DO NOT EDIT. */

#include "gzc_rpc_decode.h"

#include <string.h>

int gzc_ping_response_decode_json(gzc_str_t json, gzc_ping_response_t *out_value) {
  if (out_value == NULL) {
    return GZC_ERR_INVALID_ARGUMENT;
  }
  memset(out_value, 0, sizeof(*out_value));
  gzc_str_t raw;
  int rc;
  rc = gzc_json_find_field(json, "ok", &raw);
  if (rc != GZC_OK) { return rc; }
  rc = gzc_json_parse_bool(raw, &out_value->ok);
  if (rc != GZC_OK) { return rc; }
  rc = gzc_json_find_field(json, "server_time", &raw);
  if (rc != GZC_OK) { return rc; }
  rc = gzc_json_parse_i64(raw, &out_value->server_time);
  if (rc != GZC_OK) { return rc; }
  return GZC_OK;
}

int gzc_server_run_say_response_decode_json(gzc_str_t json, gzc_server_run_say_response_t *out_value) {
  if (out_value == NULL) {
    return GZC_ERR_INVALID_ARGUMENT;
  }
  memset(out_value, 0, sizeof(*out_value));
  gzc_str_t raw;
  int rc;
  rc = gzc_json_find_field(json, "accepted", &raw);
  if (rc != GZC_OK) { return rc; }
  rc = gzc_json_parse_bool(raw, &out_value->accepted);
  if (rc != GZC_OK) { return rc; }
  rc = gzc_json_find_field(json, "queue_position", &raw);
  if (rc == GZC_OK) {
    out_value->has_queue_position = true;
    rc = gzc_json_parse_i32(raw, &out_value->queue_position);
    if (rc != GZC_OK) { return rc; }
  }
  return GZC_OK;
}
