/* Code generated by tools/gzc-rpcgen. DO NOT EDIT. */

#ifndef GZC_RPC_ENCODE_H
#define GZC_RPC_ENCODE_H

#include "gzc_rpc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

int gzc_ping_request_encode_json(const gzc_platform_t *platform, const gzc_ping_request_t *value, gzc_buf_t *out_json);
int gzc_speed_test_request_encode_json(const gzc_platform_t *platform, const gzc_speed_test_request_t *value, gzc_buf_t *out_json);
int gzc_server_run_say_request_encode_json(const gzc_platform_t *platform, const gzc_server_run_say_request_t *value, gzc_buf_t *out_json);

#ifdef __cplusplus
}
#endif

#endif
