/* Code generated by tools/gzc-rpcgen. DO NOT EDIT. */

#include "gzc_rpc_encode.h"

#include "gzc_rpc_methods.h"

const gzc_rpc_method_info_t gzc_rpc_methods[] = {
  {GZC_RPC_METHOD_ALL_PING, "PingRequest", "PingResponse"},
  {GZC_RPC_METHOD_ALL_SPEED_TEST_RUN, "SpeedTestRequest", "SpeedTestResponse"},
  {GZC_RPC_METHOD_SERVER_RUN_SAY, "ServerRunSayRequest", "ServerRunSayResponse"},
};

int gzc_ping_request_encode_json(const gzc_platform_t *platform, const gzc_ping_request_t *value, gzc_buf_t *out_json) {
  if (value == NULL || out_json == NULL) {
    return GZC_ERR_INVALID_ARGUMENT;
  }
  gzc_json_writer_t writer;
  gzc_json_writer_init(&writer, platform, out_json);
  int rc = gzc_json_object_begin(&writer);
  if (rc != GZC_OK) { return rc; }
  if (true) {
    rc = gzc_json_field_i64(&writer, "client_send_time", value->client_send_time);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_tag) {
    rc = gzc_json_field_str(&writer, "tag", value->tag);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_trace) {
    rc = gzc_json_field_raw(&writer, "trace", value->trace.raw);
    if (rc != GZC_OK) { return rc; }
  }
  return gzc_json_object_end(&writer);
}

int gzc_speed_test_request_encode_json(const gzc_platform_t *platform, const gzc_speed_test_request_t *value, gzc_buf_t *out_json) {
  if (value == NULL || out_json == NULL) {
    return GZC_ERR_INVALID_ARGUMENT;
  }
  gzc_json_writer_t writer;
  gzc_json_writer_init(&writer, platform, out_json);
  int rc = gzc_json_object_begin(&writer);
  if (rc != GZC_OK) { return rc; }
  if (true) {
    rc = gzc_json_field_i64(&writer, "down_content_length", value->down_content_length);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_payload_hint) {
    rc = gzc_json_field_raw(&writer, "payload_hint", value->payload_hint.raw);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_sample_count) {
    rc = gzc_json_field_i32(&writer, "sample_count", value->sample_count);
    if (rc != GZC_OK) { return rc; }
  }
  if (true) {
    rc = gzc_json_field_i64(&writer, "up_content_length", value->up_content_length);
    if (rc != GZC_OK) { return rc; }
  }
  return gzc_json_object_end(&writer);
}

int gzc_server_run_say_request_encode_json(const gzc_platform_t *platform, const gzc_server_run_say_request_t *value, gzc_buf_t *out_json) {
  if (value == NULL || out_json == NULL) {
    return GZC_ERR_INVALID_ARGUMENT;
  }
  gzc_json_writer_t writer;
  gzc_json_writer_init(&writer, platform, out_json);
  int rc = gzc_json_object_begin(&writer);
  if (rc != GZC_OK) { return rc; }
  if (value->has_metadata) {
    rc = gzc_json_field_raw(&writer, "metadata", value->metadata.raw);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_repeat) {
    rc = gzc_json_field_i32(&writer, "repeat", value->repeat);
    if (rc != GZC_OK) { return rc; }
  }
  if (true) {
    rc = gzc_json_field_str(&writer, "text", value->text);
    if (rc != GZC_OK) { return rc; }
  }
  if (value->has_voice_id) {
    rc = gzc_json_field_str(&writer, "voice_id", value->voice_id);
    if (rc != GZC_OK) { return rc; }
  }
  return gzc_json_object_end(&writer);
}
