/* Code generated by tools/gzc-rpcgen. DO NOT EDIT. */

#ifndef GZC_RPC_TYPES_H
#define GZC_RPC_TYPES_H

#include "gzc_json.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  int64_t client_send_time;
  bool has_tag;
  gzc_str_t tag;
} gzc_ping_request_t;

typedef struct {
  bool has_metadata;
  gzc_json_t metadata;
  gzc_str_t text;
  bool has_voice_id;
  gzc_str_t voice_id;
} gzc_server_run_say_request_t;

typedef struct {
  bool ok;
  int64_t server_time;
} gzc_ping_response_t;

typedef struct {
  bool accepted;
  bool has_queue_position;
  int32_t queue_position;
} gzc_server_run_say_response_t;

#ifdef __cplusplus
}
#endif

#endif
