package: peerhttp
generate:
  fiber-server: true
  strict-server: true
  client: true
  models: true
import-mapping:
  ./shared.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
  ./shared/server.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcapi
output-options:
  skip-prune: true
