// Package peerhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package peerhttp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	externalRef0 "github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for LoginResultTokenType.
const (
	Bearer LoginResultTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResultTokenType enum.
func (e LoginResultTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// GiznetWebRTCSignalingError defines model for GiznetWebRTCSignalingError.
type GiznetWebRTCSignalingError struct {
	Error string `json:"error"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	AccessToken string               `json:"access_token"`
	ExpiresAt   int64                `json:"expires_at"`
	TokenType   LoginResultTokenType `json:"token_type"`
}

// LoginResultTokenType defines model for LoginResult.TokenType.
type LoginResultTokenType string

// PeerSelf defines model for PeerSelf.
type PeerSelf struct {
	Device             *externalRef0.DeviceInfo            `json:"device,omitempty"`
	PublicKey          string                              `json:"public_key"`
	RegistrationStatus externalRef0.PeerRegistrationStatus `json:"registration_status"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	XPublicKey    string `json:"X-Public-Key"`
	Authorization string `json:"Authorization"`
}

// CreateGiznetWebRTCOfferParams defines parameters for CreateGiznetWebRTCOffer.
type CreateGiznetWebRTCOfferParams struct {
	// XGiznetPublicKey Client public key.
	XGiznetPublicKey string `json:"X-Giznet-Public-Key"`

	// XGiznetTimestamp Unix timestamp used by signaling AEAD derivation.
	XGiznetTimestamp int64 `json:"X-Giznet-Timestamp"`

	// XGiznetNonce Base64url nonce used by signaling AEAD derivation and replay checks.
	XGiznetNonce string `json:"X-Giznet-Nonce"`
}

// PutMeStatusJSONRequestBody defines body for PutMeStatus for application/json ContentType.
type PutMeStatusJSONRequestBody = externalRef0.PeerStatus

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Login request
	Login(ctx context.Context, params *LoginParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMe request
	GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMeRuntime request
	GetMeRuntime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMeStatus request
	GetMeStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMeStatusWithBody request with any body
	PutMeStatusWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMeStatus(ctx context.Context, body PutMeStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServerInfo request
	GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateGiznetWebRTCOfferWithBody request with any body
	CreateGiznetWebRTCOfferWithBody(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Login(ctx context.Context, params *LoginParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLoginRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMeRuntime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeRuntimeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMeStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMeStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMeStatusWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMeStatusRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMeStatus(ctx context.Context, body PutMeStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMeStatusRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGiznetWebRTCOfferWithBody(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGiznetWebRTCOfferRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLoginRequest generates requests for Login
func NewLoginRequest(server string, params *LoginParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Public-Key", params.XPublicKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Public-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Authorization", params.Authorization, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Authorization", headerParam1)

	}

	return req, nil
}

// NewGetMeRequest generates requests for GetMe
func NewGetMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMeRuntimeRequest generates requests for GetMeRuntime
func NewGetMeRuntimeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/runtime")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMeStatusRequest generates requests for GetMeStatus
func NewGetMeStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutMeStatusRequest calls the generic PutMeStatus builder with application/json body
func NewPutMeStatusRequest(server string, body PutMeStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMeStatusRequestWithBody(server, "application/json", bodyReader)
}

// NewPutMeStatusRequestWithBody generates requests for PutMeStatus with any type of body
func NewPutMeStatusRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/me/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetServerInfoRequest generates requests for GetServerInfo
func NewGetServerInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/server-info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateGiznetWebRTCOfferRequestWithBody generates requests for CreateGiznetWebRTCOffer with any type of body
func NewCreateGiznetWebRTCOfferRequestWithBody(server string, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webrtc/v1/offer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Public-Key", params.XGiznetPublicKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Public-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Timestamp", params.XGiznetTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "integer", Format: "int64"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Timestamp", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Nonce", params.XGiznetNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Nonce", headerParam2)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// LoginWithResponse request
	LoginWithResponse(ctx context.Context, params *LoginParams, reqEditors ...RequestEditorFn) (*LoginResponse, error)

	// GetMeWithResponse request
	GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error)

	// GetMeRuntimeWithResponse request
	GetMeRuntimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeRuntimeResponse, error)

	// GetMeStatusWithResponse request
	GetMeStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeStatusResponse, error)

	// PutMeStatusWithBodyWithResponse request with any body
	PutMeStatusWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMeStatusResponse, error)

	PutMeStatusWithResponse(ctx context.Context, body PutMeStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMeStatusResponse, error)

	// GetServerInfoWithResponse request
	GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error)

	// CreateGiznetWebRTCOfferWithBodyWithResponse request with any body
	CreateGiznetWebRTCOfferWithBodyWithResponse(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGiznetWebRTCOfferResponse, error)
}

type LoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LoginResult
	JSON401      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r LoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PeerSelf
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMeRuntimeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Runtime
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMeRuntimeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeRuntimeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMeStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.PeerStatus
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMeStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMeStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMeStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.PeerStatus
	JSON400      *externalRef0.ErrorResponse
	JSON401      *externalRef0.ErrorResponse
	JSON404      *externalRef0.ErrorResponse
	JSON500      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutMeStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMeStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetServerInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.ServerInfo
	JSON400      *externalRef0.ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetServerInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateGiznetWebRTCOfferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *GiznetWebRTCSignalingError
	JSON401      *GiznetWebRTCSignalingError
	JSON403      *GiznetWebRTCSignalingError
	JSON409      *GiznetWebRTCSignalingError
	JSON413      *GiznetWebRTCSignalingError
	JSON415      *GiznetWebRTCSignalingError
	JSON500      *GiznetWebRTCSignalingError
	JSON503      *GiznetWebRTCSignalingError
}

// Status returns HTTPResponse.Status
func (r CreateGiznetWebRTCOfferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateGiznetWebRTCOfferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// LoginWithResponse request returning *LoginResponse
func (c *ClientWithResponses) LoginWithResponse(ctx context.Context, params *LoginParams, reqEditors ...RequestEditorFn) (*LoginResponse, error) {
	rsp, err := c.Login(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLoginResponse(rsp)
}

// GetMeWithResponse request returning *GetMeResponse
func (c *ClientWithResponses) GetMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeResponse, error) {
	rsp, err := c.GetMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeResponse(rsp)
}

// GetMeRuntimeWithResponse request returning *GetMeRuntimeResponse
func (c *ClientWithResponses) GetMeRuntimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeRuntimeResponse, error) {
	rsp, err := c.GetMeRuntime(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeRuntimeResponse(rsp)
}

// GetMeStatusWithResponse request returning *GetMeStatusResponse
func (c *ClientWithResponses) GetMeStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMeStatusResponse, error) {
	rsp, err := c.GetMeStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMeStatusResponse(rsp)
}

// PutMeStatusWithBodyWithResponse request with arbitrary body returning *PutMeStatusResponse
func (c *ClientWithResponses) PutMeStatusWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMeStatusResponse, error) {
	rsp, err := c.PutMeStatusWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMeStatusResponse(rsp)
}

func (c *ClientWithResponses) PutMeStatusWithResponse(ctx context.Context, body PutMeStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMeStatusResponse, error) {
	rsp, err := c.PutMeStatus(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMeStatusResponse(rsp)
}

// GetServerInfoWithResponse request returning *GetServerInfoResponse
func (c *ClientWithResponses) GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error) {
	rsp, err := c.GetServerInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerInfoResponse(rsp)
}

// CreateGiznetWebRTCOfferWithBodyWithResponse request with arbitrary body returning *CreateGiznetWebRTCOfferResponse
func (c *ClientWithResponses) CreateGiznetWebRTCOfferWithBodyWithResponse(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGiznetWebRTCOfferResponse, error) {
	rsp, err := c.CreateGiznetWebRTCOfferWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGiznetWebRTCOfferResponse(rsp)
}

// ParseLoginResponse parses an HTTP response from a LoginWithResponse call
func ParseLoginResponse(rsp *http.Response) (*LoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LoginResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetMeResponse parses an HTTP response from a GetMeWithResponse call
func ParseGetMeResponse(rsp *http.Response) (*GetMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PeerSelf
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetMeRuntimeResponse parses an HTTP response from a GetMeRuntimeWithResponse call
func ParseGetMeRuntimeResponse(rsp *http.Response) (*GetMeRuntimeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeRuntimeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Runtime
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetMeStatusResponse parses an HTTP response from a GetMeStatusWithResponse call
func ParseGetMeStatusResponse(rsp *http.Response) (*GetMeStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMeStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.PeerStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutMeStatusResponse parses an HTTP response from a PutMeStatusWithResponse call
func ParsePutMeStatusResponse(rsp *http.Response) (*PutMeStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMeStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.PeerStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetServerInfoResponse parses an HTTP response from a GetServerInfoWithResponse call
func ParseGetServerInfoResponse(rsp *http.Response) (*GetServerInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.ServerInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseCreateGiznetWebRTCOfferResponse parses an HTTP response from a CreateGiznetWebRTCOfferWithResponse call
func ParseCreateGiznetWebRTCOfferResponse(rsp *http.Response) (*CreateGiznetWebRTCOfferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateGiznetWebRTCOfferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exchange a device assertion for a bearer session
	// (POST /login)
	Login(c *fiber.Ctx, params LoginParams) error
	// Get caller peer summary
	// (GET /me)
	GetMe(c *fiber.Ctx) error
	// Get caller peer runtime
	// (GET /me/runtime)
	GetMeRuntime(c *fiber.Ctx) error
	// Get caller peer status
	// (GET /me/status)
	GetMeStatus(c *fiber.Ctx) error
	// Update caller peer status
	// (PUT /me/status)
	PutMeStatus(c *fiber.Ctx) error
	// Get server information
	// (GET /server-info)
	GetServerInfo(c *fiber.Ctx) error
	// Create a WebRTC answer for an encrypted browser offer
	// (POST /webrtc/v1/offer)
	CreateGiznetWebRTCOffer(c *fiber.Ctx, params CreateGiznetWebRTCOfferParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	headers := c.GetReqHeaders()

	// ------------- Required header parameter "X-Public-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Public-Key")]; found {
		var XPublicKey string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Public-Key, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Public-Key", valueList[0], &XPublicKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Public-Key: %w", err).Error())
		}

		params.XPublicKey = XPublicKey

	} else {
		err = fmt.Errorf("Header parameter X-Public-Key is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName Authorization, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter Authorization: %w", err).Error())
		}

		params.Authorization = Authorization

	} else {
		err = fmt.Errorf("Header parameter Authorization is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	return siw.Handler.Login(c, params)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetMe(c)
}

// GetMeRuntime operation middleware
func (siw *ServerInterfaceWrapper) GetMeRuntime(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetMeRuntime(c)
}

// GetMeStatus operation middleware
func (siw *ServerInterfaceWrapper) GetMeStatus(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetMeStatus(c)
}

// PutMeStatus operation middleware
func (siw *ServerInterfaceWrapper) PutMeStatus(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PutMeStatus(c)
}

// GetServerInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServerInfo(c *fiber.Ctx) error {

	return siw.Handler.GetServerInfo(c)
}

// CreateGiznetWebRTCOffer operation middleware
func (siw *ServerInterfaceWrapper) CreateGiznetWebRTCOffer(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateGiznetWebRTCOfferParams

	headers := c.GetReqHeaders()

	// ------------- Required header parameter "X-Giznet-Public-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Public-Key")]; found {
		var XGiznetPublicKey string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Public-Key, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Public-Key", valueList[0], &XGiznetPublicKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Public-Key: %w", err).Error())
		}

		params.XGiznetPublicKey = XGiznetPublicKey

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Public-Key is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	// ------------- Required header parameter "X-Giznet-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Timestamp")]; found {
		var XGiznetTimestamp int64
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Timestamp, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Timestamp", valueList[0], &XGiznetTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "integer", Format: "int64"})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Timestamp: %w", err).Error())
		}

		params.XGiznetTimestamp = XGiznetTimestamp

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Timestamp is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	// ------------- Required header parameter "X-Giznet-Nonce" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Nonce")]; found {
		var XGiznetNonce string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Nonce, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Nonce", valueList[0], &XGiznetNonce, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Nonce: %w", err).Error())
		}

		params.XGiznetNonce = XGiznetNonce

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Nonce is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	return siw.Handler.CreateGiznetWebRTCOffer(c, params)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/login", wrapper.Login)

	router.Get(options.BaseURL+"/me", wrapper.GetMe)

	router.Get(options.BaseURL+"/me/runtime", wrapper.GetMeRuntime)

	router.Get(options.BaseURL+"/me/status", wrapper.GetMeStatus)

	router.Put(options.BaseURL+"/me/status", wrapper.PutMeStatus)

	router.Get(options.BaseURL+"/server-info", wrapper.GetServerInfo)

	router.Post(options.BaseURL+"/webrtc/v1/offer", wrapper.CreateGiznetWebRTCOffer)

}

type LoginRequestObject struct {
	Params LoginParams
}

type LoginResponseObject interface {
	VisitLoginResponse(ctx *fiber.Ctx) error
}

type Login200JSONResponse LoginResult

func (response Login200JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type Login401JSONResponse externalRef0.ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(ctx *fiber.Ctx) error
}

type GetMe200JSONResponse PeerSelf

func (response GetMe200JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMe401JSONResponse externalRef0.ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMe404JSONResponse externalRef0.ErrorResponse

func (response GetMe404JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetMe500JSONResponse externalRef0.ErrorResponse

func (response GetMe500JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetMeRuntimeRequestObject struct {
}

type GetMeRuntimeResponseObject interface {
	VisitGetMeRuntimeResponse(ctx *fiber.Ctx) error
}

type GetMeRuntime200JSONResponse externalRef0.Runtime

func (response GetMeRuntime200JSONResponse) VisitGetMeRuntimeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMeRuntime401JSONResponse externalRef0.ErrorResponse

func (response GetMeRuntime401JSONResponse) VisitGetMeRuntimeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMeRuntime404JSONResponse externalRef0.ErrorResponse

func (response GetMeRuntime404JSONResponse) VisitGetMeRuntimeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetMeRuntime500JSONResponse externalRef0.ErrorResponse

func (response GetMeRuntime500JSONResponse) VisitGetMeRuntimeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetMeStatusRequestObject struct {
}

type GetMeStatusResponseObject interface {
	VisitGetMeStatusResponse(ctx *fiber.Ctx) error
}

type GetMeStatus200JSONResponse externalRef0.PeerStatus

func (response GetMeStatus200JSONResponse) VisitGetMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMeStatus401JSONResponse externalRef0.ErrorResponse

func (response GetMeStatus401JSONResponse) VisitGetMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMeStatus404JSONResponse externalRef0.ErrorResponse

func (response GetMeStatus404JSONResponse) VisitGetMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetMeStatus500JSONResponse externalRef0.ErrorResponse

func (response GetMeStatus500JSONResponse) VisitGetMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type PutMeStatusRequestObject struct {
	Body *PutMeStatusJSONRequestBody
}

type PutMeStatusResponseObject interface {
	VisitPutMeStatusResponse(ctx *fiber.Ctx) error
}

type PutMeStatus200JSONResponse externalRef0.PeerStatus

func (response PutMeStatus200JSONResponse) VisitPutMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PutMeStatus400JSONResponse externalRef0.ErrorResponse

func (response PutMeStatus400JSONResponse) VisitPutMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type PutMeStatus401JSONResponse externalRef0.ErrorResponse

func (response PutMeStatus401JSONResponse) VisitPutMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type PutMeStatus404JSONResponse externalRef0.ErrorResponse

func (response PutMeStatus404JSONResponse) VisitPutMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type PutMeStatus500JSONResponse externalRef0.ErrorResponse

func (response PutMeStatus500JSONResponse) VisitPutMeStatusResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetServerInfoRequestObject struct {
}

type GetServerInfoResponseObject interface {
	VisitGetServerInfoResponse(ctx *fiber.Ctx) error
}

type GetServerInfo200JSONResponse externalRef0.ServerInfo

func (response GetServerInfo200JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetServerInfo400JSONResponse externalRef0.ErrorResponse

func (response GetServerInfo400JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOfferRequestObject struct {
	Params CreateGiznetWebRTCOfferParams
	Body   io.Reader
}

type CreateGiznetWebRTCOfferResponseObject interface {
	VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error
}

type CreateGiznetWebRTCOffer200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateGiznetWebRTCOffer200ApplicationoctetStreamResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type CreateGiznetWebRTCOffer400JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer400JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer401JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer401JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer403JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer403JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer409JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer409JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer413JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer413JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(413)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer415JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer415JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(415)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer500JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer500JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer503JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer503JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(503)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Exchange a device assertion for a bearer session
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Get caller peer summary
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Get caller peer runtime
	// (GET /me/runtime)
	GetMeRuntime(ctx context.Context, request GetMeRuntimeRequestObject) (GetMeRuntimeResponseObject, error)
	// Get caller peer status
	// (GET /me/status)
	GetMeStatus(ctx context.Context, request GetMeStatusRequestObject) (GetMeStatusResponseObject, error)
	// Update caller peer status
	// (PUT /me/status)
	PutMeStatus(ctx context.Context, request PutMeStatusRequestObject) (PutMeStatusResponseObject, error)
	// Get server information
	// (GET /server-info)
	GetServerInfo(ctx context.Context, request GetServerInfoRequestObject) (GetServerInfoResponseObject, error)
	// Create a WebRTC answer for an encrypted browser offer
	// (POST /webrtc/v1/offer)
	CreateGiznetWebRTCOffer(ctx context.Context, request CreateGiznetWebRTCOfferRequestObject) (CreateGiznetWebRTCOfferResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *fiber.Ctx, params LoginParams) error {
	var request LoginRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.UserContext(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *fiber.Ctx) error {
	var request GetMeRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.UserContext(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMeRuntime operation middleware
func (sh *strictHandler) GetMeRuntime(ctx *fiber.Ctx) error {
	var request GetMeRuntimeRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeRuntime(ctx.UserContext(), request.(GetMeRuntimeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeRuntime")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMeRuntimeResponseObject); ok {
		if err := validResponse.VisitGetMeRuntimeResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMeStatus operation middleware
func (sh *strictHandler) GetMeStatus(ctx *fiber.Ctx) error {
	var request GetMeStatusRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMeStatus(ctx.UserContext(), request.(GetMeStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMeStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMeStatusResponseObject); ok {
		if err := validResponse.VisitGetMeStatusResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutMeStatus operation middleware
func (sh *strictHandler) PutMeStatus(ctx *fiber.Ctx) error {
	var request PutMeStatusRequestObject

	var body PutMeStatusJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PutMeStatus(ctx.UserContext(), request.(PutMeStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMeStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(PutMeStatusResponseObject); ok {
		if err := validResponse.VisitPutMeStatusResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetServerInfo operation middleware
func (sh *strictHandler) GetServerInfo(ctx *fiber.Ctx) error {
	var request GetServerInfoRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetServerInfo(ctx.UserContext(), request.(GetServerInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServerInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetServerInfoResponseObject); ok {
		if err := validResponse.VisitGetServerInfoResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateGiznetWebRTCOffer operation middleware
func (sh *strictHandler) CreateGiznetWebRTCOffer(ctx *fiber.Ctx, params CreateGiznetWebRTCOfferParams) error {
	var request CreateGiznetWebRTCOfferRequestObject

	request.Params = params

	request.Body = bytes.NewReader(ctx.Request().Body())

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGiznetWebRTCOffer(ctx.UserContext(), request.(CreateGiznetWebRTCOfferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGiznetWebRTCOffer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateGiznetWebRTCOfferResponseObject); ok {
		if err := validResponse.VisitCreateGiznetWebRTCOfferResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
