// Package peerhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package peerhttp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	externalRef0 "github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// APIKey defines model for APIKey.
type APIKey struct {
	// ApiKey Complete recoverable API key stored by the server.
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`

	// DisplayName Trimmed UTF-8 display name; the server enforces an 80-byte maximum.
	DisplayName   string `json:"display_name"`
	ManageApiKeys bool   `json:"manage_api_keys"`

	// Name Opaque API key identity.
	Name string `json:"name"`

	// Prefix Short display prefix; the complete API key is also returned.
	Prefix string `json:"prefix"`
}

// APIKeyCreateRequest defines model for APIKeyCreateRequest.
type APIKeyCreateRequest struct {
	// DisplayName Trimmed UTF-8 display name; the server enforces an 80-byte maximum.
	DisplayName   string `json:"display_name"`
	ManageApiKeys bool   `json:"manage_api_keys"`
}

// APIKeyCreateResult defines model for APIKeyCreateResult.
type APIKeyCreateResult struct {
	// ApiKey Complete recoverable API key.
	ApiKey string `json:"api_key"`
	Value  APIKey `json:"value"`
}

// APIKeyList defines model for APIKeyList.
type APIKeyList struct {
	Items      []APIKey `json:"items"`
	NextCursor *string  `json:"next_cursor,omitempty"`
}

// GiznetWebRTCSignalingError defines model for GiznetWebRTCSignalingError.
type GiznetWebRTCSignalingError struct {
	Error string `json:"error"`
}

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.ErrorResponse

// Conflict defines model for Conflict.
type Conflict = externalRef0.ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = externalRef0.ErrorResponse

// InternalError defines model for InternalError.
type InternalError = externalRef0.ErrorResponse

// NotFound defines model for NotFound.
type NotFound = externalRef0.ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = externalRef0.ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int32  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateGiznetWebRTCOfferParams defines parameters for CreateGiznetWebRTCOffer.
type CreateGiznetWebRTCOfferParams struct {
	// XGiznetPublicKey Client public key.
	XGiznetPublicKey string `json:"X-Giznet-Public-Key"`

	// XGiznetTimestamp Unix timestamp used by signaling AEAD derivation.
	XGiznetTimestamp int64 `json:"X-Giznet-Timestamp"`

	// XGiznetNonce Base64url nonce used by signaling AEAD derivation and replay checks.
	XGiznetNonce string `json:"X-Giznet-Nonce"`
}

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = APIKeyCreateRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAPIKeys request
	ListAPIKeys(ctx context.Context, params *ListAPIKeysParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAPIKeyWithBody request with any body
	CreateAPIKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAPIKey(ctx context.Context, body CreateAPIKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeSelfAPIKey request
	RevokeSelfAPIKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSelfAPIKey request
	GetSelfAPIKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeAPIKey request
	RevokeAPIKey(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAPIKey request
	GetAPIKey(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServerInfo request
	GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateGiznetWebRTCOfferWithBody request with any body
	CreateGiznetWebRTCOfferWithBody(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAPIKeys(ctx context.Context, params *ListAPIKeysParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAPIKeysRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAPIKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAPIKeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAPIKey(ctx context.Context, body CreateAPIKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAPIKeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeSelfAPIKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeSelfAPIKeyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSelfAPIKey(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSelfAPIKeyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeAPIKey(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeAPIKeyRequest(c.Server, apiKeyName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAPIKey(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAPIKeyRequest(c.Server, apiKeyName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateGiznetWebRTCOfferWithBody(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateGiznetWebRTCOfferRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAPIKeysRequest generates requests for ListAPIKeys
func NewListAPIKeysRequest(server string, params *ListAPIKeysParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAPIKeyRequest calls the generic CreateAPIKey builder with application/json body
func NewCreateAPIKeyRequest(server string, body CreateAPIKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAPIKeyRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAPIKeyRequestWithBody generates requests for CreateAPIKey with any type of body
func NewCreateAPIKeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeSelfAPIKeyRequest generates requests for RevokeSelfAPIKey
func NewRevokeSelfAPIKeyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys/self")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSelfAPIKeyRequest generates requests for GetSelfAPIKey
func NewGetSelfAPIKeyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys/self")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeAPIKeyRequest generates requests for RevokeAPIKey
func NewRevokeAPIKeyRequest(server string, apiKeyName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "apiKeyName", apiKeyName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAPIKeyRequest generates requests for GetAPIKey
func NewGetAPIKeyRequest(server string, apiKeyName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "apiKeyName", apiKeyName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gizclaw/v1/api-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServerInfoRequest generates requests for GetServerInfo
func NewGetServerInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/server-info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateGiznetWebRTCOfferRequestWithBody generates requests for CreateGiznetWebRTCOffer with any type of body
func NewCreateGiznetWebRTCOfferRequestWithBody(server string, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/webrtc/v1/offer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Public-Key", params.XGiznetPublicKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Public-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Timestamp", params.XGiznetTimestamp, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "integer", Format: "int64"})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Timestamp", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithOptions("simple", false, "X-Giznet-Nonce", params.XGiznetNonce, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Giznet-Nonce", headerParam2)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAPIKeysWithResponse request
	ListAPIKeysWithResponse(ctx context.Context, params *ListAPIKeysParams, reqEditors ...RequestEditorFn) (*ListAPIKeysResponse, error)

	// CreateAPIKeyWithBodyWithResponse request with any body
	CreateAPIKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAPIKeyResponse, error)

	CreateAPIKeyWithResponse(ctx context.Context, body CreateAPIKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAPIKeyResponse, error)

	// RevokeSelfAPIKeyWithResponse request
	RevokeSelfAPIKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeSelfAPIKeyResponse, error)

	// GetSelfAPIKeyWithResponse request
	GetSelfAPIKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSelfAPIKeyResponse, error)

	// RevokeAPIKeyWithResponse request
	RevokeAPIKeyWithResponse(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*RevokeAPIKeyResponse, error)

	// GetAPIKeyWithResponse request
	GetAPIKeyWithResponse(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*GetAPIKeyResponse, error)

	// GetServerInfoWithResponse request
	GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error)

	// CreateGiznetWebRTCOfferWithBodyWithResponse request with any body
	CreateGiznetWebRTCOfferWithBodyWithResponse(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGiznetWebRTCOfferResponse, error)
}

type ListAPIKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *APIKeyList
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r ListAPIKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAPIKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAPIKeysResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateAPIKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *APIKeyCreateResult
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r CreateAPIKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAPIKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateAPIKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeSelfAPIKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r RevokeSelfAPIKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeSelfAPIKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeSelfAPIKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSelfAPIKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *APIKey
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetSelfAPIKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSelfAPIKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSelfAPIKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeAPIKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r RevokeAPIKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeAPIKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeAPIKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAPIKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *APIKey
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetAPIKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAPIKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAPIKeyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetServerInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.ServerInfo
	JSON400      *BadRequest
}

// Status returns HTTPResponse.Status
func (r GetServerInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetServerInfoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateGiznetWebRTCOfferResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *GiznetWebRTCSignalingError
	JSON401      *GiznetWebRTCSignalingError
	JSON403      *GiznetWebRTCSignalingError
	JSON409      *GiznetWebRTCSignalingError
	JSON413      *GiznetWebRTCSignalingError
	JSON415      *GiznetWebRTCSignalingError
	JSON500      *GiznetWebRTCSignalingError
	JSON503      *GiznetWebRTCSignalingError
}

// Status returns HTTPResponse.Status
func (r CreateGiznetWebRTCOfferResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateGiznetWebRTCOfferResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateGiznetWebRTCOfferResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListAPIKeysWithResponse request returning *ListAPIKeysResponse
func (c *ClientWithResponses) ListAPIKeysWithResponse(ctx context.Context, params *ListAPIKeysParams, reqEditors ...RequestEditorFn) (*ListAPIKeysResponse, error) {
	rsp, err := c.ListAPIKeys(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAPIKeysResponse(rsp)
}

// CreateAPIKeyWithBodyWithResponse request with arbitrary body returning *CreateAPIKeyResponse
func (c *ClientWithResponses) CreateAPIKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAPIKeyResponse, error) {
	rsp, err := c.CreateAPIKeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAPIKeyResponse(rsp)
}

func (c *ClientWithResponses) CreateAPIKeyWithResponse(ctx context.Context, body CreateAPIKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAPIKeyResponse, error) {
	rsp, err := c.CreateAPIKey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAPIKeyResponse(rsp)
}

// RevokeSelfAPIKeyWithResponse request returning *RevokeSelfAPIKeyResponse
func (c *ClientWithResponses) RevokeSelfAPIKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeSelfAPIKeyResponse, error) {
	rsp, err := c.RevokeSelfAPIKey(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeSelfAPIKeyResponse(rsp)
}

// GetSelfAPIKeyWithResponse request returning *GetSelfAPIKeyResponse
func (c *ClientWithResponses) GetSelfAPIKeyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSelfAPIKeyResponse, error) {
	rsp, err := c.GetSelfAPIKey(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSelfAPIKeyResponse(rsp)
}

// RevokeAPIKeyWithResponse request returning *RevokeAPIKeyResponse
func (c *ClientWithResponses) RevokeAPIKeyWithResponse(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*RevokeAPIKeyResponse, error) {
	rsp, err := c.RevokeAPIKey(ctx, apiKeyName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeAPIKeyResponse(rsp)
}

// GetAPIKeyWithResponse request returning *GetAPIKeyResponse
func (c *ClientWithResponses) GetAPIKeyWithResponse(ctx context.Context, apiKeyName string, reqEditors ...RequestEditorFn) (*GetAPIKeyResponse, error) {
	rsp, err := c.GetAPIKey(ctx, apiKeyName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAPIKeyResponse(rsp)
}

// GetServerInfoWithResponse request returning *GetServerInfoResponse
func (c *ClientWithResponses) GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error) {
	rsp, err := c.GetServerInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerInfoResponse(rsp)
}

// CreateGiznetWebRTCOfferWithBodyWithResponse request with arbitrary body returning *CreateGiznetWebRTCOfferResponse
func (c *ClientWithResponses) CreateGiznetWebRTCOfferWithBodyWithResponse(ctx context.Context, params *CreateGiznetWebRTCOfferParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateGiznetWebRTCOfferResponse, error) {
	rsp, err := c.CreateGiznetWebRTCOfferWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateGiznetWebRTCOfferResponse(rsp)
}

// ParseListAPIKeysResponse parses an HTTP response from a ListAPIKeysWithResponse call
func ParseListAPIKeysResponse(rsp *http.Response) (*ListAPIKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAPIKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest APIKeyList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAPIKeyResponse parses an HTTP response from a CreateAPIKeyWithResponse call
func ParseCreateAPIKeyResponse(rsp *http.Response) (*CreateAPIKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAPIKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest APIKeyCreateResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRevokeSelfAPIKeyResponse parses an HTTP response from a RevokeSelfAPIKeyWithResponse call
func ParseRevokeSelfAPIKeyResponse(rsp *http.Response) (*RevokeSelfAPIKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeSelfAPIKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetSelfAPIKeyResponse parses an HTTP response from a GetSelfAPIKeyWithResponse call
func ParseGetSelfAPIKeyResponse(rsp *http.Response) (*GetSelfAPIKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSelfAPIKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest APIKey
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRevokeAPIKeyResponse parses an HTTP response from a RevokeAPIKeyWithResponse call
func ParseRevokeAPIKeyResponse(rsp *http.Response) (*RevokeAPIKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeAPIKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAPIKeyResponse parses an HTTP response from a GetAPIKeyWithResponse call
func ParseGetAPIKeyResponse(rsp *http.Response) (*GetAPIKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAPIKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest APIKey
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetServerInfoResponse parses an HTTP response from a GetServerInfoWithResponse call
func ParseGetServerInfoResponse(rsp *http.Response) (*GetServerInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.ServerInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseCreateGiznetWebRTCOfferResponse parses an HTTP response from a CreateGiznetWebRTCOfferWithResponse call
func ParseCreateGiznetWebRTCOfferResponse(rsp *http.Response) (*CreateGiznetWebRTCOfferResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateGiznetWebRTCOfferResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest GiznetWebRTCSignalingError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List API keys owned by the caller's device
	// (GET /gizclaw/v1/api-keys)
	ListAPIKeys(c *fiber.Ctx, params ListAPIKeysParams) error
	// Create an API key for the caller's device
	// (POST /gizclaw/v1/api-keys)
	CreateAPIKey(c *fiber.Ctx) error
	// Revoke the current API key
	// (DELETE /gizclaw/v1/api-keys/self)
	RevokeSelfAPIKey(c *fiber.Ctx) error
	// Get the current API key
	// (GET /gizclaw/v1/api-keys/self)
	GetSelfAPIKey(c *fiber.Ctx) error
	// Revoke an API key owned by the caller's device
	// (DELETE /gizclaw/v1/api-keys/{apiKeyName})
	RevokeAPIKey(c *fiber.Ctx, apiKeyName string) error
	// Get an API key owned by the caller's device
	// (GET /gizclaw/v1/api-keys/{apiKeyName})
	GetAPIKey(c *fiber.Ctx, apiKeyName string) error
	// Get server information
	// (GET /server-info)
	GetServerInfo(c *fiber.Ctx) error
	// Create a WebRTC answer for an encrypted browser offer
	// (POST /webrtc/v1/offer)
	CreateGiznetWebRTCOffer(c *fiber.Ctx, params CreateGiznetWebRTCOfferParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(c *fiber.Ctx) error {

	var err error
	_ = err

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAPIKeysParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", query, &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListAPIKeys(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(c *fiber.Ctx) error {

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CreateAPIKey(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// RevokeSelfAPIKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeSelfAPIKey(c *fiber.Ctx) error {

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.RevokeSelfAPIKey(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSelfAPIKey operation middleware
func (siw *ServerInterfaceWrapper) GetSelfAPIKey(c *fiber.Ctx) error {

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSelfAPIKey(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// RevokeAPIKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeAPIKey(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "apiKeyName" -------------
	var apiKeyName string

	err = runtime.BindStyledParameterWithOptions("simple", "apiKeyName", c.Params("apiKeyName"), &apiKeyName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter apiKeyName: %w", err).Error())
	}

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.RevokeAPIKey(c, apiKeyName)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetAPIKey operation middleware
func (siw *ServerInterfaceWrapper) GetAPIKey(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "apiKeyName" -------------
	var apiKeyName string

	err = runtime.BindStyledParameterWithOptions("simple", "apiKeyName", c.Params("apiKeyName"), &apiKeyName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter apiKeyName: %w", err).Error())
	}

	c.Context().SetUserValue((BearerAuthScopes), []string{})

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetAPIKey(c, apiKeyName)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetServerInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServerInfo(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetServerInfo(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateGiznetWebRTCOffer operation middleware
func (siw *ServerInterfaceWrapper) CreateGiznetWebRTCOffer(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateGiznetWebRTCOfferParams

	headers := c.GetReqHeaders()

	// ------------- Required header parameter "X-Giznet-Public-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Public-Key")]; found {
		var XGiznetPublicKey string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Public-Key, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Public-Key", valueList[0], &XGiznetPublicKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Public-Key: %w", err).Error())
		}

		params.XGiznetPublicKey = XGiznetPublicKey

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Public-Key is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	// ------------- Required header parameter "X-Giznet-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Timestamp")]; found {
		var XGiznetTimestamp int64
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Timestamp, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Timestamp", valueList[0], &XGiznetTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "integer", Format: "int64"})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Timestamp: %w", err).Error())
		}

		params.XGiznetTimestamp = XGiznetTimestamp

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Timestamp is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	// ------------- Required header parameter "X-Giznet-Nonce" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Giznet-Nonce")]; found {
		var XGiznetNonce string
		n := len(valueList)
		if n != 1 {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("Too many values for ParamName X-Giznet-Nonce, 1 is required, but %d found", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Giznet-Nonce", valueList[0], &XGiznetNonce, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter X-Giznet-Nonce: %w", err).Error())
		}

		params.XGiznetNonce = XGiznetNonce

	} else {
		err = fmt.Errorf("Header parameter X-Giznet-Nonce is required, but not found: %w", err)
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CreateGiznetWebRTCOffer(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/gizclaw/v1/api-keys", wrapper.ListAPIKeys)

	router.Post(options.BaseURL+"/gizclaw/v1/api-keys", wrapper.CreateAPIKey)

	router.Delete(options.BaseURL+"/gizclaw/v1/api-keys/self", wrapper.RevokeSelfAPIKey)

	router.Get(options.BaseURL+"/gizclaw/v1/api-keys/self", wrapper.GetSelfAPIKey)

	router.Delete(options.BaseURL+"/gizclaw/v1/api-keys/:apiKeyName", wrapper.RevokeAPIKey)

	router.Get(options.BaseURL+"/gizclaw/v1/api-keys/:apiKeyName", wrapper.GetAPIKey)

	router.Get(options.BaseURL+"/server-info", wrapper.GetServerInfo)

	router.Post(options.BaseURL+"/webrtc/v1/offer", wrapper.CreateGiznetWebRTCOffer)

}

type BadRequestJSONResponse externalRef0.ErrorResponse

type ConflictJSONResponse externalRef0.ErrorResponse

type ForbiddenJSONResponse externalRef0.ErrorResponse

type InternalErrorJSONResponse externalRef0.ErrorResponse

type NotFoundJSONResponse externalRef0.ErrorResponse

type UnauthorizedJSONResponse externalRef0.ErrorResponse

type ListAPIKeysRequestObject struct {
	Params ListAPIKeysParams
}

type ListAPIKeysResponseObject interface {
	VisitListAPIKeysResponse(ctx *fiber.Ctx) error
}

type ListAPIKeys200JSONResponse APIKeyList

func (response ListAPIKeys200JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListAPIKeys400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAPIKeys400JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type ListAPIKeys401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAPIKeys401JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListAPIKeys403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListAPIKeys403JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type ListAPIKeys409JSONResponse struct{ ConflictJSONResponse }

func (response ListAPIKeys409JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type ListAPIKeys500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListAPIKeys500JSONResponse) VisitListAPIKeysResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateAPIKeyRequestObject struct {
	Body *CreateAPIKeyJSONRequestBody
}

type CreateAPIKeyResponseObject interface {
	VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error
}

type CreateAPIKey201JSONResponse APIKeyCreateResult

func (response CreateAPIKey201JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateAPIKey400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAPIKey400JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateAPIKey401JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type CreateAPIKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateAPIKey403JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type CreateAPIKey409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAPIKey409JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateAPIKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateAPIKey500JSONResponse) VisitCreateAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type RevokeSelfAPIKeyRequestObject struct {
}

type RevokeSelfAPIKeyResponseObject interface {
	VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error
}

type RevokeSelfAPIKey204Response struct {
}

func (response RevokeSelfAPIKey204Response) VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type RevokeSelfAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeSelfAPIKey401JSONResponse) VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type RevokeSelfAPIKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeSelfAPIKey403JSONResponse) VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type RevokeSelfAPIKey409JSONResponse struct{ ConflictJSONResponse }

func (response RevokeSelfAPIKey409JSONResponse) VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type RevokeSelfAPIKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response RevokeSelfAPIKey500JSONResponse) VisitRevokeSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetSelfAPIKeyRequestObject struct {
}

type GetSelfAPIKeyResponseObject interface {
	VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error
}

type GetSelfAPIKey200JSONResponse APIKey

func (response GetSelfAPIKey200JSONResponse) VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetSelfAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSelfAPIKey401JSONResponse) VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetSelfAPIKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetSelfAPIKey403JSONResponse) VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetSelfAPIKey409JSONResponse struct{ ConflictJSONResponse }

func (response GetSelfAPIKey409JSONResponse) VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type GetSelfAPIKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSelfAPIKey500JSONResponse) VisitGetSelfAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type RevokeAPIKeyRequestObject struct {
	ApiKeyName string `json:"apiKeyName"`
}

type RevokeAPIKeyResponseObject interface {
	VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error
}

type RevokeAPIKey204Response struct {
}

func (response RevokeAPIKey204Response) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type RevokeAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeAPIKey401JSONResponse) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type RevokeAPIKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response RevokeAPIKey403JSONResponse) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type RevokeAPIKey404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeAPIKey404JSONResponse) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type RevokeAPIKey409JSONResponse struct{ ConflictJSONResponse }

func (response RevokeAPIKey409JSONResponse) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type RevokeAPIKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response RevokeAPIKey500JSONResponse) VisitRevokeAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetAPIKeyRequestObject struct {
	ApiKeyName string `json:"apiKeyName"`
}

type GetAPIKeyResponseObject interface {
	VisitGetAPIKeyResponse(ctx *fiber.Ctx) error
}

type GetAPIKey200JSONResponse APIKey

func (response GetAPIKey200JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetAPIKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAPIKey401JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetAPIKey403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAPIKey403JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type GetAPIKey404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAPIKey404JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetAPIKey409JSONResponse struct{ ConflictJSONResponse }

func (response GetAPIKey409JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type GetAPIKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetAPIKey500JSONResponse) VisitGetAPIKeyResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetServerInfoRequestObject struct {
}

type GetServerInfoResponseObject interface {
	VisitGetServerInfoResponse(ctx *fiber.Ctx) error
}

type GetServerInfo200JSONResponse externalRef0.ServerInfo

func (response GetServerInfo200JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetServerInfo400JSONResponse struct{ BadRequestJSONResponse }

func (response GetServerInfo400JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOfferRequestObject struct {
	Params CreateGiznetWebRTCOfferParams
	Body   io.Reader
}

type CreateGiznetWebRTCOfferResponseObject interface {
	VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error
}

type CreateGiznetWebRTCOffer200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateGiznetWebRTCOffer200ApplicationoctetStreamResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		ctx.Response().Header.Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	ctx.Status(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(ctx.Response().BodyWriter(), response.Body)
	return err
}

type CreateGiznetWebRTCOffer400JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer400JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer401JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer401JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer403JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer403JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer409JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer409JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer413JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer413JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(413)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer415JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer415JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(415)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer500JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer500JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type CreateGiznetWebRTCOffer503JSONResponse GiznetWebRTCSignalingError

func (response CreateGiznetWebRTCOffer503JSONResponse) VisitCreateGiznetWebRTCOfferResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(503)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List API keys owned by the caller's device
	// (GET /gizclaw/v1/api-keys)
	ListAPIKeys(ctx context.Context, request ListAPIKeysRequestObject) (ListAPIKeysResponseObject, error)
	// Create an API key for the caller's device
	// (POST /gizclaw/v1/api-keys)
	CreateAPIKey(ctx context.Context, request CreateAPIKeyRequestObject) (CreateAPIKeyResponseObject, error)
	// Revoke the current API key
	// (DELETE /gizclaw/v1/api-keys/self)
	RevokeSelfAPIKey(ctx context.Context, request RevokeSelfAPIKeyRequestObject) (RevokeSelfAPIKeyResponseObject, error)
	// Get the current API key
	// (GET /gizclaw/v1/api-keys/self)
	GetSelfAPIKey(ctx context.Context, request GetSelfAPIKeyRequestObject) (GetSelfAPIKeyResponseObject, error)
	// Revoke an API key owned by the caller's device
	// (DELETE /gizclaw/v1/api-keys/{apiKeyName})
	RevokeAPIKey(ctx context.Context, request RevokeAPIKeyRequestObject) (RevokeAPIKeyResponseObject, error)
	// Get an API key owned by the caller's device
	// (GET /gizclaw/v1/api-keys/{apiKeyName})
	GetAPIKey(ctx context.Context, request GetAPIKeyRequestObject) (GetAPIKeyResponseObject, error)
	// Get server information
	// (GET /server-info)
	GetServerInfo(ctx context.Context, request GetServerInfoRequestObject) (GetServerInfoResponseObject, error)
	// Create a WebRTC answer for an encrypted browser offer
	// (POST /webrtc/v1/offer)
	CreateGiznetWebRTCOffer(ctx context.Context, request CreateGiznetWebRTCOfferRequestObject) (CreateGiznetWebRTCOfferResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListAPIKeys operation middleware
func (sh *strictHandler) ListAPIKeys(ctx *fiber.Ctx, params ListAPIKeysParams) error {
	var request ListAPIKeysRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListAPIKeys(ctx.UserContext(), request.(ListAPIKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAPIKeys")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListAPIKeysResponseObject); ok {
		if err := validResponse.VisitListAPIKeysResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAPIKey operation middleware
func (sh *strictHandler) CreateAPIKey(ctx *fiber.Ctx) error {
	var request CreateAPIKeyRequestObject

	var body CreateAPIKeyJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAPIKey(ctx.UserContext(), request.(CreateAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateAPIKeyResponseObject); ok {
		if err := validResponse.VisitCreateAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RevokeSelfAPIKey operation middleware
func (sh *strictHandler) RevokeSelfAPIKey(ctx *fiber.Ctx) error {
	var request RevokeSelfAPIKeyRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeSelfAPIKey(ctx.UserContext(), request.(RevokeSelfAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeSelfAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RevokeSelfAPIKeyResponseObject); ok {
		if err := validResponse.VisitRevokeSelfAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSelfAPIKey operation middleware
func (sh *strictHandler) GetSelfAPIKey(ctx *fiber.Ctx) error {
	var request GetSelfAPIKeyRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetSelfAPIKey(ctx.UserContext(), request.(GetSelfAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSelfAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetSelfAPIKeyResponseObject); ok {
		if err := validResponse.VisitGetSelfAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RevokeAPIKey operation middleware
func (sh *strictHandler) RevokeAPIKey(ctx *fiber.Ctx, apiKeyName string) error {
	var request RevokeAPIKeyRequestObject

	request.ApiKeyName = apiKeyName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeAPIKey(ctx.UserContext(), request.(RevokeAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RevokeAPIKeyResponseObject); ok {
		if err := validResponse.VisitRevokeAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAPIKey operation middleware
func (sh *strictHandler) GetAPIKey(ctx *fiber.Ctx, apiKeyName string) error {
	var request GetAPIKeyRequestObject

	request.ApiKeyName = apiKeyName

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIKey(ctx.UserContext(), request.(GetAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetAPIKeyResponseObject); ok {
		if err := validResponse.VisitGetAPIKeyResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetServerInfo operation middleware
func (sh *strictHandler) GetServerInfo(ctx *fiber.Ctx) error {
	var request GetServerInfoRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetServerInfo(ctx.UserContext(), request.(GetServerInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServerInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetServerInfoResponseObject); ok {
		if err := validResponse.VisitGetServerInfoResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateGiznetWebRTCOffer operation middleware
func (sh *strictHandler) CreateGiznetWebRTCOffer(ctx *fiber.Ctx, params CreateGiznetWebRTCOfferParams) error {
	var request CreateGiznetWebRTCOfferRequestObject

	request.Params = params

	request.Body = bytes.NewReader(ctx.Request().Body())

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGiznetWebRTCOffer(ctx.UserContext(), request.(CreateGiznetWebRTCOfferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGiznetWebRTCOffer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(CreateGiznetWebRTCOfferResponseObject); ok {
		if err := validResponse.VisitCreateGiznetWebRTCOfferResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
