name: gizclaw
description: Dart and Flutter client SDK for GizClaw WebRTC peer connections.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cryptography: ^2.7.0
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.5.2
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  protoc_plugin: ^25.0.0
  test: ^1.26.3
