package rpcgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

type generatedFile struct {
	Name string
	Data []byte
}

func emitAll(model Model) ([]generatedFile, error) {
	var files []generatedFile
	emitters := []struct {
		name string
		fn   func(Model) ([]byte, error)
	}{
		{"gzc_rpc_methods.h", emitMethodsH},
		{"gzc_rpc_types.h", emitTypesH},
		{"gzc_rpc_encode.h", emitEncodeH},
		{"gzc_rpc_encode.c", emitEncodeC},
		{"gzc_rpc_decode.h", emitDecodeH},
		{"gzc_rpc_decode.c", emitDecodeC},
		{"gzc_rpc_generated.h", emitGeneratedH},
		{"README.md", emitReadme},
	}
	for _, e := range emitters {
		data, err := e.fn(model)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", e.name, err)
		}
		data = append(bytes.TrimRight(data, "\n"), '\n')
		files = append(files, generatedFile{Name: e.name, Data: data})
	}
	return files, nil
}

func writeFiles(cfg Config, files []generatedFile) error {
	for _, file := range files {
		path := filepath.Join(cfg.OutDir, file.Name)
		if cfg.Check {
			existing, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.Equal(existing, file.Data) {
				return fmt.Errorf("%s is not up to date", path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, file.Data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func cHeader() string {
	return "/* Code generated by tools/gzc-rpcgen. DO NOT EDIT. */\n\n"
}

func guard(name string) string {
	return upperIdent(name)
}

func sortFields(fields []Field) {
	sort.Slice(fields, func(i, j int) bool {
		return fields[i].JSONName < fields[j].JSONName
	})
}

func uniqueSchemas(model Model, pick func(Method) Schema) []Schema {
	seen := map[string]bool{}
	var out []Schema
	for _, method := range model.Methods {
		schema := pick(method)
		if seen[schema.Name] {
			continue
		}
		seen[schema.Name] = true
		out = append(out, schema)
	}
	return out
}
