import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// Name every output file so Go rejects a partially removed build, even when
// another file keeps the assets directory nonempty.
export function generateEmbed(root) {
  const output = join(root, "assets_generated.go");
  rmSync(output, { force: true });
  const files = [];
  function collect(directory) {
    for (const entry of readdirSync(join(root, directory), {
      withFileTypes: true,
    })) {
      const name = `${directory}/${entry.name}`;
      if (!/^[a-zA-Z0-9_./-]+$/.test(name)) {
        throw new Error(`Unsupported embedded asset path: ${name}`);
      }
      if (entry.isDirectory()) collect(name);
      else if (entry.isFile()) files.push(name);
      else throw new Error(`Embedded asset must be a regular file: ${name}`);
    }
  }
  collect("dist");
  const html = readFileSync(join(root, "dist/index.html"), "utf8");
  const references = [...html.matchAll(/(?:src|href)="\.\/(assets\/[^\"]+)"/g)];
  if (
    !references.some((ref) => ref[1].endsWith(".js")) ||
    !references.some((ref) => ref[1].endsWith(".css"))
  ) {
    throw new Error("Console HTML must reference built JavaScript and CSS");
  }
  for (const [, name] of references) {
    if (!files.includes(`dist/${name}`)) {
      throw new Error(`Console HTML references missing asset: ${name}`);
    }
  }
  writeFileSync(
    output,
    `// Code generated by embed.mjs; DO NOT EDIT.
package console

import "embed"

//go:embed ${files.sort().join(" ")}
var assets embed.FS
`,
  );
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  generateEmbed(fileURLToPath(new URL(".", import.meta.url)));
}
