package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGenerated(t *testing.T) {
	root := t.TempDir()
	generated := filepath.Join(root, "generated.go")
	if err := os.WriteFile(generated, []byte("// Code generated by test. DO NOT EDIT.\npackage generated\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	handwritten := filepath.Join(root, "handwritten.go")
	if err := os.WriteFile(handwritten, []byte("package handwritten\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if !isGenerated(root, "generated.go") {
		t.Fatal("generated Go header was not recognised")
	}
	if isGenerated(root, "handwritten.go") {
		t.Fatal("handwritten Go file was classified as generated")
	}
	if !isGenerated(root, "sdk/c/gizclaw/generated/rpc.pb.c") {
		t.Fatal("generator-owned directory was not recognised")
	}
}

func TestDiagnosticPath(t *testing.T) {
	path, ok := diagnosticPath("/repo/file.go:12:34: interface{} can be replaced by any")
	if !ok || path != "/repo/file.go" {
		t.Fatalf("diagnosticPath() = %q, %t", path, ok)
	}
	if _, ok := diagnosticPath("modernize failed to load package"); ok {
		t.Fatal("non-diagnostic output was accepted")
	}
}

func TestDiagnosticAbsolutePath(t *testing.T) {
	root := t.TempDir()
	path, err := diagnosticAbsolutePath(root, "examples/nested", "pkg/file.go")
	if err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(root, "examples/nested", "pkg/file.go")
	if path != want {
		t.Fatalf("diagnosticAbsolutePath() = %q, want %q", path, want)
	}
}
