// Device-owned single audio player control and playlist contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/audioplayer.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One playable item. URL is HTTPS, without embedded credentials (1..1024
// UTF-8 bytes). Display title and opaque catalog ref are optional (128 bytes).
type AudioPlayerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	SourceRef     *string                `protobuf:"bytes,3,opt,name=source_ref,json=sourceRef,proto3,oneof" json:"source_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPlayerItem) Reset() {
	*x = AudioPlayerItem{}
	mi := &file_payload_audioplayer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPlayerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPlayerItem) ProtoMessage() {}

func (x *AudioPlayerItem) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPlayerItem.ProtoReflect.Descriptor instead.
func (*AudioPlayerItem) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{0}
}

func (x *AudioPlayerItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AudioPlayerItem) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *AudioPlayerItem) GetSourceRef() string {
	if x != nil && x.SourceRef != nil {
		return *x.SourceRef
	}
	return ""
}

// One complete device snapshot. State is stopped/buffering/playing/ended/error;
// repeat is off/one/all. Index is zero-based and absent when no track is selected.
// Unknown duration is absent, not zero. Progress is actual playout time.
type AudioPlayerStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	State            string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CurrentIndex     *uint32                `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3,oneof" json:"current_index,omitempty"`
	PositionMs       uint64                 `protobuf:"varint,3,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	DurationMs       *uint64                `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	Repeat           string                 `protobuf:"bytes,5,opt,name=repeat,proto3" json:"repeat,omitempty"`
	PlaylistLength   uint32                 `protobuf:"varint,6,opt,name=playlist_length,json=playlistLength,proto3" json:"playlist_length,omitempty"`
	PlaylistRevision uint32                 `protobuf:"varint,7,opt,name=playlist_revision,json=playlistRevision,proto3" json:"playlist_revision,omitempty"`
	ErrorCode        *string                `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	ErrorMessage     *string                `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	ObservedAtUnixMs int64                  `protobuf:"varint,10,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AudioPlayerStatus) Reset() {
	*x = AudioPlayerStatus{}
	mi := &file_payload_audioplayer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPlayerStatus) ProtoMessage() {}

func (x *AudioPlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPlayerStatus.ProtoReflect.Descriptor instead.
func (*AudioPlayerStatus) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{1}
}

func (x *AudioPlayerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AudioPlayerStatus) GetCurrentIndex() uint32 {
	if x != nil && x.CurrentIndex != nil {
		return *x.CurrentIndex
	}
	return 0
}

func (x *AudioPlayerStatus) GetPositionMs() uint64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *AudioPlayerStatus) GetDurationMs() uint64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *AudioPlayerStatus) GetRepeat() string {
	if x != nil {
		return x.Repeat
	}
	return ""
}

func (x *AudioPlayerStatus) GetPlaylistLength() uint32 {
	if x != nil {
		return x.PlaylistLength
	}
	return 0
}

func (x *AudioPlayerStatus) GetPlaylistRevision() uint32 {
	if x != nil {
		return x.PlaylistRevision
	}
	return 0
}

func (x *AudioPlayerStatus) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *AudioPlayerStatus) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AudioPlayerStatus) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

type ClientDeviceAudioPlayerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerGetRequest) Reset() {
	*x = ClientDeviceAudioPlayerGetRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerGetRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerGetRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerGetRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{2}
}

type ClientDeviceAudioPlayerGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerGetResponse) Reset() {
	*x = ClientDeviceAudioPlayerGetResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerGetResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerGetResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerGetResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDeviceAudioPlayerGetResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

type ClientDeviceAudioPlayerPlaylistGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistGetRequest) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistGetRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistGetRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistGetRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistGetRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{4}
}

type ClientDeviceAudioPlayerPlaylistGetResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*AudioPlayerItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // At most 32 items, duplicates allowed.
	PlaylistRevision uint32                 `protobuf:"varint,2,opt,name=playlist_revision,json=playlistRevision,proto3" json:"playlist_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistGetResponse) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistGetResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistGetResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistGetResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistGetResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{5}
}

func (x *ClientDeviceAudioPlayerPlaylistGetResponse) GetItems() []*AudioPlayerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClientDeviceAudioPlayerPlaylistGetResponse) GetPlaylistRevision() uint32 {
	if x != nil {
		return x.PlaylistRevision
	}
	return 0
}

// Validate and reserve capacity before stopping/replacing. Failure preserves
// both the previous playlist and playback. Empty items clears the playlist.
type ClientDeviceAudioPlayerPlaylistSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AudioPlayerItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistSetRequest) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistSetRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistSetRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistSetRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistSetRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{6}
}

func (x *ClientDeviceAudioPlayerPlaylistSetRequest) GetItems() []*AudioPlayerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClientDeviceAudioPlayerPlaylistSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistSetResponse) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistSetResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistSetResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistSetResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistSetResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{7}
}

func (x *ClientDeviceAudioPlayerPlaylistSetResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

// Atomically append 1..32 items, respecting the total 32-item capacity. Does not
// interrupt playback or start a stopped/ended player. Never automatically retry.
type ClientDeviceAudioPlayerPlaylistAppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AudioPlayerItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistAppendRequest) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistAppendRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistAppendRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistAppendRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistAppendRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{8}
}

func (x *ClientDeviceAudioPlayerPlaylistAppendRequest) GetItems() []*AudioPlayerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ClientDeviceAudioPlayerPlaylistAppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlaylistAppendResponse) Reset() {
	*x = ClientDeviceAudioPlayerPlaylistAppendResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlaylistAppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlaylistAppendResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlaylistAppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlaylistAppendResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlaylistAppendResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{9}
}

func (x *ClientDeviceAudioPlayerPlaylistAppendResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

// Accept playback from the beginning of the selected track, replacing current
// playback. Response acknowledges acceptance; telemetry reports actual start.
type ClientDeviceAudioPlayerPlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *uint32                `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlayRequest) Reset() {
	*x = ClientDeviceAudioPlayerPlayRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlayRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlayRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlayRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{10}
}

func (x *ClientDeviceAudioPlayerPlayRequest) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ClientDeviceAudioPlayerPlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerPlayResponse) Reset() {
	*x = ClientDeviceAudioPlayerPlayResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerPlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerPlayResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerPlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerPlayResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerPlayResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{11}
}

func (x *ClientDeviceAudioPlayerPlayResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

// Idempotently stop, retaining the playlist and repeat mode.
type ClientDeviceAudioPlayerStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerStopRequest) Reset() {
	*x = ClientDeviceAudioPlayerStopRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerStopRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerStopRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerStopRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{12}
}

type ClientDeviceAudioPlayerStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerStopResponse) Reset() {
	*x = ClientDeviceAudioPlayerStopResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerStopResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerStopResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerStopResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{13}
}

func (x *ClientDeviceAudioPlayerStopResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

// off: stop after the list; one: repeat current track; all: repeat the list.
// Changing the mode does not interrupt the current track.
type ClientDeviceAudioPlayerModeSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repeat        string                 `protobuf:"bytes,1,opt,name=repeat,proto3" json:"repeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerModeSetRequest) Reset() {
	*x = ClientDeviceAudioPlayerModeSetRequest{}
	mi := &file_payload_audioplayer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerModeSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerModeSetRequest) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerModeSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerModeSetRequest.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerModeSetRequest) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{14}
}

func (x *ClientDeviceAudioPlayerModeSetRequest) GetRepeat() string {
	if x != nil {
		return x.Repeat
	}
	return ""
}

type ClientDeviceAudioPlayerModeSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *AudioPlayerStatus     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDeviceAudioPlayerModeSetResponse) Reset() {
	*x = ClientDeviceAudioPlayerModeSetResponse{}
	mi := &file_payload_audioplayer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeviceAudioPlayerModeSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeviceAudioPlayerModeSetResponse) ProtoMessage() {}

func (x *ClientDeviceAudioPlayerModeSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_audioplayer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeviceAudioPlayerModeSetResponse.ProtoReflect.Descriptor instead.
func (*ClientDeviceAudioPlayerModeSetResponse) Descriptor() ([]byte, []int) {
	return file_payload_audioplayer_proto_rawDescGZIP(), []int{15}
}

func (x *ClientDeviceAudioPlayerModeSetResponse) GetValue() *AudioPlayerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_payload_audioplayer_proto protoreflect.FileDescriptor

const file_payload_audioplayer_proto_rawDesc = "" +
	"\n" +
	"\x19payload/audioplayer.proto\x12\x0egizclaw.rpc.v1\"{\n" +
	"\x0fAudioPlayerItem\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\"\n" +
	"\n" +
	"source_ref\x18\x03 \x01(\tH\x01R\tsourceRef\x88\x01\x01B\b\n" +
	"\x06_titleB\r\n" +
	"\v_source_ref\"\xc8\x03\n" +
	"\x11AudioPlayerStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12(\n" +
	"\rcurrent_index\x18\x02 \x01(\rH\x00R\fcurrentIndex\x88\x01\x01\x12\x1f\n" +
	"\vposition_ms\x18\x03 \x01(\x04R\n" +
	"positionMs\x12$\n" +
	"\vduration_ms\x18\x04 \x01(\x04H\x01R\n" +
	"durationMs\x88\x01\x01\x12\x16\n" +
	"\x06repeat\x18\x05 \x01(\tR\x06repeat\x12'\n" +
	"\x0fplaylist_length\x18\x06 \x01(\rR\x0eplaylistLength\x12+\n" +
	"\x11playlist_revision\x18\a \x01(\rR\x10playlistRevision\x12\"\n" +
	"\n" +
	"error_code\x18\b \x01(\tH\x02R\terrorCode\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\t \x01(\tH\x03R\ferrorMessage\x88\x01\x01\x12-\n" +
	"\x13observed_at_unix_ms\x18\n" +
	" \x01(\x03R\x10observedAtUnixMsB\x10\n" +
	"\x0e_current_indexB\x0e\n" +
	"\f_duration_msB\r\n" +
	"\v_error_codeB\x10\n" +
	"\x0e_error_message\"#\n" +
	"!ClientDeviceAudioPlayerGetRequest\"]\n" +
	"\"ClientDeviceAudioPlayerGetResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05value\"+\n" +
	")ClientDeviceAudioPlayerPlaylistGetRequest\"\x90\x01\n" +
	"*ClientDeviceAudioPlayerPlaylistGetResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.gizclaw.rpc.v1.AudioPlayerItemR\x05items\x12+\n" +
	"\x11playlist_revision\x18\x02 \x01(\rR\x10playlistRevision\"b\n" +
	")ClientDeviceAudioPlayerPlaylistSetRequest\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.gizclaw.rpc.v1.AudioPlayerItemR\x05items\"e\n" +
	"*ClientDeviceAudioPlayerPlaylistSetResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05value\"e\n" +
	",ClientDeviceAudioPlayerPlaylistAppendRequest\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.gizclaw.rpc.v1.AudioPlayerItemR\x05items\"h\n" +
	"-ClientDeviceAudioPlayerPlaylistAppendResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05value\"I\n" +
	"\"ClientDeviceAudioPlayerPlayRequest\x12\x19\n" +
	"\x05index\x18\x01 \x01(\rH\x00R\x05index\x88\x01\x01B\b\n" +
	"\x06_index\"^\n" +
	"#ClientDeviceAudioPlayerPlayResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05value\"$\n" +
	"\"ClientDeviceAudioPlayerStopRequest\"^\n" +
	"#ClientDeviceAudioPlayerStopResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05value\"?\n" +
	"%ClientDeviceAudioPlayerModeSetRequest\x12\x16\n" +
	"\x06repeat\x18\x01 \x01(\tR\x06repeat\"a\n" +
	"&ClientDeviceAudioPlayerModeSetResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.AudioPlayerStatusR\x05valueB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_audioplayer_proto_rawDescOnce sync.Once
	file_payload_audioplayer_proto_rawDescData []byte
)

func file_payload_audioplayer_proto_rawDescGZIP() []byte {
	file_payload_audioplayer_proto_rawDescOnce.Do(func() {
		file_payload_audioplayer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_audioplayer_proto_rawDesc), len(file_payload_audioplayer_proto_rawDesc)))
	})
	return file_payload_audioplayer_proto_rawDescData
}

var file_payload_audioplayer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_payload_audioplayer_proto_goTypes = []any{
	(*AudioPlayerItem)(nil),                               // 0: gizclaw.rpc.v1.AudioPlayerItem
	(*AudioPlayerStatus)(nil),                             // 1: gizclaw.rpc.v1.AudioPlayerStatus
	(*ClientDeviceAudioPlayerGetRequest)(nil),             // 2: gizclaw.rpc.v1.ClientDeviceAudioPlayerGetRequest
	(*ClientDeviceAudioPlayerGetResponse)(nil),            // 3: gizclaw.rpc.v1.ClientDeviceAudioPlayerGetResponse
	(*ClientDeviceAudioPlayerPlaylistGetRequest)(nil),     // 4: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistGetRequest
	(*ClientDeviceAudioPlayerPlaylistGetResponse)(nil),    // 5: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistGetResponse
	(*ClientDeviceAudioPlayerPlaylistSetRequest)(nil),     // 6: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistSetRequest
	(*ClientDeviceAudioPlayerPlaylistSetResponse)(nil),    // 7: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistSetResponse
	(*ClientDeviceAudioPlayerPlaylistAppendRequest)(nil),  // 8: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistAppendRequest
	(*ClientDeviceAudioPlayerPlaylistAppendResponse)(nil), // 9: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistAppendResponse
	(*ClientDeviceAudioPlayerPlayRequest)(nil),            // 10: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlayRequest
	(*ClientDeviceAudioPlayerPlayResponse)(nil),           // 11: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlayResponse
	(*ClientDeviceAudioPlayerStopRequest)(nil),            // 12: gizclaw.rpc.v1.ClientDeviceAudioPlayerStopRequest
	(*ClientDeviceAudioPlayerStopResponse)(nil),           // 13: gizclaw.rpc.v1.ClientDeviceAudioPlayerStopResponse
	(*ClientDeviceAudioPlayerModeSetRequest)(nil),         // 14: gizclaw.rpc.v1.ClientDeviceAudioPlayerModeSetRequest
	(*ClientDeviceAudioPlayerModeSetResponse)(nil),        // 15: gizclaw.rpc.v1.ClientDeviceAudioPlayerModeSetResponse
}
var file_payload_audioplayer_proto_depIdxs = []int32{
	1, // 0: gizclaw.rpc.v1.ClientDeviceAudioPlayerGetResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	0, // 1: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistGetResponse.items:type_name -> gizclaw.rpc.v1.AudioPlayerItem
	0, // 2: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistSetRequest.items:type_name -> gizclaw.rpc.v1.AudioPlayerItem
	1, // 3: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistSetResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	0, // 4: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistAppendRequest.items:type_name -> gizclaw.rpc.v1.AudioPlayerItem
	1, // 5: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlaylistAppendResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	1, // 6: gizclaw.rpc.v1.ClientDeviceAudioPlayerPlayResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	1, // 7: gizclaw.rpc.v1.ClientDeviceAudioPlayerStopResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	1, // 8: gizclaw.rpc.v1.ClientDeviceAudioPlayerModeSetResponse.value:type_name -> gizclaw.rpc.v1.AudioPlayerStatus
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_payload_audioplayer_proto_init() }
func file_payload_audioplayer_proto_init() {
	if File_payload_audioplayer_proto != nil {
		return
	}
	file_payload_audioplayer_proto_msgTypes[0].OneofWrappers = []any{}
	file_payload_audioplayer_proto_msgTypes[1].OneofWrappers = []any{}
	file_payload_audioplayer_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_audioplayer_proto_rawDesc), len(file_payload_audioplayer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_audioplayer_proto_goTypes,
		DependencyIndexes: file_payload_audioplayer_proto_depIdxs,
		MessageInfos:      file_payload_audioplayer_proto_msgTypes,
	}.Build()
	File_payload_audioplayer_proto = out.File
	file_payload_audioplayer_proto_goTypes = nil
	file_payload_audioplayer_proto_depIdxs = nil
}
