// Peer RPC firmware payload protobuf schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/firmware.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirmwareGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       FirmwareChannelName    `protobuf:"varint,1,opt,name=channel,proto3,enum=gizclaw.rpc.v1.FirmwareChannelName" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareGetRequest) Reset() {
	*x = FirmwareGetRequest{}
	mi := &file_payload_firmware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareGetRequest) ProtoMessage() {}

func (x *FirmwareGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_firmware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareGetRequest.ProtoReflect.Descriptor instead.
func (*FirmwareGetRequest) Descriptor() ([]byte, []int) {
	return file_payload_firmware_proto_rawDescGZIP(), []int{0}
}

func (x *FirmwareGetRequest) GetChannel() FirmwareChannelName {
	if x != nil {
		return x.Channel
	}
	return FirmwareChannelName_FIRMWARE_CHANNEL_NAME_UNSPECIFIED
}

type FirmwareGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       FirmwareChannelName    `protobuf:"varint,1,opt,name=channel,proto3,enum=gizclaw.rpc.v1.FirmwareChannelName" json:"channel,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareGetResponse) Reset() {
	*x = FirmwareGetResponse{}
	mi := &file_payload_firmware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareGetResponse) ProtoMessage() {}

func (x *FirmwareGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_firmware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareGetResponse.ProtoReflect.Descriptor instead.
func (*FirmwareGetResponse) Descriptor() ([]byte, []int) {
	return file_payload_firmware_proto_rawDescGZIP(), []int{1}
}

func (x *FirmwareGetResponse) GetChannel() FirmwareChannelName {
	if x != nil {
		return x.Channel
	}
	return FirmwareChannelName_FIRMWARE_CHANNEL_NAME_UNSPECIFIED
}

func (x *FirmwareGetResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FirmwareGetResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FirmwareGetResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FirmwareGetResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ClientFirmwareUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *FirmwareChannelName   `protobuf:"varint,1,opt,name=channel,proto3,enum=gizclaw.rpc.v1.FirmwareChannelName,oneof" json:"channel,omitempty"`
	Sha256        *string                `protobuf:"bytes,2,opt,name=sha256,proto3,oneof" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFirmwareUpdateRequest) Reset() {
	*x = ClientFirmwareUpdateRequest{}
	mi := &file_payload_firmware_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFirmwareUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFirmwareUpdateRequest) ProtoMessage() {}

func (x *ClientFirmwareUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_firmware_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFirmwareUpdateRequest.ProtoReflect.Descriptor instead.
func (*ClientFirmwareUpdateRequest) Descriptor() ([]byte, []int) {
	return file_payload_firmware_proto_rawDescGZIP(), []int{2}
}

func (x *ClientFirmwareUpdateRequest) GetChannel() FirmwareChannelName {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return FirmwareChannelName_FIRMWARE_CHANNEL_NAME_UNSPECIFIED
}

func (x *ClientFirmwareUpdateRequest) GetSha256() string {
	if x != nil && x.Sha256 != nil {
		return *x.Sha256
	}
	return ""
}

type ClientFirmwareUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFirmwareUpdateResponse) Reset() {
	*x = ClientFirmwareUpdateResponse{}
	mi := &file_payload_firmware_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFirmwareUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFirmwareUpdateResponse) ProtoMessage() {}

func (x *ClientFirmwareUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_firmware_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFirmwareUpdateResponse.ProtoReflect.Descriptor instead.
func (*ClientFirmwareUpdateResponse) Descriptor() ([]byte, []int) {
	return file_payload_firmware_proto_rawDescGZIP(), []int{3}
}

var File_payload_firmware_proto protoreflect.FileDescriptor

const file_payload_firmware_proto_rawDesc = "" +
	"\n" +
	"\x16payload/firmware.proto\x12\x0egizclaw.rpc.v1\x1a\x13payload/enums.proto\"S\n" +
	"\x12FirmwareGetRequest\x12=\n" +
	"\achannel\x18\x01 \x01(\x0e2#.gizclaw.rpc.v1.FirmwareChannelNameR\achannel\"\xc9\x01\n" +
	"\x13FirmwareGetResponse\x12=\n" +
	"\achannel\x18\x01 \x01(\x0e2#.gizclaw.rpc.v1.FirmwareChannelNameR\achannel\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04sizeB\x0e\n" +
	"\f_description\"\x95\x01\n" +
	"\x1bClientFirmwareUpdateRequest\x12B\n" +
	"\achannel\x18\x01 \x01(\x0e2#.gizclaw.rpc.v1.FirmwareChannelNameH\x00R\achannel\x88\x01\x01\x12\x1b\n" +
	"\x06sha256\x18\x02 \x01(\tH\x01R\x06sha256\x88\x01\x01B\n" +
	"\n" +
	"\b_channelB\t\n" +
	"\a_sha256\"\x1e\n" +
	"\x1cClientFirmwareUpdateResponseB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_firmware_proto_rawDescOnce sync.Once
	file_payload_firmware_proto_rawDescData []byte
)

func file_payload_firmware_proto_rawDescGZIP() []byte {
	file_payload_firmware_proto_rawDescOnce.Do(func() {
		file_payload_firmware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_firmware_proto_rawDesc), len(file_payload_firmware_proto_rawDesc)))
	})
	return file_payload_firmware_proto_rawDescData
}

var file_payload_firmware_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payload_firmware_proto_goTypes = []any{
	(*FirmwareGetRequest)(nil),           // 0: gizclaw.rpc.v1.FirmwareGetRequest
	(*FirmwareGetResponse)(nil),          // 1: gizclaw.rpc.v1.FirmwareGetResponse
	(*ClientFirmwareUpdateRequest)(nil),  // 2: gizclaw.rpc.v1.ClientFirmwareUpdateRequest
	(*ClientFirmwareUpdateResponse)(nil), // 3: gizclaw.rpc.v1.ClientFirmwareUpdateResponse
	(FirmwareChannelName)(0),             // 4: gizclaw.rpc.v1.FirmwareChannelName
}
var file_payload_firmware_proto_depIdxs = []int32{
	4, // 0: gizclaw.rpc.v1.FirmwareGetRequest.channel:type_name -> gizclaw.rpc.v1.FirmwareChannelName
	4, // 1: gizclaw.rpc.v1.FirmwareGetResponse.channel:type_name -> gizclaw.rpc.v1.FirmwareChannelName
	4, // 2: gizclaw.rpc.v1.ClientFirmwareUpdateRequest.channel:type_name -> gizclaw.rpc.v1.FirmwareChannelName
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payload_firmware_proto_init() }
func file_payload_firmware_proto_init() {
	if File_payload_firmware_proto != nil {
		return
	}
	file_payload_enums_proto_init()
	file_payload_firmware_proto_msgTypes[1].OneofWrappers = []any{}
	file_payload_firmware_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_firmware_proto_rawDesc), len(file_payload_firmware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_firmware_proto_goTypes,
		DependencyIndexes: file_payload_firmware_proto_depIdxs,
		MessageInfos:      file_payload_firmware_proto_msgTypes,
	}.Build()
	File_payload_firmware_proto = out.File
	file_payload_firmware_proto_goTypes = nil
	file_payload_firmware_proto_depIdxs = nil
}
