// GizClaw-owned MHS v0 hardware device definitions (HWDs).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/mhs_v0.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientHwd int32

const (
	ClientHwd_CLIENT_HWD_UNSPECIFIED ClientHwd = 0
	ClientHwd_CLIENT_HWD_WIFI        ClientHwd = 1
	ClientHwd_CLIENT_HWD_BLE         ClientHwd = 2
	ClientHwd_CLIENT_HWD_MODEM       ClientHwd = 3
	ClientHwd_CLIENT_HWD_BATTERY     ClientHwd = 4
	ClientHwd_CLIENT_HWD_MIC         ClientHwd = 5
	ClientHwd_CLIENT_HWD_DISPLAY     ClientHwd = 6
	ClientHwd_CLIENT_HWD_LED         ClientHwd = 7
	ClientHwd_CLIENT_HWD_SPEAKER     ClientHwd = 8
)

// Enum value maps for ClientHwd.
var (
	ClientHwd_name = map[int32]string{
		0: "CLIENT_HWD_UNSPECIFIED",
		1: "CLIENT_HWD_WIFI",
		2: "CLIENT_HWD_BLE",
		3: "CLIENT_HWD_MODEM",
		4: "CLIENT_HWD_BATTERY",
		5: "CLIENT_HWD_MIC",
		6: "CLIENT_HWD_DISPLAY",
		7: "CLIENT_HWD_LED",
		8: "CLIENT_HWD_SPEAKER",
	}
	ClientHwd_value = map[string]int32{
		"CLIENT_HWD_UNSPECIFIED": 0,
		"CLIENT_HWD_WIFI":        1,
		"CLIENT_HWD_BLE":         2,
		"CLIENT_HWD_MODEM":       3,
		"CLIENT_HWD_BATTERY":     4,
		"CLIENT_HWD_MIC":         5,
		"CLIENT_HWD_DISPLAY":     6,
		"CLIENT_HWD_LED":         7,
		"CLIENT_HWD_SPEAKER":     8,
	}
)

func (x ClientHwd) Enum() *ClientHwd {
	p := new(ClientHwd)
	*p = x
	return p
}

func (x ClientHwd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientHwd) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_mhs_v0_proto_enumTypes[0].Descriptor()
}

func (ClientHwd) Type() protoreflect.EnumType {
	return &file_payload_mhs_v0_proto_enumTypes[0]
}

func (x ClientHwd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientHwd.Descriptor instead.
func (ClientHwd) EnumDescriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{0}
}

// An HWD identifies the shape of one hardware instance, not its instance ID.
// A RuntimeProfile manifest lists the instances present on a product. Read-only
// HWDs have no write messages. The message names are the source for SDK codecs.
type ClientHwdOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadResponse  string                 `protobuf:"bytes,2,opt,name=read_response,json=readResponse,proto3" json:"read_response,omitempty"`
	WriteRequest  string                 `protobuf:"bytes,3,opt,name=write_request,json=writeRequest,proto3" json:"write_request,omitempty"`
	WriteResponse string                 `protobuf:"bytes,4,opt,name=write_response,json=writeResponse,proto3" json:"write_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHwdOptions) Reset() {
	*x = ClientHwdOptions{}
	mi := &file_payload_mhs_v0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHwdOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHwdOptions) ProtoMessage() {}

func (x *ClientHwdOptions) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHwdOptions.ProtoReflect.Descriptor instead.
func (*ClientHwdOptions) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHwdOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientHwdOptions) GetReadResponse() string {
	if x != nil {
		return x.ReadResponse
	}
	return ""
}

func (x *ClientHwdOptions) GetWriteRequest() string {
	if x != nil {
		return x.WriteRequest
	}
	return ""
}

func (x *ClientHwdOptions) GetWriteResponse() string {
	if x != nil {
		return x.WriteResponse
	}
	return ""
}

// The Server checks the ID against the bound manifest and verifies the HWD
// before forwarding. A device returns NOT_FOUND when the physical instance is
// absent, even if the RuntimeProfile advertises it. Failures use RpcStatus.
type ClientMhsV0ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hwd           ClientHwd              `protobuf:"varint,2,opt,name=hwd,proto3,enum=gizclaw.rpc.v1.ClientHwd" json:"hwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMhsV0ReadRequest) Reset() {
	*x = ClientMhsV0ReadRequest{}
	mi := &file_payload_mhs_v0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMhsV0ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMhsV0ReadRequest) ProtoMessage() {}

func (x *ClientMhsV0ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMhsV0ReadRequest.ProtoReflect.Descriptor instead.
func (*ClientMhsV0ReadRequest) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMhsV0ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientMhsV0ReadRequest) GetHwd() ClientHwd {
	if x != nil {
		return x.Hwd
	}
	return ClientHwd_CLIENT_HWD_UNSPECIFIED
}

// Present capabilities report the fields this concrete instance can write.
// Omitted capabilities mean unknown; fields in a generic HWD schema do not
// imply write support on a particular device.
type MhsV0WriteCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []string               `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MhsV0WriteCapabilities) Reset() {
	*x = MhsV0WriteCapabilities{}
	mi := &file_payload_mhs_v0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MhsV0WriteCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MhsV0WriteCapabilities) ProtoMessage() {}

func (x *MhsV0WriteCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MhsV0WriteCapabilities.ProtoReflect.Descriptor instead.
func (*MhsV0WriteCapabilities) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{2}
}

func (x *MhsV0WriteCapabilities) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ClientMhsV0ReadResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Payload           []byte                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Encoded read_response message declared by hwd.
	WriteCapabilities *MhsV0WriteCapabilities `protobuf:"bytes,2,opt,name=write_capabilities,json=writeCapabilities,proto3,oneof" json:"write_capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientMhsV0ReadResponse) Reset() {
	*x = ClientMhsV0ReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMhsV0ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMhsV0ReadResponse) ProtoMessage() {}

func (x *ClientMhsV0ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMhsV0ReadResponse.ProtoReflect.Descriptor instead.
func (*ClientMhsV0ReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMhsV0ReadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMhsV0ReadResponse) GetWriteCapabilities() *MhsV0WriteCapabilities {
	if x != nil {
		return x.WriteCapabilities
	}
	return nil
}

type ClientMhsV0WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hwd           ClientHwd              `protobuf:"varint,2,opt,name=hwd,proto3,enum=gizclaw.rpc.v1.ClientHwd" json:"hwd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Encoded write_request message declared by hwd.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMhsV0WriteRequest) Reset() {
	*x = ClientMhsV0WriteRequest{}
	mi := &file_payload_mhs_v0_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMhsV0WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMhsV0WriteRequest) ProtoMessage() {}

func (x *ClientMhsV0WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMhsV0WriteRequest.ProtoReflect.Descriptor instead.
func (*ClientMhsV0WriteRequest) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMhsV0WriteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientMhsV0WriteRequest) GetHwd() ClientHwd {
	if x != nil {
		return x.Hwd
	}
	return ClientHwd_CLIENT_HWD_UNSPECIFIED
}

func (x *ClientMhsV0WriteRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ClientMhsV0WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Encoded write_response message declared by hwd.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMhsV0WriteResponse) Reset() {
	*x = ClientMhsV0WriteResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMhsV0WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMhsV0WriteResponse) ProtoMessage() {}

func (x *ClientMhsV0WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMhsV0WriteResponse.ProtoReflect.Descriptor instead.
func (*ClientMhsV0WriteResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{5}
}

func (x *ClientMhsV0WriteResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Read-only HWDs. Optional fields distinguish a measured zero or false from
// an observation unavailable on this hardware revision.
type WifiHwdReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     *bool                  `protobuf:"varint,1,opt,name=connected,proto3,oneof" json:"connected,omitempty"`
	Ssid          *string                `protobuf:"bytes,2,opt,name=ssid,proto3,oneof" json:"ssid,omitempty"`
	Bssid         *string                `protobuf:"bytes,3,opt,name=bssid,proto3,oneof" json:"bssid,omitempty"`
	RssiDbm       *int32                 `protobuf:"varint,4,opt,name=rssi_dbm,json=rssiDbm,proto3,oneof" json:"rssi_dbm,omitempty"`
	Ip            *string                `protobuf:"bytes,5,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiHwdReadResponse) Reset() {
	*x = WifiHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiHwdReadResponse) ProtoMessage() {}

func (x *WifiHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiHwdReadResponse.ProtoReflect.Descriptor instead.
func (*WifiHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{6}
}

func (x *WifiHwdReadResponse) GetConnected() bool {
	if x != nil && x.Connected != nil {
		return *x.Connected
	}
	return false
}

func (x *WifiHwdReadResponse) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *WifiHwdReadResponse) GetBssid() string {
	if x != nil && x.Bssid != nil {
		return *x.Bssid
	}
	return ""
}

func (x *WifiHwdReadResponse) GetRssiDbm() int32 {
	if x != nil && x.RssiDbm != nil {
		return *x.RssiDbm
	}
	return 0
}

func (x *WifiHwdReadResponse) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

type BleHwdReadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Powered         *bool                  `protobuf:"varint,1,opt,name=powered,proto3,oneof" json:"powered,omitempty"`
	Advertising     *bool                  `protobuf:"varint,2,opt,name=advertising,proto3,oneof" json:"advertising,omitempty"`
	Scanning        *bool                  `protobuf:"varint,3,opt,name=scanning,proto3,oneof" json:"scanning,omitempty"`
	ConnectionCount *uint32                `protobuf:"varint,4,opt,name=connection_count,json=connectionCount,proto3,oneof" json:"connection_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BleHwdReadResponse) Reset() {
	*x = BleHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BleHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BleHwdReadResponse) ProtoMessage() {}

func (x *BleHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BleHwdReadResponse.ProtoReflect.Descriptor instead.
func (*BleHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{7}
}

func (x *BleHwdReadResponse) GetPowered() bool {
	if x != nil && x.Powered != nil {
		return *x.Powered
	}
	return false
}

func (x *BleHwdReadResponse) GetAdvertising() bool {
	if x != nil && x.Advertising != nil {
		return *x.Advertising
	}
	return false
}

func (x *BleHwdReadResponse) GetScanning() bool {
	if x != nil && x.Scanning != nil {
		return *x.Scanning
	}
	return false
}

func (x *BleHwdReadResponse) GetConnectionCount() uint32 {
	if x != nil && x.ConnectionCount != nil {
		return *x.ConnectionCount
	}
	return 0
}

type ModemHwdReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimPresent    *bool                  `protobuf:"varint,1,opt,name=sim_present,json=simPresent,proto3,oneof" json:"sim_present,omitempty"`
	Registered    *bool                  `protobuf:"varint,2,opt,name=registered,proto3,oneof" json:"registered,omitempty"`
	Rat           *string                `protobuf:"bytes,3,opt,name=rat,proto3,oneof" json:"rat,omitempty"`
	RssiDbm       *int32                 `protobuf:"varint,4,opt,name=rssi_dbm,json=rssiDbm,proto3,oneof" json:"rssi_dbm,omitempty"`
	SignalLevel   *uint32                `protobuf:"varint,5,opt,name=signal_level,json=signalLevel,proto3,oneof" json:"signal_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModemHwdReadResponse) Reset() {
	*x = ModemHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModemHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemHwdReadResponse) ProtoMessage() {}

func (x *ModemHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemHwdReadResponse.ProtoReflect.Descriptor instead.
func (*ModemHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{8}
}

func (x *ModemHwdReadResponse) GetSimPresent() bool {
	if x != nil && x.SimPresent != nil {
		return *x.SimPresent
	}
	return false
}

func (x *ModemHwdReadResponse) GetRegistered() bool {
	if x != nil && x.Registered != nil {
		return *x.Registered
	}
	return false
}

func (x *ModemHwdReadResponse) GetRat() string {
	if x != nil && x.Rat != nil {
		return *x.Rat
	}
	return ""
}

func (x *ModemHwdReadResponse) GetRssiDbm() int32 {
	if x != nil && x.RssiDbm != nil {
		return *x.RssiDbm
	}
	return 0
}

func (x *ModemHwdReadResponse) GetSignalLevel() uint32 {
	if x != nil && x.SignalLevel != nil {
		return *x.SignalLevel
	}
	return 0
}

type BatteryHwdReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       *float64               `protobuf:"fixed64,1,opt,name=percent,proto3,oneof" json:"percent,omitempty"`
	Charging      *bool                  `protobuf:"varint,2,opt,name=charging,proto3,oneof" json:"charging,omitempty"`
	VoltageMv     *float64               `protobuf:"fixed64,3,opt,name=voltage_mv,json=voltageMv,proto3,oneof" json:"voltage_mv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryHwdReadResponse) Reset() {
	*x = BatteryHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryHwdReadResponse) ProtoMessage() {}

func (x *BatteryHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryHwdReadResponse.ProtoReflect.Descriptor instead.
func (*BatteryHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{9}
}

func (x *BatteryHwdReadResponse) GetPercent() float64 {
	if x != nil && x.Percent != nil {
		return *x.Percent
	}
	return 0
}

func (x *BatteryHwdReadResponse) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

func (x *BatteryHwdReadResponse) GetVoltageMv() float64 {
	if x != nil && x.VoltageMv != nil {
		return *x.VoltageMv
	}
	return 0
}

type MicHwdReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     *bool                  `protobuf:"varint,1,opt,name=available,proto3,oneof" json:"available,omitempty"`
	Capturing     *bool                  `protobuf:"varint,2,opt,name=capturing,proto3,oneof" json:"capturing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicHwdReadResponse) Reset() {
	*x = MicHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicHwdReadResponse) ProtoMessage() {}

func (x *MicHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicHwdReadResponse.ProtoReflect.Descriptor instead.
func (*MicHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{10}
}

func (x *MicHwdReadResponse) GetAvailable() bool {
	if x != nil && x.Available != nil {
		return *x.Available
	}
	return false
}

func (x *MicHwdReadResponse) GetCapturing() bool {
	if x != nil && x.Capturing != nil {
		return *x.Capturing
	}
	return false
}

// Write requests update the present fields only. An empty request is invalid.
// Drivers enforce physical safety limits and return the values actually in
// effect. A timeout does not prove a write was not applied; re-read the HWD.
type DisplayHwdReadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BrightnessPercent *uint32                `protobuf:"varint,1,opt,name=brightness_percent,json=brightnessPercent,proto3,oneof" json:"brightness_percent,omitempty"`
	Enabled           *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	OffTimeoutMs      *uint32                `protobuf:"varint,3,opt,name=off_timeout_ms,json=offTimeoutMs,proto3,oneof" json:"off_timeout_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisplayHwdReadResponse) Reset() {
	*x = DisplayHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayHwdReadResponse) ProtoMessage() {}

func (x *DisplayHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayHwdReadResponse.ProtoReflect.Descriptor instead.
func (*DisplayHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{11}
}

func (x *DisplayHwdReadResponse) GetBrightnessPercent() uint32 {
	if x != nil && x.BrightnessPercent != nil {
		return *x.BrightnessPercent
	}
	return 0
}

func (x *DisplayHwdReadResponse) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *DisplayHwdReadResponse) GetOffTimeoutMs() uint32 {
	if x != nil && x.OffTimeoutMs != nil {
		return *x.OffTimeoutMs
	}
	return 0
}

type DisplayHwdWriteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BrightnessPercent *uint32                `protobuf:"varint,1,opt,name=brightness_percent,json=brightnessPercent,proto3,oneof" json:"brightness_percent,omitempty"`
	Enabled           *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	OffTimeoutMs      *uint32                `protobuf:"varint,3,opt,name=off_timeout_ms,json=offTimeoutMs,proto3,oneof" json:"off_timeout_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DisplayHwdWriteRequest) Reset() {
	*x = DisplayHwdWriteRequest{}
	mi := &file_payload_mhs_v0_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayHwdWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayHwdWriteRequest) ProtoMessage() {}

func (x *DisplayHwdWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayHwdWriteRequest.ProtoReflect.Descriptor instead.
func (*DisplayHwdWriteRequest) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{12}
}

func (x *DisplayHwdWriteRequest) GetBrightnessPercent() uint32 {
	if x != nil && x.BrightnessPercent != nil {
		return *x.BrightnessPercent
	}
	return 0
}

func (x *DisplayHwdWriteRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *DisplayHwdWriteRequest) GetOffTimeoutMs() uint32 {
	if x != nil && x.OffTimeoutMs != nil {
		return *x.OffTimeoutMs
	}
	return 0
}

type DisplayHwdWriteResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Applied       *DisplayHwdReadResponse `protobuf:"bytes,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayHwdWriteResponse) Reset() {
	*x = DisplayHwdWriteResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayHwdWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayHwdWriteResponse) ProtoMessage() {}

func (x *DisplayHwdWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayHwdWriteResponse.ProtoReflect.Descriptor instead.
func (*DisplayHwdWriteResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{13}
}

func (x *DisplayHwdWriteResponse) GetApplied() *DisplayHwdReadResponse {
	if x != nil {
		return x.Applied
	}
	return nil
}

type LedHwdReadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           *bool                  `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	BrightnessPercent *uint32                `protobuf:"varint,2,opt,name=brightness_percent,json=brightnessPercent,proto3,oneof" json:"brightness_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedHwdReadResponse) Reset() {
	*x = LedHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedHwdReadResponse) ProtoMessage() {}

func (x *LedHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedHwdReadResponse.ProtoReflect.Descriptor instead.
func (*LedHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{14}
}

func (x *LedHwdReadResponse) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *LedHwdReadResponse) GetBrightnessPercent() uint32 {
	if x != nil && x.BrightnessPercent != nil {
		return *x.BrightnessPercent
	}
	return 0
}

type LedHwdWriteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           *bool                  `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	BrightnessPercent *uint32                `protobuf:"varint,2,opt,name=brightness_percent,json=brightnessPercent,proto3,oneof" json:"brightness_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LedHwdWriteRequest) Reset() {
	*x = LedHwdWriteRequest{}
	mi := &file_payload_mhs_v0_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedHwdWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedHwdWriteRequest) ProtoMessage() {}

func (x *LedHwdWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedHwdWriteRequest.ProtoReflect.Descriptor instead.
func (*LedHwdWriteRequest) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{15}
}

func (x *LedHwdWriteRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *LedHwdWriteRequest) GetBrightnessPercent() uint32 {
	if x != nil && x.BrightnessPercent != nil {
		return *x.BrightnessPercent
	}
	return 0
}

type LedHwdWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       *LedHwdReadResponse    `protobuf:"bytes,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedHwdWriteResponse) Reset() {
	*x = LedHwdWriteResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedHwdWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedHwdWriteResponse) ProtoMessage() {}

func (x *LedHwdWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedHwdWriteResponse.ProtoReflect.Descriptor instead.
func (*LedHwdWriteResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{16}
}

func (x *LedHwdWriteResponse) GetApplied() *LedHwdReadResponse {
	if x != nil {
		return x.Applied
	}
	return nil
}

type SpeakerHwdReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumePercent *uint32                `protobuf:"varint,1,opt,name=volume_percent,json=volumePercent,proto3,oneof" json:"volume_percent,omitempty"`
	Muted         *bool                  `protobuf:"varint,2,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakerHwdReadResponse) Reset() {
	*x = SpeakerHwdReadResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerHwdReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerHwdReadResponse) ProtoMessage() {}

func (x *SpeakerHwdReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerHwdReadResponse.ProtoReflect.Descriptor instead.
func (*SpeakerHwdReadResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{17}
}

func (x *SpeakerHwdReadResponse) GetVolumePercent() uint32 {
	if x != nil && x.VolumePercent != nil {
		return *x.VolumePercent
	}
	return 0
}

func (x *SpeakerHwdReadResponse) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

type SpeakerHwdWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumePercent *uint32                `protobuf:"varint,1,opt,name=volume_percent,json=volumePercent,proto3,oneof" json:"volume_percent,omitempty"`
	Muted         *bool                  `protobuf:"varint,2,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakerHwdWriteRequest) Reset() {
	*x = SpeakerHwdWriteRequest{}
	mi := &file_payload_mhs_v0_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerHwdWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerHwdWriteRequest) ProtoMessage() {}

func (x *SpeakerHwdWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerHwdWriteRequest.ProtoReflect.Descriptor instead.
func (*SpeakerHwdWriteRequest) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{18}
}

func (x *SpeakerHwdWriteRequest) GetVolumePercent() uint32 {
	if x != nil && x.VolumePercent != nil {
		return *x.VolumePercent
	}
	return 0
}

func (x *SpeakerHwdWriteRequest) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

type SpeakerHwdWriteResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Applied       *SpeakerHwdReadResponse `protobuf:"bytes,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeakerHwdWriteResponse) Reset() {
	*x = SpeakerHwdWriteResponse{}
	mi := &file_payload_mhs_v0_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerHwdWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerHwdWriteResponse) ProtoMessage() {}

func (x *SpeakerHwdWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_mhs_v0_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerHwdWriteResponse.ProtoReflect.Descriptor instead.
func (*SpeakerHwdWriteResponse) Descriptor() ([]byte, []int) {
	return file_payload_mhs_v0_proto_rawDescGZIP(), []int{19}
}

func (x *SpeakerHwdWriteResponse) GetApplied() *SpeakerHwdReadResponse {
	if x != nil {
		return x.Applied
	}
	return nil
}

var file_payload_mhs_v0_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ClientHwdOptions)(nil),
		Field:         51002,
		Name:          "gizclaw.rpc.v1.client_hwd",
		Tag:           "bytes,51002,opt,name=client_hwd",
		Filename:      "payload/mhs_v0.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional gizclaw.rpc.v1.ClientHwdOptions client_hwd = 51002;
	E_ClientHwd = &file_payload_mhs_v0_proto_extTypes[0]
)

var File_payload_mhs_v0_proto protoreflect.FileDescriptor

const file_payload_mhs_v0_proto_rawDesc = "" +
	"\n" +
	"\x14payload/mhs_v0.proto\x12\x0egizclaw.rpc.v1\x1a google/protobuf/descriptor.proto\"\x97\x01\n" +
	"\x10ClientHwdOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rread_response\x18\x02 \x01(\tR\freadResponse\x12#\n" +
	"\rwrite_request\x18\x03 \x01(\tR\fwriteRequest\x12%\n" +
	"\x0ewrite_response\x18\x04 \x01(\tR\rwriteResponse\"U\n" +
	"\x16ClientMhsV0ReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x03hwd\x18\x02 \x01(\x0e2\x19.gizclaw.rpc.v1.ClientHwdR\x03hwd\"0\n" +
	"\x16MhsV0WriteCapabilities\x12\x16\n" +
	"\x06fields\x18\x01 \x03(\tR\x06fields\"\xa6\x01\n" +
	"\x17ClientMhsV0ReadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12Z\n" +
	"\x12write_capabilities\x18\x02 \x01(\v2&.gizclaw.rpc.v1.MhsV0WriteCapabilitiesH\x00R\x11writeCapabilities\x88\x01\x01B\x15\n" +
	"\x13_write_capabilities\"p\n" +
	"\x17ClientMhsV0WriteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x03hwd\x18\x02 \x01(\x0e2\x19.gizclaw.rpc.v1.ClientHwdR\x03hwd\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"4\n" +
	"\x18ClientMhsV0WriteResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xd6\x01\n" +
	"\x13WifiHwdReadResponse\x12!\n" +
	"\tconnected\x18\x01 \x01(\bH\x00R\tconnected\x88\x01\x01\x12\x17\n" +
	"\x04ssid\x18\x02 \x01(\tH\x01R\x04ssid\x88\x01\x01\x12\x19\n" +
	"\x05bssid\x18\x03 \x01(\tH\x02R\x05bssid\x88\x01\x01\x12\x1e\n" +
	"\brssi_dbm\x18\x04 \x01(\x05H\x03R\arssiDbm\x88\x01\x01\x12\x13\n" +
	"\x02ip\x18\x05 \x01(\tH\x04R\x02ip\x88\x01\x01B\f\n" +
	"\n" +
	"_connectedB\a\n" +
	"\x05_ssidB\b\n" +
	"\x06_bssidB\v\n" +
	"\t_rssi_dbmB\x05\n" +
	"\x03_ip\"\xe9\x01\n" +
	"\x12BleHwdReadResponse\x12\x1d\n" +
	"\apowered\x18\x01 \x01(\bH\x00R\apowered\x88\x01\x01\x12%\n" +
	"\vadvertising\x18\x02 \x01(\bH\x01R\vadvertising\x88\x01\x01\x12\x1f\n" +
	"\bscanning\x18\x03 \x01(\bH\x02R\bscanning\x88\x01\x01\x12.\n" +
	"\x10connection_count\x18\x04 \x01(\rH\x03R\x0fconnectionCount\x88\x01\x01B\n" +
	"\n" +
	"\b_poweredB\x0e\n" +
	"\f_advertisingB\v\n" +
	"\t_scanningB\x13\n" +
	"\x11_connection_count\"\x85\x02\n" +
	"\x14ModemHwdReadResponse\x12$\n" +
	"\vsim_present\x18\x01 \x01(\bH\x00R\n" +
	"simPresent\x88\x01\x01\x12#\n" +
	"\n" +
	"registered\x18\x02 \x01(\bH\x01R\n" +
	"registered\x88\x01\x01\x12\x15\n" +
	"\x03rat\x18\x03 \x01(\tH\x02R\x03rat\x88\x01\x01\x12\x1e\n" +
	"\brssi_dbm\x18\x04 \x01(\x05H\x03R\arssiDbm\x88\x01\x01\x12&\n" +
	"\fsignal_level\x18\x05 \x01(\rH\x04R\vsignalLevel\x88\x01\x01B\x0e\n" +
	"\f_sim_presentB\r\n" +
	"\v_registeredB\x06\n" +
	"\x04_ratB\v\n" +
	"\t_rssi_dbmB\x0f\n" +
	"\r_signal_level\"\xa4\x01\n" +
	"\x16BatteryHwdReadResponse\x12\x1d\n" +
	"\apercent\x18\x01 \x01(\x01H\x00R\apercent\x88\x01\x01\x12\x1f\n" +
	"\bcharging\x18\x02 \x01(\bH\x01R\bcharging\x88\x01\x01\x12\"\n" +
	"\n" +
	"voltage_mv\x18\x03 \x01(\x01H\x02R\tvoltageMv\x88\x01\x01B\n" +
	"\n" +
	"\b_percentB\v\n" +
	"\t_chargingB\r\n" +
	"\v_voltage_mv\"v\n" +
	"\x12MicHwdReadResponse\x12!\n" +
	"\tavailable\x18\x01 \x01(\bH\x00R\tavailable\x88\x01\x01\x12!\n" +
	"\tcapturing\x18\x02 \x01(\bH\x01R\tcapturing\x88\x01\x01B\f\n" +
	"\n" +
	"_availableB\f\n" +
	"\n" +
	"_capturing\"\xcc\x01\n" +
	"\x16DisplayHwdReadResponse\x122\n" +
	"\x12brightness_percent\x18\x01 \x01(\rH\x00R\x11brightnessPercent\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x01R\aenabled\x88\x01\x01\x12)\n" +
	"\x0eoff_timeout_ms\x18\x03 \x01(\rH\x02R\foffTimeoutMs\x88\x01\x01B\x15\n" +
	"\x13_brightness_percentB\n" +
	"\n" +
	"\b_enabledB\x11\n" +
	"\x0f_off_timeout_ms\"\xcc\x01\n" +
	"\x16DisplayHwdWriteRequest\x122\n" +
	"\x12brightness_percent\x18\x01 \x01(\rH\x00R\x11brightnessPercent\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x01R\aenabled\x88\x01\x01\x12)\n" +
	"\x0eoff_timeout_ms\x18\x03 \x01(\rH\x02R\foffTimeoutMs\x88\x01\x01B\x15\n" +
	"\x13_brightness_percentB\n" +
	"\n" +
	"\b_enabledB\x11\n" +
	"\x0f_off_timeout_ms\"[\n" +
	"\x17DisplayHwdWriteResponse\x12@\n" +
	"\aapplied\x18\x01 \x01(\v2&.gizclaw.rpc.v1.DisplayHwdReadResponseR\aapplied\"\x8a\x01\n" +
	"\x12LedHwdReadResponse\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x122\n" +
	"\x12brightness_percent\x18\x02 \x01(\rH\x01R\x11brightnessPercent\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\x15\n" +
	"\x13_brightness_percent\"\x8a\x01\n" +
	"\x12LedHwdWriteRequest\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x122\n" +
	"\x12brightness_percent\x18\x02 \x01(\rH\x01R\x11brightnessPercent\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\x15\n" +
	"\x13_brightness_percent\"S\n" +
	"\x13LedHwdWriteResponse\x12<\n" +
	"\aapplied\x18\x01 \x01(\v2\".gizclaw.rpc.v1.LedHwdReadResponseR\aapplied\"|\n" +
	"\x16SpeakerHwdReadResponse\x12*\n" +
	"\x0evolume_percent\x18\x01 \x01(\rH\x00R\rvolumePercent\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x02 \x01(\bH\x01R\x05muted\x88\x01\x01B\x11\n" +
	"\x0f_volume_percentB\b\n" +
	"\x06_muted\"|\n" +
	"\x16SpeakerHwdWriteRequest\x12*\n" +
	"\x0evolume_percent\x18\x01 \x01(\rH\x00R\rvolumePercent\x88\x01\x01\x12\x19\n" +
	"\x05muted\x18\x02 \x01(\bH\x01R\x05muted\x88\x01\x01B\x11\n" +
	"\x0f_volume_percentB\b\n" +
	"\x06_muted\"[\n" +
	"\x17SpeakerHwdWriteResponse\x12@\n" +
	"\aapplied\x18\x01 \x01(\v2&.gizclaw.rpc.v1.SpeakerHwdReadResponseR\aapplied*\xf7\x04\n" +
	"\tClientHwd\x12\x1a\n" +
	"\x16CLIENT_HWD_UNSPECIFIED\x10\x00\x124\n" +
	"\x0fCLIENT_HWD_WIFI\x10\x01\x1a\x1f\xd2\xf3\x18\x1b\n" +
	"\x04wifi\x12\x13WifiHwdReadResponse\x121\n" +
	"\x0eCLIENT_HWD_BLE\x10\x02\x1a\x1d\xd2\xf3\x18\x19\n" +
	"\x03ble\x12\x12BleHwdReadResponse\x127\n" +
	"\x10CLIENT_HWD_MODEM\x10\x03\x1a!\xd2\xf3\x18\x1d\n" +
	"\x05modem\x12\x14ModemHwdReadResponse\x12=\n" +
	"\x12CLIENT_HWD_BATTERY\x10\x04\x1a%\xd2\xf3\x18!\n" +
	"\abattery\x12\x16BatteryHwdReadResponse\x121\n" +
	"\x0eCLIENT_HWD_MIC\x10\x05\x1a\x1d\xd2\xf3\x18\x19\n" +
	"\x03mic\x12\x12MicHwdReadResponse\x12n\n" +
	"\x12CLIENT_HWD_DISPLAY\x10\x06\x1aV\xd2\xf3\x18R\n" +
	"\adisplay\x12\x16DisplayHwdReadResponse\x1a\x16DisplayHwdWriteRequest\"\x17DisplayHwdWriteResponse\x12Z\n" +
	"\x0eCLIENT_HWD_LED\x10\a\x1aF\xd2\xf3\x18B\n" +
	"\x03led\x12\x12LedHwdReadResponse\x1a\x12LedHwdWriteRequest\"\x13LedHwdWriteResponse\x12n\n" +
	"\x12CLIENT_HWD_SPEAKER\x10\b\x1aV\xd2\xf3\x18R\n" +
	"\aspeaker\x12\x16SpeakerHwdReadResponse\x1a\x16SpeakerHwdWriteRequest\"\x17SpeakerHwdWriteResponse:d\n" +
	"\n" +
	"client_hwd\x12!.google.protobuf.EnumValueOptions\x18\xba\x8e\x03 \x01(\v2 .gizclaw.rpc.v1.ClientHwdOptionsR\tclientHwdB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_mhs_v0_proto_rawDescOnce sync.Once
	file_payload_mhs_v0_proto_rawDescData []byte
)

func file_payload_mhs_v0_proto_rawDescGZIP() []byte {
	file_payload_mhs_v0_proto_rawDescOnce.Do(func() {
		file_payload_mhs_v0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_mhs_v0_proto_rawDesc), len(file_payload_mhs_v0_proto_rawDesc)))
	})
	return file_payload_mhs_v0_proto_rawDescData
}

var file_payload_mhs_v0_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payload_mhs_v0_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_payload_mhs_v0_proto_goTypes = []any{
	(ClientHwd)(0),                        // 0: gizclaw.rpc.v1.ClientHwd
	(*ClientHwdOptions)(nil),              // 1: gizclaw.rpc.v1.ClientHwdOptions
	(*ClientMhsV0ReadRequest)(nil),        // 2: gizclaw.rpc.v1.ClientMhsV0ReadRequest
	(*MhsV0WriteCapabilities)(nil),        // 3: gizclaw.rpc.v1.MhsV0WriteCapabilities
	(*ClientMhsV0ReadResponse)(nil),       // 4: gizclaw.rpc.v1.ClientMhsV0ReadResponse
	(*ClientMhsV0WriteRequest)(nil),       // 5: gizclaw.rpc.v1.ClientMhsV0WriteRequest
	(*ClientMhsV0WriteResponse)(nil),      // 6: gizclaw.rpc.v1.ClientMhsV0WriteResponse
	(*WifiHwdReadResponse)(nil),           // 7: gizclaw.rpc.v1.WifiHwdReadResponse
	(*BleHwdReadResponse)(nil),            // 8: gizclaw.rpc.v1.BleHwdReadResponse
	(*ModemHwdReadResponse)(nil),          // 9: gizclaw.rpc.v1.ModemHwdReadResponse
	(*BatteryHwdReadResponse)(nil),        // 10: gizclaw.rpc.v1.BatteryHwdReadResponse
	(*MicHwdReadResponse)(nil),            // 11: gizclaw.rpc.v1.MicHwdReadResponse
	(*DisplayHwdReadResponse)(nil),        // 12: gizclaw.rpc.v1.DisplayHwdReadResponse
	(*DisplayHwdWriteRequest)(nil),        // 13: gizclaw.rpc.v1.DisplayHwdWriteRequest
	(*DisplayHwdWriteResponse)(nil),       // 14: gizclaw.rpc.v1.DisplayHwdWriteResponse
	(*LedHwdReadResponse)(nil),            // 15: gizclaw.rpc.v1.LedHwdReadResponse
	(*LedHwdWriteRequest)(nil),            // 16: gizclaw.rpc.v1.LedHwdWriteRequest
	(*LedHwdWriteResponse)(nil),           // 17: gizclaw.rpc.v1.LedHwdWriteResponse
	(*SpeakerHwdReadResponse)(nil),        // 18: gizclaw.rpc.v1.SpeakerHwdReadResponse
	(*SpeakerHwdWriteRequest)(nil),        // 19: gizclaw.rpc.v1.SpeakerHwdWriteRequest
	(*SpeakerHwdWriteResponse)(nil),       // 20: gizclaw.rpc.v1.SpeakerHwdWriteResponse
	(*descriptorpb.EnumValueOptions)(nil), // 21: google.protobuf.EnumValueOptions
}
var file_payload_mhs_v0_proto_depIdxs = []int32{
	0,  // 0: gizclaw.rpc.v1.ClientMhsV0ReadRequest.hwd:type_name -> gizclaw.rpc.v1.ClientHwd
	3,  // 1: gizclaw.rpc.v1.ClientMhsV0ReadResponse.write_capabilities:type_name -> gizclaw.rpc.v1.MhsV0WriteCapabilities
	0,  // 2: gizclaw.rpc.v1.ClientMhsV0WriteRequest.hwd:type_name -> gizclaw.rpc.v1.ClientHwd
	12, // 3: gizclaw.rpc.v1.DisplayHwdWriteResponse.applied:type_name -> gizclaw.rpc.v1.DisplayHwdReadResponse
	15, // 4: gizclaw.rpc.v1.LedHwdWriteResponse.applied:type_name -> gizclaw.rpc.v1.LedHwdReadResponse
	18, // 5: gizclaw.rpc.v1.SpeakerHwdWriteResponse.applied:type_name -> gizclaw.rpc.v1.SpeakerHwdReadResponse
	21, // 6: gizclaw.rpc.v1.client_hwd:extendee -> google.protobuf.EnumValueOptions
	1,  // 7: gizclaw.rpc.v1.client_hwd:type_name -> gizclaw.rpc.v1.ClientHwdOptions
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	7,  // [7:8] is the sub-list for extension type_name
	6,  // [6:7] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_payload_mhs_v0_proto_init() }
func file_payload_mhs_v0_proto_init() {
	if File_payload_mhs_v0_proto != nil {
		return
	}
	file_payload_mhs_v0_proto_msgTypes[3].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[6].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[7].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[8].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[9].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[10].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[11].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[12].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[14].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[15].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[17].OneofWrappers = []any{}
	file_payload_mhs_v0_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_mhs_v0_proto_rawDesc), len(file_payload_mhs_v0_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_payload_mhs_v0_proto_goTypes,
		DependencyIndexes: file_payload_mhs_v0_proto_depIdxs,
		EnumInfos:         file_payload_mhs_v0_proto_enumTypes,
		MessageInfos:      file_payload_mhs_v0_proto_msgTypes,
		ExtensionInfos:    file_payload_mhs_v0_proto_extTypes,
	}.Build()
	File_payload_mhs_v0_proto = out.File
	file_payload_mhs_v0_proto_goTypes = nil
	file_payload_mhs_v0_proto_depIdxs = nil
}
