// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusCode is the canonical gRPC status code set (google.rpc.Code).
type StatusCode int32

const (
	StatusCode_STATUS_CODE_OK                  StatusCode = 0
	StatusCode_STATUS_CODE_CANCELLED           StatusCode = 1
	StatusCode_STATUS_CODE_UNKNOWN             StatusCode = 2
	StatusCode_STATUS_CODE_INVALID_ARGUMENT    StatusCode = 3
	StatusCode_STATUS_CODE_DEADLINE_EXCEEDED   StatusCode = 4
	StatusCode_STATUS_CODE_NOT_FOUND           StatusCode = 5
	StatusCode_STATUS_CODE_ALREADY_EXISTS      StatusCode = 6
	StatusCode_STATUS_CODE_PERMISSION_DENIED   StatusCode = 7
	StatusCode_STATUS_CODE_RESOURCE_EXHAUSTED  StatusCode = 8
	StatusCode_STATUS_CODE_FAILED_PRECONDITION StatusCode = 9
	StatusCode_STATUS_CODE_ABORTED             StatusCode = 10
	StatusCode_STATUS_CODE_OUT_OF_RANGE        StatusCode = 11
	StatusCode_STATUS_CODE_UNIMPLEMENTED       StatusCode = 12
	StatusCode_STATUS_CODE_INTERNAL            StatusCode = 13
	StatusCode_STATUS_CODE_UNAVAILABLE         StatusCode = 14
	StatusCode_STATUS_CODE_DATA_LOSS           StatusCode = 15
	StatusCode_STATUS_CODE_UNAUTHENTICATED     StatusCode = 16
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "STATUS_CODE_OK",
		1:  "STATUS_CODE_CANCELLED",
		2:  "STATUS_CODE_UNKNOWN",
		3:  "STATUS_CODE_INVALID_ARGUMENT",
		4:  "STATUS_CODE_DEADLINE_EXCEEDED",
		5:  "STATUS_CODE_NOT_FOUND",
		6:  "STATUS_CODE_ALREADY_EXISTS",
		7:  "STATUS_CODE_PERMISSION_DENIED",
		8:  "STATUS_CODE_RESOURCE_EXHAUSTED",
		9:  "STATUS_CODE_FAILED_PRECONDITION",
		10: "STATUS_CODE_ABORTED",
		11: "STATUS_CODE_OUT_OF_RANGE",
		12: "STATUS_CODE_UNIMPLEMENTED",
		13: "STATUS_CODE_INTERNAL",
		14: "STATUS_CODE_UNAVAILABLE",
		15: "STATUS_CODE_DATA_LOSS",
		16: "STATUS_CODE_UNAUTHENTICATED",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_OK":                  0,
		"STATUS_CODE_CANCELLED":           1,
		"STATUS_CODE_UNKNOWN":             2,
		"STATUS_CODE_INVALID_ARGUMENT":    3,
		"STATUS_CODE_DEADLINE_EXCEEDED":   4,
		"STATUS_CODE_NOT_FOUND":           5,
		"STATUS_CODE_ALREADY_EXISTS":      6,
		"STATUS_CODE_PERMISSION_DENIED":   7,
		"STATUS_CODE_RESOURCE_EXHAUSTED":  8,
		"STATUS_CODE_FAILED_PRECONDITION": 9,
		"STATUS_CODE_ABORTED":             10,
		"STATUS_CODE_OUT_OF_RANGE":        11,
		"STATUS_CODE_UNIMPLEMENTED":       12,
		"STATUS_CODE_INTERNAL":            13,
		"STATUS_CODE_UNAVAILABLE":         14,
		"STATUS_CODE_DATA_LOSS":           15,
		"STATUS_CODE_UNAUTHENTICATED":     16,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type RpcMethod int32

const (
	RpcMethod_RPC_METHOD_UNSPECIFIED                             RpcMethod = 0
	RpcMethod_RPC_METHOD_ALL_PING                                RpcMethod = 1
	RpcMethod_RPC_METHOD_ALL_SPEED_TEST_RUN                      RpcMethod = 2
	RpcMethod_RPC_METHOD_CLIENT_INFO_GET                         RpcMethod = 3
	RpcMethod_RPC_METHOD_CLIENT_IDENTIFIERS_GET                  RpcMethod = 4
	RpcMethod_RPC_METHOD_SERVER_INFO_GET                         RpcMethod = 5
	RpcMethod_RPC_METHOD_SERVER_INFO_PUT                         RpcMethod = 6
	RpcMethod_RPC_METHOD_SERVER_RUNTIME_GET                      RpcMethod = 7
	RpcMethod_RPC_METHOD_SERVER_STATUS_GET                       RpcMethod = 8
	RpcMethod_RPC_METHOD_SERVER_RUN_AGENT_GET                    RpcMethod = 9
	RpcMethod_RPC_METHOD_SERVER_RUN_AGENT_SET                    RpcMethod = 10
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_GET                RpcMethod = 11
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_SET                RpcMethod = 12
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_RELOAD             RpcMethod = 13
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY            RpcMethod = 14
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY_PLAY       RpcMethod = 15
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_MEMORY_STATS       RpcMethod = 16
	RpcMethod_RPC_METHOD_SERVER_RUN_WORKSPACE_RECALL             RpcMethod = 17
	RpcMethod_RPC_METHOD_SERVER_RUN_RELOAD                       RpcMethod = 18
	RpcMethod_RPC_METHOD_SERVER_RUN_STATUS                       RpcMethod = 19
	RpcMethod_RPC_METHOD_SERVER_RUN_STOP                         RpcMethod = 20
	RpcMethod_RPC_METHOD_SERVER_RUN_SAY                          RpcMethod = 21
	RpcMethod_RPC_METHOD_SERVER_FIRMWARE_GET                     RpcMethod = 22
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_LIST                   RpcMethod = 24
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_GET                    RpcMethod = 25
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_CREATE                 RpcMethod = 26
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_PUT                    RpcMethod = 27
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_INPUT_PUT              RpcMethod = 107
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_PARAMETERS_SET         RpcMethod = 110
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_DELETE                 RpcMethod = 28
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_HISTORY_LIST           RpcMethod = 29
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_HISTORY_GET            RpcMethod = 30
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_HISTORY_AUDIO_DOWNLOAD RpcMethod = 31
	RpcMethod_RPC_METHOD_SERVER_WORKFLOW_LIST                    RpcMethod = 32
	RpcMethod_RPC_METHOD_SERVER_WORKFLOW_GET                     RpcMethod = 33
	RpcMethod_RPC_METHOD_SERVER_MODEL_LIST                       RpcMethod = 34
	RpcMethod_RPC_METHOD_SERVER_MODEL_GET                        RpcMethod = 35
	RpcMethod_RPC_METHOD_SERVER_VOICE_LIST                       RpcMethod = 36
	RpcMethod_RPC_METHOD_SERVER_VOICE_GET                        RpcMethod = 37
	RpcMethod_RPC_METHOD_SERVER_CONTACT_LIST                     RpcMethod = 38
	RpcMethod_RPC_METHOD_SERVER_CONTACT_GET                      RpcMethod = 39
	RpcMethod_RPC_METHOD_SERVER_CONTACT_CREATE                   RpcMethod = 40
	RpcMethod_RPC_METHOD_SERVER_CONTACT_PUT                      RpcMethod = 41
	RpcMethod_RPC_METHOD_SERVER_CONTACT_DELETE                   RpcMethod = 42
	RpcMethod_RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_GET          RpcMethod = 43
	RpcMethod_RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CREATE       RpcMethod = 44
	RpcMethod_RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CLEAR        RpcMethod = 45
	RpcMethod_RPC_METHOD_SERVER_FRIEND_ADD                       RpcMethod = 46
	RpcMethod_RPC_METHOD_SERVER_FRIEND_LIST                      RpcMethod = 47
	RpcMethod_RPC_METHOD_SERVER_FRIEND_DELETE                    RpcMethod = 48
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_LIST                RpcMethod = 49
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_GET                 RpcMethod = 50
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_CREATE              RpcMethod = 51
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_PUT                 RpcMethod = 52
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_DELETE              RpcMethod = 53
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_GET    RpcMethod = 54
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CREATE RpcMethod = 55
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CLEAR  RpcMethod = 56
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_JOIN                RpcMethod = 57
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_LIST        RpcMethod = 58
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_ADD         RpcMethod = 59
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_PUT         RpcMethod = 60
	RpcMethod_RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_DELETE      RpcMethod = 61
	RpcMethod_RPC_METHOD_SERVER_BADGE_DEF_PIXA_DOWNLOAD          RpcMethod = 64
	RpcMethod_RPC_METHOD_SERVER_PET_LIST                         RpcMethod = 65
	RpcMethod_RPC_METHOD_SERVER_PET_GET                          RpcMethod = 66
	RpcMethod_RPC_METHOD_RUNTIME_ADOPT                           RpcMethod = 67
	RpcMethod_RPC_METHOD_SERVER_PET_PUT                          RpcMethod = 68
	RpcMethod_RPC_METHOD_SERVER_PET_DELETE                       RpcMethod = 69
	RpcMethod_RPC_METHOD_SERVER_PET_DRIVE                        RpcMethod = 70
	RpcMethod_RPC_METHOD_SERVER_POINTS_GET                       RpcMethod = 71
	RpcMethod_RPC_METHOD_SERVER_POINTS_TRANSACTIONS_LIST         RpcMethod = 72
	RpcMethod_RPC_METHOD_SERVER_POINTS_TRANSACTIONS_GET          RpcMethod = 73
	RpcMethod_RPC_METHOD_SERVER_BADGE_LIST                       RpcMethod = 74
	RpcMethod_RPC_METHOD_SERVER_BADGE_GET                        RpcMethod = 75
	RpcMethod_RPC_METHOD_SERVER_GAME_RESULT_LIST                 RpcMethod = 76
	RpcMethod_RPC_METHOD_SERVER_GAME_RESULT_GET                  RpcMethod = 77
	RpcMethod_RPC_METHOD_SERVER_REWARD_GRANT_LIST                RpcMethod = 78
	RpcMethod_RPC_METHOD_SERVER_REWARD_GRANT_GET                 RpcMethod = 79
	RpcMethod_RPC_METHOD_SERVER_TOOL_LIST                        RpcMethod = 80
	RpcMethod_RPC_METHOD_SERVER_TOOL_GET                         RpcMethod = 81
	RpcMethod_RPC_METHOD_CLIENT_TOOL_INVOKE                      RpcMethod = 82
	RpcMethod_RPC_METHOD_SERVER_PEER_LOOKUP                      RpcMethod = 83
	RpcMethod_RPC_METHOD_SERVER_PEER_ASSIGN                      RpcMethod = 84
	RpcMethod_RPC_METHOD_SERVER_ROUTE_RESOLVE                    RpcMethod = 85
	RpcMethod_RPC_METHOD_SERVER_PET_ACTIONS_GET                  RpcMethod = 86
	RpcMethod_RPC_METHOD_SERVER_PET_PIXA_DOWNLOAD                RpcMethod = 87
	RpcMethod_RPC_METHOD_SERVER_WORKSPACE_ICON_DOWNLOAD          RpcMethod = 88
	RpcMethod_RPC_METHOD_SERVER_FRIEND_INFO_GET                  RpcMethod = 89
	RpcMethod_RPC_METHOD_SERVER_REGISTER                         RpcMethod = 90
	RpcMethod_RPC_METHOD_SERVER_SPEECH_TRANSCRIBE                RpcMethod = 91
	RpcMethod_RPC_METHOD_SERVER_SPEECH_SYNTHESIZE                RpcMethod = 92
	RpcMethod_RPC_METHOD_SERVER_PEER_DELETE                      RpcMethod = 93
	RpcMethod_RPC_METHOD_SERVER_SPEECH_EXTRACT                   RpcMethod = 94
	RpcMethod_RPC_METHOD_SERVER_API_KEY_CREATE                   RpcMethod = 96
	RpcMethod_RPC_METHOD_SERVER_API_KEY_LIST                     RpcMethod = 97
	RpcMethod_RPC_METHOD_SERVER_API_KEY_REVOKE                   RpcMethod = 98
	RpcMethod_RPC_METHOD_SERVER_API_KEY_RESOLVE                  RpcMethod = 99
	RpcMethod_RPC_METHOD_CLIENT_DEVICE_STATUS_GET                RpcMethod = 100
	RpcMethod_RPC_METHOD_CLIENT_DEVICE_VOLUME_SET                RpcMethod = 101
	RpcMethod_RPC_METHOD_CLIENT_DEVICE_SOUND_PLAY                RpcMethod = 102
	RpcMethod_RPC_METHOD_CLIENT_DEVICE_REBOOT                    RpcMethod = 103
	RpcMethod_RPC_METHOD_CLIENT_WIFI_STATUS_GET                  RpcMethod = 104
	RpcMethod_RPC_METHOD_CLIENT_WIFI_SAVED_LIST                  RpcMethod = 105
	RpcMethod_RPC_METHOD_CLIENT_WIFI_SAVED_FORGET                RpcMethod = 106
	RpcMethod_RPC_METHOD_CLIENT_WIFI_SCAN                        RpcMethod = 108
	RpcMethod_RPC_METHOD_CLIENT_WIFI_CONNECT                     RpcMethod = 109
	RpcMethod_RPC_METHOD_CLIENT_FIRMWARE_UPDATE                  RpcMethod = 111
)

// Enum value maps for RpcMethod.
var (
	RpcMethod_name = map[int32]string{
		0:   "RPC_METHOD_UNSPECIFIED",
		1:   "RPC_METHOD_ALL_PING",
		2:   "RPC_METHOD_ALL_SPEED_TEST_RUN",
		3:   "RPC_METHOD_CLIENT_INFO_GET",
		4:   "RPC_METHOD_CLIENT_IDENTIFIERS_GET",
		5:   "RPC_METHOD_SERVER_INFO_GET",
		6:   "RPC_METHOD_SERVER_INFO_PUT",
		7:   "RPC_METHOD_SERVER_RUNTIME_GET",
		8:   "RPC_METHOD_SERVER_STATUS_GET",
		9:   "RPC_METHOD_SERVER_RUN_AGENT_GET",
		10:  "RPC_METHOD_SERVER_RUN_AGENT_SET",
		11:  "RPC_METHOD_SERVER_RUN_WORKSPACE_GET",
		12:  "RPC_METHOD_SERVER_RUN_WORKSPACE_SET",
		13:  "RPC_METHOD_SERVER_RUN_WORKSPACE_RELOAD",
		14:  "RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY",
		15:  "RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY_PLAY",
		16:  "RPC_METHOD_SERVER_RUN_WORKSPACE_MEMORY_STATS",
		17:  "RPC_METHOD_SERVER_RUN_WORKSPACE_RECALL",
		18:  "RPC_METHOD_SERVER_RUN_RELOAD",
		19:  "RPC_METHOD_SERVER_RUN_STATUS",
		20:  "RPC_METHOD_SERVER_RUN_STOP",
		21:  "RPC_METHOD_SERVER_RUN_SAY",
		22:  "RPC_METHOD_SERVER_FIRMWARE_GET",
		24:  "RPC_METHOD_SERVER_WORKSPACE_LIST",
		25:  "RPC_METHOD_SERVER_WORKSPACE_GET",
		26:  "RPC_METHOD_SERVER_WORKSPACE_CREATE",
		27:  "RPC_METHOD_SERVER_WORKSPACE_PUT",
		107: "RPC_METHOD_SERVER_WORKSPACE_INPUT_PUT",
		110: "RPC_METHOD_SERVER_WORKSPACE_PARAMETERS_SET",
		28:  "RPC_METHOD_SERVER_WORKSPACE_DELETE",
		29:  "RPC_METHOD_SERVER_WORKSPACE_HISTORY_LIST",
		30:  "RPC_METHOD_SERVER_WORKSPACE_HISTORY_GET",
		31:  "RPC_METHOD_SERVER_WORKSPACE_HISTORY_AUDIO_DOWNLOAD",
		32:  "RPC_METHOD_SERVER_WORKFLOW_LIST",
		33:  "RPC_METHOD_SERVER_WORKFLOW_GET",
		34:  "RPC_METHOD_SERVER_MODEL_LIST",
		35:  "RPC_METHOD_SERVER_MODEL_GET",
		36:  "RPC_METHOD_SERVER_VOICE_LIST",
		37:  "RPC_METHOD_SERVER_VOICE_GET",
		38:  "RPC_METHOD_SERVER_CONTACT_LIST",
		39:  "RPC_METHOD_SERVER_CONTACT_GET",
		40:  "RPC_METHOD_SERVER_CONTACT_CREATE",
		41:  "RPC_METHOD_SERVER_CONTACT_PUT",
		42:  "RPC_METHOD_SERVER_CONTACT_DELETE",
		43:  "RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_GET",
		44:  "RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CREATE",
		45:  "RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CLEAR",
		46:  "RPC_METHOD_SERVER_FRIEND_ADD",
		47:  "RPC_METHOD_SERVER_FRIEND_LIST",
		48:  "RPC_METHOD_SERVER_FRIEND_DELETE",
		49:  "RPC_METHOD_SERVER_FRIEND_GROUP_LIST",
		50:  "RPC_METHOD_SERVER_FRIEND_GROUP_GET",
		51:  "RPC_METHOD_SERVER_FRIEND_GROUP_CREATE",
		52:  "RPC_METHOD_SERVER_FRIEND_GROUP_PUT",
		53:  "RPC_METHOD_SERVER_FRIEND_GROUP_DELETE",
		54:  "RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_GET",
		55:  "RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CREATE",
		56:  "RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CLEAR",
		57:  "RPC_METHOD_SERVER_FRIEND_GROUP_JOIN",
		58:  "RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_LIST",
		59:  "RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_ADD",
		60:  "RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_PUT",
		61:  "RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_DELETE",
		64:  "RPC_METHOD_SERVER_BADGE_DEF_PIXA_DOWNLOAD",
		65:  "RPC_METHOD_SERVER_PET_LIST",
		66:  "RPC_METHOD_SERVER_PET_GET",
		67:  "RPC_METHOD_RUNTIME_ADOPT",
		68:  "RPC_METHOD_SERVER_PET_PUT",
		69:  "RPC_METHOD_SERVER_PET_DELETE",
		70:  "RPC_METHOD_SERVER_PET_DRIVE",
		71:  "RPC_METHOD_SERVER_POINTS_GET",
		72:  "RPC_METHOD_SERVER_POINTS_TRANSACTIONS_LIST",
		73:  "RPC_METHOD_SERVER_POINTS_TRANSACTIONS_GET",
		74:  "RPC_METHOD_SERVER_BADGE_LIST",
		75:  "RPC_METHOD_SERVER_BADGE_GET",
		76:  "RPC_METHOD_SERVER_GAME_RESULT_LIST",
		77:  "RPC_METHOD_SERVER_GAME_RESULT_GET",
		78:  "RPC_METHOD_SERVER_REWARD_GRANT_LIST",
		79:  "RPC_METHOD_SERVER_REWARD_GRANT_GET",
		80:  "RPC_METHOD_SERVER_TOOL_LIST",
		81:  "RPC_METHOD_SERVER_TOOL_GET",
		82:  "RPC_METHOD_CLIENT_TOOL_INVOKE",
		83:  "RPC_METHOD_SERVER_PEER_LOOKUP",
		84:  "RPC_METHOD_SERVER_PEER_ASSIGN",
		85:  "RPC_METHOD_SERVER_ROUTE_RESOLVE",
		86:  "RPC_METHOD_SERVER_PET_ACTIONS_GET",
		87:  "RPC_METHOD_SERVER_PET_PIXA_DOWNLOAD",
		88:  "RPC_METHOD_SERVER_WORKSPACE_ICON_DOWNLOAD",
		89:  "RPC_METHOD_SERVER_FRIEND_INFO_GET",
		90:  "RPC_METHOD_SERVER_REGISTER",
		91:  "RPC_METHOD_SERVER_SPEECH_TRANSCRIBE",
		92:  "RPC_METHOD_SERVER_SPEECH_SYNTHESIZE",
		93:  "RPC_METHOD_SERVER_PEER_DELETE",
		94:  "RPC_METHOD_SERVER_SPEECH_EXTRACT",
		96:  "RPC_METHOD_SERVER_API_KEY_CREATE",
		97:  "RPC_METHOD_SERVER_API_KEY_LIST",
		98:  "RPC_METHOD_SERVER_API_KEY_REVOKE",
		99:  "RPC_METHOD_SERVER_API_KEY_RESOLVE",
		100: "RPC_METHOD_CLIENT_DEVICE_STATUS_GET",
		101: "RPC_METHOD_CLIENT_DEVICE_VOLUME_SET",
		102: "RPC_METHOD_CLIENT_DEVICE_SOUND_PLAY",
		103: "RPC_METHOD_CLIENT_DEVICE_REBOOT",
		104: "RPC_METHOD_CLIENT_WIFI_STATUS_GET",
		105: "RPC_METHOD_CLIENT_WIFI_SAVED_LIST",
		106: "RPC_METHOD_CLIENT_WIFI_SAVED_FORGET",
		108: "RPC_METHOD_CLIENT_WIFI_SCAN",
		109: "RPC_METHOD_CLIENT_WIFI_CONNECT",
		111: "RPC_METHOD_CLIENT_FIRMWARE_UPDATE",
	}
	RpcMethod_value = map[string]int32{
		"RPC_METHOD_UNSPECIFIED":                             0,
		"RPC_METHOD_ALL_PING":                                1,
		"RPC_METHOD_ALL_SPEED_TEST_RUN":                      2,
		"RPC_METHOD_CLIENT_INFO_GET":                         3,
		"RPC_METHOD_CLIENT_IDENTIFIERS_GET":                  4,
		"RPC_METHOD_SERVER_INFO_GET":                         5,
		"RPC_METHOD_SERVER_INFO_PUT":                         6,
		"RPC_METHOD_SERVER_RUNTIME_GET":                      7,
		"RPC_METHOD_SERVER_STATUS_GET":                       8,
		"RPC_METHOD_SERVER_RUN_AGENT_GET":                    9,
		"RPC_METHOD_SERVER_RUN_AGENT_SET":                    10,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_GET":                11,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_SET":                12,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_RELOAD":             13,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY":            14,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY_PLAY":       15,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_MEMORY_STATS":       16,
		"RPC_METHOD_SERVER_RUN_WORKSPACE_RECALL":             17,
		"RPC_METHOD_SERVER_RUN_RELOAD":                       18,
		"RPC_METHOD_SERVER_RUN_STATUS":                       19,
		"RPC_METHOD_SERVER_RUN_STOP":                         20,
		"RPC_METHOD_SERVER_RUN_SAY":                          21,
		"RPC_METHOD_SERVER_FIRMWARE_GET":                     22,
		"RPC_METHOD_SERVER_WORKSPACE_LIST":                   24,
		"RPC_METHOD_SERVER_WORKSPACE_GET":                    25,
		"RPC_METHOD_SERVER_WORKSPACE_CREATE":                 26,
		"RPC_METHOD_SERVER_WORKSPACE_PUT":                    27,
		"RPC_METHOD_SERVER_WORKSPACE_INPUT_PUT":              107,
		"RPC_METHOD_SERVER_WORKSPACE_PARAMETERS_SET":         110,
		"RPC_METHOD_SERVER_WORKSPACE_DELETE":                 28,
		"RPC_METHOD_SERVER_WORKSPACE_HISTORY_LIST":           29,
		"RPC_METHOD_SERVER_WORKSPACE_HISTORY_GET":            30,
		"RPC_METHOD_SERVER_WORKSPACE_HISTORY_AUDIO_DOWNLOAD": 31,
		"RPC_METHOD_SERVER_WORKFLOW_LIST":                    32,
		"RPC_METHOD_SERVER_WORKFLOW_GET":                     33,
		"RPC_METHOD_SERVER_MODEL_LIST":                       34,
		"RPC_METHOD_SERVER_MODEL_GET":                        35,
		"RPC_METHOD_SERVER_VOICE_LIST":                       36,
		"RPC_METHOD_SERVER_VOICE_GET":                        37,
		"RPC_METHOD_SERVER_CONTACT_LIST":                     38,
		"RPC_METHOD_SERVER_CONTACT_GET":                      39,
		"RPC_METHOD_SERVER_CONTACT_CREATE":                   40,
		"RPC_METHOD_SERVER_CONTACT_PUT":                      41,
		"RPC_METHOD_SERVER_CONTACT_DELETE":                   42,
		"RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_GET":          43,
		"RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CREATE":       44,
		"RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CLEAR":        45,
		"RPC_METHOD_SERVER_FRIEND_ADD":                       46,
		"RPC_METHOD_SERVER_FRIEND_LIST":                      47,
		"RPC_METHOD_SERVER_FRIEND_DELETE":                    48,
		"RPC_METHOD_SERVER_FRIEND_GROUP_LIST":                49,
		"RPC_METHOD_SERVER_FRIEND_GROUP_GET":                 50,
		"RPC_METHOD_SERVER_FRIEND_GROUP_CREATE":              51,
		"RPC_METHOD_SERVER_FRIEND_GROUP_PUT":                 52,
		"RPC_METHOD_SERVER_FRIEND_GROUP_DELETE":              53,
		"RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_GET":    54,
		"RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CREATE": 55,
		"RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CLEAR":  56,
		"RPC_METHOD_SERVER_FRIEND_GROUP_JOIN":                57,
		"RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_LIST":        58,
		"RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_ADD":         59,
		"RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_PUT":         60,
		"RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_DELETE":      61,
		"RPC_METHOD_SERVER_BADGE_DEF_PIXA_DOWNLOAD":          64,
		"RPC_METHOD_SERVER_PET_LIST":                         65,
		"RPC_METHOD_SERVER_PET_GET":                          66,
		"RPC_METHOD_RUNTIME_ADOPT":                           67,
		"RPC_METHOD_SERVER_PET_PUT":                          68,
		"RPC_METHOD_SERVER_PET_DELETE":                       69,
		"RPC_METHOD_SERVER_PET_DRIVE":                        70,
		"RPC_METHOD_SERVER_POINTS_GET":                       71,
		"RPC_METHOD_SERVER_POINTS_TRANSACTIONS_LIST":         72,
		"RPC_METHOD_SERVER_POINTS_TRANSACTIONS_GET":          73,
		"RPC_METHOD_SERVER_BADGE_LIST":                       74,
		"RPC_METHOD_SERVER_BADGE_GET":                        75,
		"RPC_METHOD_SERVER_GAME_RESULT_LIST":                 76,
		"RPC_METHOD_SERVER_GAME_RESULT_GET":                  77,
		"RPC_METHOD_SERVER_REWARD_GRANT_LIST":                78,
		"RPC_METHOD_SERVER_REWARD_GRANT_GET":                 79,
		"RPC_METHOD_SERVER_TOOL_LIST":                        80,
		"RPC_METHOD_SERVER_TOOL_GET":                         81,
		"RPC_METHOD_CLIENT_TOOL_INVOKE":                      82,
		"RPC_METHOD_SERVER_PEER_LOOKUP":                      83,
		"RPC_METHOD_SERVER_PEER_ASSIGN":                      84,
		"RPC_METHOD_SERVER_ROUTE_RESOLVE":                    85,
		"RPC_METHOD_SERVER_PET_ACTIONS_GET":                  86,
		"RPC_METHOD_SERVER_PET_PIXA_DOWNLOAD":                87,
		"RPC_METHOD_SERVER_WORKSPACE_ICON_DOWNLOAD":          88,
		"RPC_METHOD_SERVER_FRIEND_INFO_GET":                  89,
		"RPC_METHOD_SERVER_REGISTER":                         90,
		"RPC_METHOD_SERVER_SPEECH_TRANSCRIBE":                91,
		"RPC_METHOD_SERVER_SPEECH_SYNTHESIZE":                92,
		"RPC_METHOD_SERVER_PEER_DELETE":                      93,
		"RPC_METHOD_SERVER_SPEECH_EXTRACT":                   94,
		"RPC_METHOD_SERVER_API_KEY_CREATE":                   96,
		"RPC_METHOD_SERVER_API_KEY_LIST":                     97,
		"RPC_METHOD_SERVER_API_KEY_REVOKE":                   98,
		"RPC_METHOD_SERVER_API_KEY_RESOLVE":                  99,
		"RPC_METHOD_CLIENT_DEVICE_STATUS_GET":                100,
		"RPC_METHOD_CLIENT_DEVICE_VOLUME_SET":                101,
		"RPC_METHOD_CLIENT_DEVICE_SOUND_PLAY":                102,
		"RPC_METHOD_CLIENT_DEVICE_REBOOT":                    103,
		"RPC_METHOD_CLIENT_WIFI_STATUS_GET":                  104,
		"RPC_METHOD_CLIENT_WIFI_SAVED_LIST":                  105,
		"RPC_METHOD_CLIENT_WIFI_SAVED_FORGET":                106,
		"RPC_METHOD_CLIENT_WIFI_SCAN":                        108,
		"RPC_METHOD_CLIENT_WIFI_CONNECT":                     109,
		"RPC_METHOD_CLIENT_FIRMWARE_UPDATE":                  111,
	}
)

func (x RpcMethod) Enum() *RpcMethod {
	p := new(RpcMethod)
	*p = x
	return p
}

func (x RpcMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[1].Descriptor()
}

func (RpcMethod) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[1]
}

func (x RpcMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcMethod.Descriptor instead.
func (RpcMethod) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

type RpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RpcResponse_Payload
	//	*RpcResponse_Status
	Body          isRpcResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcResponse) GetBody() isRpcResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RpcResponse) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*RpcResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *RpcResponse) GetStatus() *RpcStatus {
	if x != nil {
		if x, ok := x.Body.(*RpcResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isRpcResponse_Body interface {
	isRpcResponse_Body()
}

type RpcResponse_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

type RpcResponse_Status struct {
	Status *RpcStatus `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*RpcResponse_Payload) isRpcResponse_Body() {}

func (*RpcResponse_Status) isRpcResponse_Body() {}

type RpcStreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*RpcStreamFrame_Payload
	//	*RpcStreamFrame_Status
	//	*RpcStreamFrame_End
	Body          isRpcStreamFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcStreamFrame) Reset() {
	*x = RpcStreamFrame{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcStreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStreamFrame) ProtoMessage() {}

func (x *RpcStreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStreamFrame.ProtoReflect.Descriptor instead.
func (*RpcStreamFrame) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcStreamFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcStreamFrame) GetBody() isRpcStreamFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RpcStreamFrame) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*RpcStreamFrame_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *RpcStreamFrame) GetStatus() *RpcStatus {
	if x != nil {
		if x, ok := x.Body.(*RpcStreamFrame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *RpcStreamFrame) GetEnd() *RpcStreamEnd {
	if x != nil {
		if x, ok := x.Body.(*RpcStreamFrame_End); ok {
			return x.End
		}
	}
	return nil
}

type isRpcStreamFrame_Body interface {
	isRpcStreamFrame_Body()
}

type RpcStreamFrame_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

type RpcStreamFrame_Status struct {
	Status *RpcStatus `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type RpcStreamFrame_End struct {
	End *RpcStreamEnd `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

func (*RpcStreamFrame_Payload) isRpcStreamFrame_Body() {}

func (*RpcStreamFrame_Status) isRpcStreamFrame_Body() {}

func (*RpcStreamFrame_End) isRpcStreamFrame_Body() {}

// RpcStatus is the terminal status of one RPC. It follows google.rpc.Status
// with one deviation: details is a typed ErrorInfo rather than
// repeated google.protobuf.Any, because nanopb cannot resolve type URLs at
// runtime and the C SDK allocates nothing.
type RpcStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=gizclaw.rpc.v1.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Info          *ErrorInfo             `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcStatus) Reset() {
	*x = RpcStatus{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStatus) ProtoMessage() {}

func (x *RpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStatus.ProtoReflect.Descriptor instead.
func (*RpcStatus) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcStatus) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_STATUS_CODE_OK
}

func (x *RpcStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcStatus) GetInfo() *ErrorInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// ErrorInfo names the specific failure behind a StatusCode. code is the class
// a client branches on; reason is the reason a human or a UI reads. It follows
// google.rpc.ErrorInfo without the metadata map, which no caller needs and
// which nanopb can only express as a bounded repeated entry message.
type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type RpcStreamEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcStreamEnd) Reset() {
	*x = RpcStreamEnd{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcStreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStreamEnd) ProtoMessage() {}

func (x *RpcStreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStreamEnd.ProtoReflect.Descriptor instead.
func (*RpcStreamEnd) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

type RpcMethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcMethodOptions) Reset() {
	*x = RpcMethodOptions{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodOptions) ProtoMessage() {}

func (x *RpcMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMethodOptions.ProtoReflect.Descriptor instead.
func (*RpcMethodOptions) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RpcMethodOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RpcMethodOptions) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *RpcMethodOptions) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        RpcMethod              `protobuf:"varint,2,opt,name=method,proto3,enum=gizclaw.rpc.v1.RpcMethod" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RpcRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcRequest) GetMethod() RpcMethod {
	if x != nil {
		return x.Method
	}
	return RpcMethod_RPC_METHOD_UNSPECIFIED
}

func (x *RpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var file_rpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*RpcMethodOptions)(nil),
		Field:         51000,
		Name:          "gizclaw.rpc.v1.rpc_method",
		Tag:           "bytes,51000,opt,name=rpc_method",
		Filename:      "rpc.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional gizclaw.rpc.v1.RpcMethodOptions rpc_method = 51000;
	E_RpcMethod = &file_rpc_proto_extTypes[0]
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x0egizclaw.rpc.v1\x1a google/protobuf/descriptor.proto\"v\n" +
	"\vRpcResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x19.gizclaw.rpc.v1.RpcStatusH\x00R\x06statusB\x06\n" +
	"\x04body\"\xab\x01\n" +
	"\x0eRpcStreamFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x19.gizclaw.rpc.v1.RpcStatusH\x00R\x06status\x120\n" +
	"\x03end\x18\x04 \x01(\v2\x1c.gizclaw.rpc.v1.RpcStreamEndH\x00R\x03endB\x06\n" +
	"\x04body\"\x84\x01\n" +
	"\tRpcStatus\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04info\x18\x03 \x01(\v2\x19.gizclaw.rpc.v1.ErrorInfoR\x04info\";\n" +
	"\tErrorInfo\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\x0e\n" +
	"\fRpcStreamEnd\"\\\n" +
	"\x10RpcMethodOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"z\n" +
	"\n" +
	"RpcRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06method\x18\x02 \x01(\x0e2\x19.gizclaw.rpc.v1.RpcMethodR\x06method\x12\x1d\n" +
	"\apayload\x18\x03 \x01(\fH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload*\x89\x04\n" +
	"\n" +
	"StatusCode\x12\x12\n" +
	"\x0eSTATUS_CODE_OK\x10\x00\x12\x19\n" +
	"\x15STATUS_CODE_CANCELLED\x10\x01\x12\x17\n" +
	"\x13STATUS_CODE_UNKNOWN\x10\x02\x12 \n" +
	"\x1cSTATUS_CODE_INVALID_ARGUMENT\x10\x03\x12!\n" +
	"\x1dSTATUS_CODE_DEADLINE_EXCEEDED\x10\x04\x12\x19\n" +
	"\x15STATUS_CODE_NOT_FOUND\x10\x05\x12\x1e\n" +
	"\x1aSTATUS_CODE_ALREADY_EXISTS\x10\x06\x12!\n" +
	"\x1dSTATUS_CODE_PERMISSION_DENIED\x10\a\x12\"\n" +
	"\x1eSTATUS_CODE_RESOURCE_EXHAUSTED\x10\b\x12#\n" +
	"\x1fSTATUS_CODE_FAILED_PRECONDITION\x10\t\x12\x17\n" +
	"\x13STATUS_CODE_ABORTED\x10\n" +
	"\x12\x1c\n" +
	"\x18STATUS_CODE_OUT_OF_RANGE\x10\v\x12\x1d\n" +
	"\x19STATUS_CODE_UNIMPLEMENTED\x10\f\x12\x18\n" +
	"\x14STATUS_CODE_INTERNAL\x10\r\x12\x1b\n" +
	"\x17STATUS_CODE_UNAVAILABLE\x10\x0e\x12\x19\n" +
	"\x15STATUS_CODE_DATA_LOSS\x10\x0f\x12\x1f\n" +
	"\x1bSTATUS_CODE_UNAUTHENTICATED\x10\x10*\x89f\n" +
	"\tRpcMethod\x12\x1a\n" +
	"\x16RPC_METHOD_UNSPECIFIED\x10\x00\x12B\n" +
	"\x13RPC_METHOD_ALL_PING\x10\x01\x1a)\xc2\xf3\x18%\n" +
	"\ball.ping\x12\vPingRequest\x1a\fPingResponse\x12`\n" +
	"\x1dRPC_METHOD_ALL_SPEED_TEST_RUN\x10\x02\x1a=\xc2\xf3\x189\n" +
	"\x12all.speed_test.run\x12\x10SpeedTestRequest\x1a\x11SpeedTestResponse\x12b\n" +
	"\x1aRPC_METHOD_CLIENT_INFO_GET\x10\x03\x1aB\xc2\xf3\x18>\n" +
	"\x0fclient.info.get\x12\x14ClientGetInfoRequest\x1a\x15ClientGetInfoResponse\x12~\n" +
	"!RPC_METHOD_CLIENT_IDENTIFIERS_GET\x10\x04\x1aW\xc2\xf3\x18S\n" +
	"\x16client.identifiers.get\x12\x1bClientGetIdentifiersRequest\x1a\x1cClientGetIdentifiersResponse\x12b\n" +
	"\x1aRPC_METHOD_SERVER_INFO_GET\x10\x05\x1aB\xc2\xf3\x18>\n" +
	"\x0fserver.info.get\x12\x14ServerGetInfoRequest\x1a\x15ServerGetInfoResponse\x12b\n" +
	"\x1aRPC_METHOD_SERVER_INFO_PUT\x10\x06\x1aB\xc2\xf3\x18>\n" +
	"\x0fserver.info.put\x12\x14ServerPutInfoRequest\x1a\x15ServerPutInfoResponse\x12n\n" +
	"\x1dRPC_METHOD_SERVER_RUNTIME_GET\x10\a\x1aK\xc2\xf3\x18G\n" +
	"\x12server.runtime.get\x12\x17ServerGetRuntimeRequest\x1a\x18ServerGetRuntimeResponse\x12j\n" +
	"\x1cRPC_METHOD_SERVER_STATUS_GET\x10\b\x1aH\xc2\xf3\x18D\n" +
	"\x11server.status.get\x12\x16ServerGetStatusRequest\x1a\x17ServerGetStatusResponse\x12t\n" +
	"\x1fRPC_METHOD_SERVER_RUN_AGENT_GET\x10\t\x1aO\xc2\xf3\x18K\n" +
	"\x14server.run.agent.get\x12\x18ServerGetRunAgentRequest\x1a\x19ServerGetRunAgentResponse\x12t\n" +
	"\x1fRPC_METHOD_SERVER_RUN_AGENT_SET\x10\n" +
	"\x1aO\xc2\xf3\x18K\n" +
	"\x14server.run.agent.set\x12\x18ServerSetRunAgentRequest\x1a\x19ServerSetRunAgentResponse\x12\x84\x01\n" +
	"#RPC_METHOD_SERVER_RUN_WORKSPACE_GET\x10\v\x1a[\xc2\xf3\x18W\n" +
	"\x18server.run.workspace.get\x12\x1cServerGetRunWorkspaceRequest\x1a\x1dServerGetRunWorkspaceResponse\x12\x84\x01\n" +
	"#RPC_METHOD_SERVER_RUN_WORKSPACE_SET\x10\f\x1a[\xc2\xf3\x18W\n" +
	"\x18server.run.workspace.set\x12\x1cServerSetRunWorkspaceRequest\x1a\x1dServerSetRunWorkspaceResponse\x12\x90\x01\n" +
	"&RPC_METHOD_SERVER_RUN_WORKSPACE_RELOAD\x10\r\x1ad\xc2\xf3\x18`\n" +
	"\x1bserver.run.workspace.reload\x12\x1fServerReloadRunWorkspaceRequest\x1a ServerReloadRunWorkspaceResponse\x12\x9c\x01\n" +
	"'RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY\x10\x0e\x1ao\xc2\xf3\x18k\n" +
	"\x1cserver.run.workspace.history\x12$ServerListRunWorkspaceHistoryRequest\x1a%ServerListRunWorkspaceHistoryResponse\x12\xa6\x01\n" +
	",RPC_METHOD_SERVER_RUN_WORKSPACE_HISTORY_PLAY\x10\x0f\x1at\xc2\xf3\x18p\n" +
	"!server.run.workspace.history.play\x12$ServerPlayRunWorkspaceHistoryRequest\x1a%ServerPlayRunWorkspaceHistoryResponse\x12\xac\x01\n" +
	",RPC_METHOD_SERVER_RUN_WORKSPACE_MEMORY_STATS\x10\x10\x1az\xc2\xf3\x18v\n" +
	"!server.run.workspace.memory.stats\x12'ServerGetRunWorkspaceMemoryStatsRequest\x1a(ServerGetRunWorkspaceMemoryStatsResponse\x12\x90\x01\n" +
	"&RPC_METHOD_SERVER_RUN_WORKSPACE_RECALL\x10\x11\x1ad\xc2\xf3\x18`\n" +
	"\x1bserver.run.workspace.recall\x12\x1fServerRunWorkspaceRecallRequest\x1a ServerRunWorkspaceRecallResponse\x12j\n" +
	"\x1cRPC_METHOD_SERVER_RUN_RELOAD\x10\x12\x1aH\xc2\xf3\x18D\n" +
	"\x11server.run.reload\x12\x16ServerReloadRunRequest\x1a\x17ServerReloadRunResponse\x12p\n" +
	"\x1cRPC_METHOD_SERVER_RUN_STATUS\x10\x13\x1aN\xc2\xf3\x18J\n" +
	"\x11server.run.status\x12\x19ServerGetRunStatusRequest\x1a\x1aServerGetRunStatusResponse\x12b\n" +
	"\x1aRPC_METHOD_SERVER_RUN_STOP\x10\x14\x1aB\xc2\xf3\x18>\n" +
	"\x0fserver.run.stop\x12\x14ServerStopRunRequest\x1a\x15ServerStopRunResponse\x12^\n" +
	"\x19RPC_METHOD_SERVER_RUN_SAY\x10\x15\x1a?\xc2\xf3\x18;\n" +
	"\x0eserver.run.say\x12\x13ServerRunSayRequest\x1a\x14ServerRunSayResponse\x12f\n" +
	"\x1eRPC_METHOD_SERVER_FIRMWARE_GET\x10\x16\x1aB\xc2\xf3\x18>\n" +
	"\x13server.firmware.get\x12\x12FirmwareGetRequest\x1a\x13FirmwareGetResponse\x12n\n" +
	" RPC_METHOD_SERVER_WORKSPACE_LIST\x10\x18\x1aH\xc2\xf3\x18D\n" +
	"\x15server.workspace.list\x12\x14WorkspaceListRequest\x1a\x15WorkspaceListResponse\x12j\n" +
	"\x1fRPC_METHOD_SERVER_WORKSPACE_GET\x10\x19\x1aE\xc2\xf3\x18A\n" +
	"\x14server.workspace.get\x12\x13WorkspaceGetRequest\x1a\x14WorkspaceGetResponse\x12v\n" +
	"\"RPC_METHOD_SERVER_WORKSPACE_CREATE\x10\x1a\x1aN\xc2\xf3\x18J\n" +
	"\x17server.workspace.create\x12\x16WorkspaceCreateRequest\x1a\x17WorkspaceCreateResponse\x12j\n" +
	"\x1fRPC_METHOD_SERVER_WORKSPACE_PUT\x10\x1b\x1aE\xc2\xf3\x18A\n" +
	"\x14server.workspace.put\x12\x13WorkspacePutRequest\x1a\x14WorkspacePutResponse\x12\x80\x01\n" +
	"%RPC_METHOD_SERVER_WORKSPACE_INPUT_PUT\x10k\x1aU\xc2\xf3\x18Q\n" +
	"\x1aserver.workspace.input.put\x12\x18WorkspaceInputPutRequest\x1a\x19WorkspaceInputPutResponse\x12\x94\x01\n" +
	"*RPC_METHOD_SERVER_WORKSPACE_PARAMETERS_SET\x10n\x1ad\xc2\xf3\x18`\n" +
	"\x1fserver.workspace.parameters.set\x12\x1dWorkspaceParametersSetRequest\x1a\x1eWorkspaceParametersSetResponse\x12v\n" +
	"\"RPC_METHOD_SERVER_WORKSPACE_DELETE\x10\x1c\x1aN\xc2\xf3\x18J\n" +
	"\x17server.workspace.delete\x12\x16WorkspaceDeleteRequest\x1a\x17WorkspaceDeleteResponse\x12\x8c\x01\n" +
	"(RPC_METHOD_SERVER_WORKSPACE_HISTORY_LIST\x10\x1d\x1a^\xc2\xf3\x18Z\n" +
	"\x1dserver.workspace.history.list\x12\x1bWorkspaceHistoryListRequest\x1a\x1cWorkspaceHistoryListResponse\x12\x88\x01\n" +
	"'RPC_METHOD_SERVER_WORKSPACE_HISTORY_GET\x10\x1e\x1a[\xc2\xf3\x18W\n" +
	"\x1cserver.workspace.history.get\x12\x1aWorkspaceHistoryGetRequest\x1a\x1bWorkspaceHistoryGetResponse\x12\xb2\x01\n" +
	"2RPC_METHOD_SERVER_WORKSPACE_HISTORY_AUDIO_DOWNLOAD\x10\x1f\x1az\xc2\xf3\x18v\n" +
	"'server.workspace.history.audio.download\x12$WorkspaceHistoryAudioDownloadRequest\x1a%WorkspaceHistoryAudioDownloadResponse\x12j\n" +
	"\x1fRPC_METHOD_SERVER_WORKFLOW_LIST\x10 \x1aE\xc2\xf3\x18A\n" +
	"\x14server.workflow.list\x12\x13WorkflowListRequest\x1a\x14WorkflowListResponse\x12f\n" +
	"\x1eRPC_METHOD_SERVER_WORKFLOW_GET\x10!\x1aB\xc2\xf3\x18>\n" +
	"\x13server.workflow.get\x12\x12WorkflowGetRequest\x1a\x13WorkflowGetResponse\x12^\n" +
	"\x1cRPC_METHOD_SERVER_MODEL_LIST\x10\"\x1a<\xc2\xf3\x188\n" +
	"\x11server.model.list\x12\x10ModelListRequest\x1a\x11ModelListResponse\x12Z\n" +
	"\x1bRPC_METHOD_SERVER_MODEL_GET\x10#\x1a9\xc2\xf3\x185\n" +
	"\x10server.model.get\x12\x0fModelGetRequest\x1a\x10ModelGetResponse\x12^\n" +
	"\x1cRPC_METHOD_SERVER_VOICE_LIST\x10$\x1a<\xc2\xf3\x188\n" +
	"\x11server.voice.list\x12\x10VoiceListRequest\x1a\x11VoiceListResponse\x12Z\n" +
	"\x1bRPC_METHOD_SERVER_VOICE_GET\x10%\x1a9\xc2\xf3\x185\n" +
	"\x10server.voice.get\x12\x0fVoiceGetRequest\x1a\x10VoiceGetResponse\x12f\n" +
	"\x1eRPC_METHOD_SERVER_CONTACT_LIST\x10&\x1aB\xc2\xf3\x18>\n" +
	"\x13server.contact.list\x12\x12ContactListRequest\x1a\x13ContactListResponse\x12b\n" +
	"\x1dRPC_METHOD_SERVER_CONTACT_GET\x10'\x1a?\xc2\xf3\x18;\n" +
	"\x12server.contact.get\x12\x11ContactGetRequest\x1a\x12ContactGetResponse\x12n\n" +
	" RPC_METHOD_SERVER_CONTACT_CREATE\x10(\x1aH\xc2\xf3\x18D\n" +
	"\x15server.contact.create\x12\x14ContactCreateRequest\x1a\x15ContactCreateResponse\x12b\n" +
	"\x1dRPC_METHOD_SERVER_CONTACT_PUT\x10)\x1a?\xc2\xf3\x18;\n" +
	"\x12server.contact.put\x12\x11ContactPutRequest\x1a\x12ContactPutResponse\x12n\n" +
	" RPC_METHOD_SERVER_CONTACT_DELETE\x10*\x1aH\xc2\xf3\x18D\n" +
	"\x15server.contact.delete\x12\x14ContactDeleteRequest\x1a\x15ContactDeleteResponse\x12\x8e\x01\n" +
	")RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_GET\x10+\x1a_\xc2\xf3\x18[\n" +
	"\x1eserver.friend.invite_token.get\x12\x1bFriendInviteTokenGetRequest\x1a\x1cFriendInviteTokenGetResponse\x12\x9a\x01\n" +
	",RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CREATE\x10,\x1ah\xc2\xf3\x18d\n" +
	"!server.friend.invite_token.create\x12\x1eFriendInviteTokenCreateRequest\x1a\x1fFriendInviteTokenCreateResponse\x12\x96\x01\n" +
	"+RPC_METHOD_SERVER_FRIEND_INVITE_TOKEN_CLEAR\x10-\x1ae\xc2\xf3\x18a\n" +
	" server.friend.invite_token.clear\x12\x1dFriendInviteTokenClearRequest\x1a\x1eFriendInviteTokenClearResponse\x12^\n" +
	"\x1cRPC_METHOD_SERVER_FRIEND_ADD\x10.\x1a<\xc2\xf3\x188\n" +
	"\x11server.friend.add\x12\x10FriendAddRequest\x1a\x11FriendAddResponse\x12b\n" +
	"\x1dRPC_METHOD_SERVER_FRIEND_LIST\x10/\x1a?\xc2\xf3\x18;\n" +
	"\x12server.friend.list\x12\x11FriendListRequest\x1a\x12FriendListResponse\x12j\n" +
	"\x1fRPC_METHOD_SERVER_FRIEND_DELETE\x100\x1aE\xc2\xf3\x18A\n" +
	"\x14server.friend.delete\x12\x13FriendDeleteRequest\x1a\x14FriendDeleteResponse\x12x\n" +
	"#RPC_METHOD_SERVER_FRIEND_GROUP_LIST\x101\x1aO\xc2\xf3\x18K\n" +
	"\x18server.friend_group.list\x12\x16FriendGroupListRequest\x1a\x17FriendGroupListResponse\x12t\n" +
	"\"RPC_METHOD_SERVER_FRIEND_GROUP_GET\x102\x1aL\xc2\xf3\x18H\n" +
	"\x17server.friend_group.get\x12\x15FriendGroupGetRequest\x1a\x16FriendGroupGetResponse\x12\x80\x01\n" +
	"%RPC_METHOD_SERVER_FRIEND_GROUP_CREATE\x103\x1aU\xc2\xf3\x18Q\n" +
	"\x1aserver.friend_group.create\x12\x18FriendGroupCreateRequest\x1a\x19FriendGroupCreateResponse\x12t\n" +
	"\"RPC_METHOD_SERVER_FRIEND_GROUP_PUT\x104\x1aL\xc2\xf3\x18H\n" +
	"\x17server.friend_group.put\x12\x15FriendGroupPutRequest\x1a\x16FriendGroupPutResponse\x12\x80\x01\n" +
	"%RPC_METHOD_SERVER_FRIEND_GROUP_DELETE\x105\x1aU\xc2\xf3\x18Q\n" +
	"\x1aserver.friend_group.delete\x12\x18FriendGroupDeleteRequest\x1a\x19FriendGroupDeleteResponse\x12\xa4\x01\n" +
	"/RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_GET\x106\x1ao\xc2\xf3\x18k\n" +
	"$server.friend_group.invite_token.get\x12 FriendGroupInviteTokenGetRequest\x1a!FriendGroupInviteTokenGetResponse\x12\xb0\x01\n" +
	"2RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CREATE\x107\x1ax\xc2\xf3\x18t\n" +
	"'server.friend_group.invite_token.create\x12#FriendGroupInviteTokenCreateRequest\x1a$FriendGroupInviteTokenCreateResponse\x12\xac\x01\n" +
	"1RPC_METHOD_SERVER_FRIEND_GROUP_INVITE_TOKEN_CLEAR\x108\x1au\xc2\xf3\x18q\n" +
	"&server.friend_group.invite_token.clear\x12\"FriendGroupInviteTokenClearRequest\x1a#FriendGroupInviteTokenClearResponse\x12x\n" +
	"#RPC_METHOD_SERVER_FRIEND_GROUP_JOIN\x109\x1aO\xc2\xf3\x18K\n" +
	"\x18server.friend_group.join\x12\x16FriendGroupJoinRequest\x1a\x17FriendGroupJoinResponse\x12\x94\x01\n" +
	"+RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_LIST\x10:\x1ac\xc2\xf3\x18_\n" +
	" server.friend_group.members.list\x12\x1cFriendGroupMemberListRequest\x1a\x1dFriendGroupMemberListResponse\x12\x90\x01\n" +
	"*RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_ADD\x10;\x1a`\xc2\xf3\x18\\\n" +
	"\x1fserver.friend_group.members.add\x12\x1bFriendGroupMemberAddRequest\x1a\x1cFriendGroupMemberAddResponse\x12\x90\x01\n" +
	"*RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_PUT\x10<\x1a`\xc2\xf3\x18\\\n" +
	"\x1fserver.friend_group.members.put\x12\x1bFriendGroupMemberPutRequest\x1a\x1cFriendGroupMemberPutResponse\x12\x9c\x01\n" +
	"-RPC_METHOD_SERVER_FRIEND_GROUP_MEMBERS_DELETE\x10=\x1ai\xc2\xf3\x18e\n" +
	"\"server.friend_group.members.delete\x12\x1eFriendGroupMemberDeleteRequest\x1a\x1fFriendGroupMemberDeleteResponse\x12\x8e\x01\n" +
	")RPC_METHOD_SERVER_BADGE_DEF_PIXA_DOWNLOAD\x10@\x1a_\xc2\xf3\x18[\n" +
	"\x1eserver.badge_def.pixa.download\x12\x1bBadgeDefPixaDownloadRequest\x1a\x1cBadgeDefPixaDownloadResponse\x12b\n" +
	"\x1aRPC_METHOD_SERVER_PET_LIST\x10A\x1aB\xc2\xf3\x18>\n" +
	"\x0fserver.pet.list\x12\x14ServerPetListRequest\x1a\x15ServerPetListResponse\x12^\n" +
	"\x19RPC_METHOD_SERVER_PET_GET\x10B\x1a?\xc2\xf3\x18;\n" +
	"\x0eserver.pet.get\x12\x13ServerPetGetRequest\x1a\x14ServerPetGetResponse\x12\\\n" +
	"\x18RPC_METHOD_RUNTIME_ADOPT\x10C\x1a>\xc2\xf3\x18:\n" +
	"\rruntime.adopt\x12\x13RuntimeAdoptRequest\x1a\x14RuntimeAdoptResponse\x12^\n" +
	"\x19RPC_METHOD_SERVER_PET_PUT\x10D\x1a?\xc2\xf3\x18;\n" +
	"\x0eserver.pet.put\x12\x13ServerPetPutRequest\x1a\x14ServerPetPutResponse\x12j\n" +
	"\x1cRPC_METHOD_SERVER_PET_DELETE\x10E\x1aH\xc2\xf3\x18D\n" +
	"\x11server.pet.delete\x12\x16ServerPetDeleteRequest\x1a\x17ServerPetDeleteResponse\x12f\n" +
	"\x1bRPC_METHOD_SERVER_PET_DRIVE\x10F\x1aE\xc2\xf3\x18A\n" +
	"\x10server.pet.drive\x12\x15ServerPetDriveRequest\x1a\x16ServerPetDriveResponse\x12j\n" +
	"\x1cRPC_METHOD_SERVER_POINTS_GET\x10G\x1aH\xc2\xf3\x18D\n" +
	"\x11server.points.get\x12\x16ServerPointsGetRequest\x1a\x17ServerPointsGetResponse\x12\x9e\x01\n" +
	"*RPC_METHOD_SERVER_POINTS_TRANSACTIONS_LIST\x10H\x1an\xc2\xf3\x18j\n" +
	"\x1fserver.points.transactions.list\x12\"ServerPointsTransactionListRequest\x1a#ServerPointsTransactionListResponse\x12\x9a\x01\n" +
	")RPC_METHOD_SERVER_POINTS_TRANSACTIONS_GET\x10I\x1ak\xc2\xf3\x18g\n" +
	"\x1eserver.points.transactions.get\x12!ServerPointsTransactionGetRequest\x1a\"ServerPointsTransactionGetResponse\x12j\n" +
	"\x1cRPC_METHOD_SERVER_BADGE_LIST\x10J\x1aH\xc2\xf3\x18D\n" +
	"\x11server.badge.list\x12\x16ServerBadgeListRequest\x1a\x17ServerBadgeListResponse\x12f\n" +
	"\x1bRPC_METHOD_SERVER_BADGE_GET\x10K\x1aE\xc2\xf3\x18A\n" +
	"\x10server.badge.get\x12\x15ServerBadgeGetRequest\x1a\x16ServerBadgeGetResponse\x12\x80\x01\n" +
	"\"RPC_METHOD_SERVER_GAME_RESULT_LIST\x10L\x1aX\xc2\xf3\x18T\n" +
	"\x17server.game_result.list\x12\x1bServerGameResultListRequest\x1a\x1cServerGameResultListResponse\x12|\n" +
	"!RPC_METHOD_SERVER_GAME_RESULT_GET\x10M\x1aU\xc2\xf3\x18Q\n" +
	"\x16server.game_result.get\x12\x1aServerGameResultGetRequest\x1a\x1bServerGameResultGetResponse\x12\x84\x01\n" +
	"#RPC_METHOD_SERVER_REWARD_GRANT_LIST\x10N\x1a[\xc2\xf3\x18W\n" +
	"\x18server.reward_grant.list\x12\x1cServerRewardGrantListRequest\x1a\x1dServerRewardGrantListResponse\x12\x80\x01\n" +
	"\"RPC_METHOD_SERVER_REWARD_GRANT_GET\x10O\x1aX\xc2\xf3\x18T\n" +
	"\x17server.reward_grant.get\x12\x1bServerRewardGrantGetRequest\x1a\x1cServerRewardGrantGetResponse\x12Z\n" +
	"\x1bRPC_METHOD_SERVER_TOOL_LIST\x10P\x1a9\xc2\xf3\x185\n" +
	"\x10server.tool.list\x12\x0fToolListRequest\x1a\x10ToolListResponse\x12V\n" +
	"\x1aRPC_METHOD_SERVER_TOOL_GET\x10Q\x1a6\xc2\xf3\x182\n" +
	"\x0fserver.tool.get\x12\x0eToolGetRequest\x1a\x0fToolGetResponse\x12b\n" +
	"\x1dRPC_METHOD_CLIENT_TOOL_INVOKE\x10R\x1a?\xc2\xf3\x18;\n" +
	"\x12client.tool.invoke\x12\x11ToolInvokeRequest\x1a\x12ToolInvokeResponse\x12n\n" +
	"\x1dRPC_METHOD_SERVER_PEER_LOOKUP\x10S\x1aK\xc2\xf3\x18G\n" +
	"\x12server.peer.lookup\x12\x17ServerPeerLookupRequest\x1a\x18ServerPeerLookupResponse\x12n\n" +
	"\x1dRPC_METHOD_SERVER_PEER_ASSIGN\x10T\x1aK\xc2\xf3\x18G\n" +
	"\x12server.peer.assign\x12\x17ServerPeerAssignRequest\x1a\x18ServerPeerAssignResponse\x12v\n" +
	"\x1fRPC_METHOD_SERVER_ROUTE_RESOLVE\x10U\x1aQ\xc2\xf3\x18M\n" +
	"\x14server.route.resolve\x12\x19ServerRouteResolveRequest\x1a\x1aServerRouteResolveResponse\x12|\n" +
	"!RPC_METHOD_SERVER_PET_ACTIONS_GET\x10V\x1aU\xc2\xf3\x18Q\n" +
	"\x16server.pet.actions.get\x12\x1aServerPetActionsGetRequest\x1a\x1bServerPetActionsGetResponse\x12\x84\x01\n" +
	"#RPC_METHOD_SERVER_PET_PIXA_DOWNLOAD\x10W\x1a[\xc2\xf3\x18W\n" +
	"\x18server.pet.pixa.download\x12\x1cServerPetPixaDownloadRequest\x1a\x1dServerPetPixaDownloadResponse\x12\x90\x01\n" +
	")RPC_METHOD_SERVER_WORKSPACE_ICON_DOWNLOAD\x10X\x1aa\xc2\xf3\x18]\n" +
	"\x1eserver.workspace.icon.download\x12\x1cWorkspaceIconDownloadRequest\x1a\x1dWorkspaceIconDownloadResponse\x12p\n" +
	"!RPC_METHOD_SERVER_FRIEND_INFO_GET\x10Y\x1aI\xc2\xf3\x18E\n" +
	"\x16server.friend.info.get\x12\x14FriendInfoGetRequest\x1a\x15FriendInfoGetResponse\x12d\n" +
	"\x1aRPC_METHOD_SERVER_REGISTER\x10Z\x1aD\xc2\xf3\x18@\n" +
	"\x0fserver.register\x12\x15ServerRegisterRequest\x1a\x16ServerRegisterResponse\x12z\n" +
	"#RPC_METHOD_SERVER_SPEECH_TRANSCRIBE\x10[\x1aQ\xc2\xf3\x18M\n" +
	"\x18server.speech.transcribe\x12\x17SpeechTranscribeRequest\x1a\x18SpeechTranscribeResponse\x12z\n" +
	"#RPC_METHOD_SERVER_SPEECH_SYNTHESIZE\x10\\\x1aQ\xc2\xf3\x18M\n" +
	"\x18server.speech.synthesize\x12\x17SpeechSynthesizeRequest\x1a\x18SpeechSynthesizeResponse\x12n\n" +
	"\x1dRPC_METHOD_SERVER_PEER_DELETE\x10]\x1aK\xc2\xf3\x18G\n" +
	"\x12server.peer.delete\x12\x17ServerPeerDeleteRequest\x1a\x18ServerPeerDeleteResponse\x12n\n" +
	" RPC_METHOD_SERVER_SPEECH_EXTRACT\x10^\x1aH\xc2\xf3\x18D\n" +
	"\x15server.speech.extract\x12\x14SpeechExtractRequest\x1a\x15SpeechExtractResponse\x12l\n" +
	" RPC_METHOD_SERVER_API_KEY_CREATE\x10`\x1aF\xc2\xf3\x18B\n" +
	"\x15server.api_key.create\x12\x13APIKeyCreateRequest\x1a\x14APIKeyCreateResponse\x12d\n" +
	"\x1eRPC_METHOD_SERVER_API_KEY_LIST\x10a\x1a@\xc2\xf3\x18<\n" +
	"\x13server.api_key.list\x12\x11APIKeyListRequest\x1a\x12APIKeyListResponse\x12l\n" +
	" RPC_METHOD_SERVER_API_KEY_REVOKE\x10b\x1aF\xc2\xf3\x18B\n" +
	"\x15server.api_key.revoke\x12\x13APIKeyRevokeRequest\x1a\x14APIKeyRevokeResponse\x12|\n" +
	"!RPC_METHOD_SERVER_API_KEY_RESOLVE\x10c\x1aU\xc2\xf3\x18Q\n" +
	"\x16server.api_key.resolve\x12\x1aServerAPIKeyResolveRequest\x1a\x1bServerAPIKeyResolveResponse\x12\x84\x01\n" +
	"#RPC_METHOD_CLIENT_DEVICE_STATUS_GET\x10d\x1a[\xc2\xf3\x18W\n" +
	"\x18client.device.status.get\x12\x1cClientDeviceStatusGetRequest\x1a\x1dClientDeviceStatusGetResponse\x12\x84\x01\n" +
	"#RPC_METHOD_CLIENT_DEVICE_VOLUME_SET\x10e\x1a[\xc2\xf3\x18W\n" +
	"\x18client.device.volume.set\x12\x1cClientDeviceVolumeSetRequest\x1a\x1dClientDeviceVolumeSetResponse\x12\x84\x01\n" +
	"#RPC_METHOD_CLIENT_DEVICE_SOUND_PLAY\x10f\x1a[\xc2\xf3\x18W\n" +
	"\x18client.device.sound.play\x12\x1cClientDeviceSoundPlayRequest\x1a\x1dClientDeviceSoundPlayResponse\x12v\n" +
	"\x1fRPC_METHOD_CLIENT_DEVICE_REBOOT\x10g\x1aQ\xc2\xf3\x18M\n" +
	"\x14client.device.reboot\x12\x19ClientDeviceRebootRequest\x1a\x1aClientDeviceRebootResponse\x12|\n" +
	"!RPC_METHOD_CLIENT_WIFI_STATUS_GET\x10h\x1aU\xc2\xf3\x18Q\n" +
	"\x16client.wifi.status.get\x12\x1aClientWifiStatusGetRequest\x1a\x1bClientWifiStatusGetResponse\x12|\n" +
	"!RPC_METHOD_CLIENT_WIFI_SAVED_LIST\x10i\x1aU\xc2\xf3\x18Q\n" +
	"\x16client.wifi.saved.list\x12\x1aClientWifiSavedListRequest\x1a\x1bClientWifiSavedListResponse\x12\x84\x01\n" +
	"#RPC_METHOD_CLIENT_WIFI_SAVED_FORGET\x10j\x1a[\xc2\xf3\x18W\n" +
	"\x18client.wifi.saved.forget\x12\x1cClientWifiSavedForgetRequest\x1a\x1dClientWifiSavedForgetResponse\x12f\n" +
	"\x1bRPC_METHOD_CLIENT_WIFI_SCAN\x10l\x1aE\xc2\xf3\x18A\n" +
	"\x10client.wifi.scan\x12\x15ClientWifiScanRequest\x1a\x16ClientWifiScanResponse\x12r\n" +
	"\x1eRPC_METHOD_CLIENT_WIFI_CONNECT\x10m\x1aN\xc2\xf3\x18J\n" +
	"\x13client.wifi.connect\x12\x18ClientWifiConnectRequest\x1a\x19ClientWifiConnectResponse\x12~\n" +
	"!RPC_METHOD_CLIENT_FIRMWARE_UPDATE\x10o\x1aW\xc2\xf3\x18S\n" +
	"\x16client.firmware.update\x12\x1bClientFirmwareUpdateRequest\x1a\x1cClientFirmwareUpdateResponse:d\n" +
	"\n" +
	"rpc_method\x12!.google.protobuf.EnumValueOptions\x18\xb8\x8e\x03 \x01(\v2 .gizclaw.rpc.v1.RpcMethodOptionsR\trpcMethodB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_proto_goTypes = []any{
	(StatusCode)(0),                       // 0: gizclaw.rpc.v1.StatusCode
	(RpcMethod)(0),                        // 1: gizclaw.rpc.v1.RpcMethod
	(*RpcResponse)(nil),                   // 2: gizclaw.rpc.v1.RpcResponse
	(*RpcStreamFrame)(nil),                // 3: gizclaw.rpc.v1.RpcStreamFrame
	(*RpcStatus)(nil),                     // 4: gizclaw.rpc.v1.RpcStatus
	(*ErrorInfo)(nil),                     // 5: gizclaw.rpc.v1.ErrorInfo
	(*RpcStreamEnd)(nil),                  // 6: gizclaw.rpc.v1.RpcStreamEnd
	(*RpcMethodOptions)(nil),              // 7: gizclaw.rpc.v1.RpcMethodOptions
	(*RpcRequest)(nil),                    // 8: gizclaw.rpc.v1.RpcRequest
	(*descriptorpb.EnumValueOptions)(nil), // 9: google.protobuf.EnumValueOptions
}
var file_rpc_proto_depIdxs = []int32{
	4, // 0: gizclaw.rpc.v1.RpcResponse.status:type_name -> gizclaw.rpc.v1.RpcStatus
	4, // 1: gizclaw.rpc.v1.RpcStreamFrame.status:type_name -> gizclaw.rpc.v1.RpcStatus
	6, // 2: gizclaw.rpc.v1.RpcStreamFrame.end:type_name -> gizclaw.rpc.v1.RpcStreamEnd
	0, // 3: gizclaw.rpc.v1.RpcStatus.code:type_name -> gizclaw.rpc.v1.StatusCode
	5, // 4: gizclaw.rpc.v1.RpcStatus.info:type_name -> gizclaw.rpc.v1.ErrorInfo
	1, // 5: gizclaw.rpc.v1.RpcRequest.method:type_name -> gizclaw.rpc.v1.RpcMethod
	9, // 6: gizclaw.rpc.v1.rpc_method:extendee -> google.protobuf.EnumValueOptions
	7, // 7: gizclaw.rpc.v1.rpc_method:type_name -> gizclaw.rpc.v1.RpcMethodOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	7, // [7:8] is the sub-list for extension type_name
	6, // [6:7] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*RpcResponse_Payload)(nil),
		(*RpcResponse_Status)(nil),
	}
	file_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*RpcStreamFrame_Payload)(nil),
		(*RpcStreamFrame_Status)(nil),
		(*RpcStreamFrame_End)(nil),
	}
	file_rpc_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
		ExtensionInfos:    file_rpc_proto_extTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
