// Peer RPC tool/v0 payload protobuf schema.
//
// tool/v0 is the procedure half of the device surface. MHS v0 owns hardware
// state and has no procedures; every other device-provided procedure is a
// ClientTool invoked through client.tool.v0.invoke. Tools are predefined by
// GizClaw, so a device advertises the subset it implements through
// client.tool.v0.list rather than naming tools of its own. A future version
// that accepts product-defined tools would be tool/v1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/tool.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientTool identifies one device-provided procedure. The value selects both
// payload messages, so a caller never guesses a type from a name. Numbers are
// the wire identity and are never reused; names are the stable identifier in
// documentation and SDK surfaces.
type ClientTool int32

const (
	ClientTool_CLIENT_TOOL_UNSPECIFIED                 ClientTool = 0
	ClientTool_CLIENT_TOOL_INFO_GET                    ClientTool = 1
	ClientTool_CLIENT_TOOL_IDENTIFIERS_GET             ClientTool = 2
	ClientTool_CLIENT_TOOL_DEVICE_STATUS_GET           ClientTool = 3
	ClientTool_CLIENT_TOOL_DEVICE_REBOOT               ClientTool = 4
	ClientTool_CLIENT_TOOL_DEVICE_FACTORY_RESET        ClientTool = 5
	ClientTool_CLIENT_TOOL_DEVICE_FIND                 ClientTool = 6
	ClientTool_CLIENT_TOOL_SOUND_PLAY                  ClientTool = 7
	ClientTool_CLIENT_TOOL_WIFI_SCAN                   ClientTool = 8
	ClientTool_CLIENT_TOOL_WIFI_CONNECT                ClientTool = 9
	ClientTool_CLIENT_TOOL_WIFI_SAVED_LIST             ClientTool = 10
	ClientTool_CLIENT_TOOL_WIFI_SAVED_FORGET           ClientTool = 11
	ClientTool_CLIENT_TOOL_FIRMWARE_UPDATE             ClientTool = 12
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_GET             ClientTool = 13
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_PLAY            ClientTool = 14
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_STOP            ClientTool = 15
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_MODE_SET        ClientTool = 16
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_GET    ClientTool = 17
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_SET    ClientTool = 18
	ClientTool_CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_APPEND ClientTool = 19
	ClientTool_CLIENT_TOOL_RUN_WORKSPACE_SET           ClientTool = 20
	ClientTool_CLIENT_TOOL_SOCIAL_PING                 ClientTool = 21
)

// Enum value maps for ClientTool.
var (
	ClientTool_name = map[int32]string{
		0:  "CLIENT_TOOL_UNSPECIFIED",
		1:  "CLIENT_TOOL_INFO_GET",
		2:  "CLIENT_TOOL_IDENTIFIERS_GET",
		3:  "CLIENT_TOOL_DEVICE_STATUS_GET",
		4:  "CLIENT_TOOL_DEVICE_REBOOT",
		5:  "CLIENT_TOOL_DEVICE_FACTORY_RESET",
		6:  "CLIENT_TOOL_DEVICE_FIND",
		7:  "CLIENT_TOOL_SOUND_PLAY",
		8:  "CLIENT_TOOL_WIFI_SCAN",
		9:  "CLIENT_TOOL_WIFI_CONNECT",
		10: "CLIENT_TOOL_WIFI_SAVED_LIST",
		11: "CLIENT_TOOL_WIFI_SAVED_FORGET",
		12: "CLIENT_TOOL_FIRMWARE_UPDATE",
		13: "CLIENT_TOOL_AUDIOPLAYER_GET",
		14: "CLIENT_TOOL_AUDIOPLAYER_PLAY",
		15: "CLIENT_TOOL_AUDIOPLAYER_STOP",
		16: "CLIENT_TOOL_AUDIOPLAYER_MODE_SET",
		17: "CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_GET",
		18: "CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_SET",
		19: "CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_APPEND",
		20: "CLIENT_TOOL_RUN_WORKSPACE_SET",
		21: "CLIENT_TOOL_SOCIAL_PING",
	}
	ClientTool_value = map[string]int32{
		"CLIENT_TOOL_UNSPECIFIED":                 0,
		"CLIENT_TOOL_INFO_GET":                    1,
		"CLIENT_TOOL_IDENTIFIERS_GET":             2,
		"CLIENT_TOOL_DEVICE_STATUS_GET":           3,
		"CLIENT_TOOL_DEVICE_REBOOT":               4,
		"CLIENT_TOOL_DEVICE_FACTORY_RESET":        5,
		"CLIENT_TOOL_DEVICE_FIND":                 6,
		"CLIENT_TOOL_SOUND_PLAY":                  7,
		"CLIENT_TOOL_WIFI_SCAN":                   8,
		"CLIENT_TOOL_WIFI_CONNECT":                9,
		"CLIENT_TOOL_WIFI_SAVED_LIST":             10,
		"CLIENT_TOOL_WIFI_SAVED_FORGET":           11,
		"CLIENT_TOOL_FIRMWARE_UPDATE":             12,
		"CLIENT_TOOL_AUDIOPLAYER_GET":             13,
		"CLIENT_TOOL_AUDIOPLAYER_PLAY":            14,
		"CLIENT_TOOL_AUDIOPLAYER_STOP":            15,
		"CLIENT_TOOL_AUDIOPLAYER_MODE_SET":        16,
		"CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_GET":    17,
		"CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_SET":    18,
		"CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_APPEND": 19,
		"CLIENT_TOOL_RUN_WORKSPACE_SET":           20,
		"CLIENT_TOOL_SOCIAL_PING":                 21,
	}
)

func (x ClientTool) Enum() *ClientTool {
	p := new(ClientTool)
	*p = x
	return p
}

func (x ClientTool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTool) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_tool_proto_enumTypes[0].Descriptor()
}

func (ClientTool) Type() protoreflect.EnumType {
	return &file_payload_tool_proto_enumTypes[0]
}

func (x ClientTool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTool.Descriptor instead.
func (ClientTool) EnumDescriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{0}
}

// ClientToolOptions binds a ClientTool to its stable name and to the payload
// messages carried by invoke. It mirrors RpcMethodOptions so the same
// generators read both registries.
type ClientToolOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request       string                 `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToolOptions) Reset() {
	*x = ClientToolOptions{}
	mi := &file_payload_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolOptions) ProtoMessage() {}

func (x *ClientToolOptions) ProtoReflect() protoreflect.Message {
	mi := &file_payload_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolOptions.ProtoReflect.Descriptor instead.
func (*ClientToolOptions) Descriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{0}
}

func (x *ClientToolOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientToolOptions) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ClientToolOptions) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// ClientToolV0InvokeRequest carries one tool call. payload is the encoded
// request message the tool declares; it is absent when that message has no
// fields. A tool the device does not implement answers UNIMPLEMENTED, matching
// the method-not-found answer the removed per-tool methods used to give.
type ClientToolV0InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          ClientTool             `protobuf:"varint,1,opt,name=tool,proto3,enum=gizclaw.rpc.v1.ClientTool" json:"tool,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToolV0InvokeRequest) Reset() {
	*x = ClientToolV0InvokeRequest{}
	mi := &file_payload_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolV0InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolV0InvokeRequest) ProtoMessage() {}

func (x *ClientToolV0InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolV0InvokeRequest.ProtoReflect.Descriptor instead.
func (*ClientToolV0InvokeRequest) Descriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{1}
}

func (x *ClientToolV0InvokeRequest) GetTool() ClientTool {
	if x != nil {
		return x.Tool
	}
	return ClientTool_CLIENT_TOOL_UNSPECIFIED
}

func (x *ClientToolV0InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ClientToolV0InvokeResponse carries the encoded response message the invoked
// tool declares, absent when that message has no fields. Failures travel as an
// RpcStatus on the envelope, not as a payload.
type ClientToolV0InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToolV0InvokeResponse) Reset() {
	*x = ClientToolV0InvokeResponse{}
	mi := &file_payload_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolV0InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolV0InvokeResponse) ProtoMessage() {}

func (x *ClientToolV0InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolV0InvokeResponse.ProtoReflect.Descriptor instead.
func (*ClientToolV0InvokeResponse) Descriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ClientToolV0InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ClientToolV0ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToolV0ListRequest) Reset() {
	*x = ClientToolV0ListRequest{}
	mi := &file_payload_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolV0ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolV0ListRequest) ProtoMessage() {}

func (x *ClientToolV0ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolV0ListRequest.ProtoReflect.Descriptor instead.
func (*ClientToolV0ListRequest) Descriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{3}
}

// ClientToolV0ListResponse lists the tools the device actually implements, so
// a caller hides or skips a control it would only fail. Unknown values must be
// ignored rather than rejected, and the list never includes UNSPECIFIED.
type ClientToolV0ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []ClientTool           `protobuf:"varint,1,rep,packed,name=tools,proto3,enum=gizclaw.rpc.v1.ClientTool" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToolV0ListResponse) Reset() {
	*x = ClientToolV0ListResponse{}
	mi := &file_payload_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToolV0ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToolV0ListResponse) ProtoMessage() {}

func (x *ClientToolV0ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToolV0ListResponse.ProtoReflect.Descriptor instead.
func (*ClientToolV0ListResponse) Descriptor() ([]byte, []int) {
	return file_payload_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ClientToolV0ListResponse) GetTools() []ClientTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

var file_payload_tool_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ClientToolOptions)(nil),
		Field:         51001,
		Name:          "gizclaw.rpc.v1.client_tool",
		Tag:           "bytes,51001,opt,name=client_tool",
		Filename:      "payload/tool.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional gizclaw.rpc.v1.ClientToolOptions client_tool = 51001;
	E_ClientTool = &file_payload_tool_proto_extTypes[0]
)

var File_payload_tool_proto protoreflect.FileDescriptor

const file_payload_tool_proto_rawDesc = "" +
	"\n" +
	"\x12payload/tool.proto\x12\x0egizclaw.rpc.v1\x1a google/protobuf/descriptor.proto\"]\n" +
	"\x11ClientToolOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arequest\x18\x02 \x01(\tR\arequest\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"v\n" +
	"\x19ClientToolV0InvokeRequest\x12.\n" +
	"\x04tool\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.ClientToolR\x04tool\x12\x1d\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload\"G\n" +
	"\x1aClientToolV0InvokeResponse\x12\x1d\n" +
	"\apayload\x18\x01 \x01(\fH\x00R\apayload\x88\x01\x01B\n" +
	"\n" +
	"\b_payload\"\x19\n" +
	"\x17ClientToolV0ListRequest\"L\n" +
	"\x18ClientToolV0ListResponse\x120\n" +
	"\x05tools\x18\x01 \x03(\x0e2\x1a.gizclaw.rpc.v1.ClientToolR\x05tools*\xb1\x14\n" +
	"\n" +
	"ClientTool\x12\x1b\n" +
	"\x17CLIENT_TOOL_UNSPECIFIED\x10\x00\x12U\n" +
	"\x14CLIENT_TOOL_INFO_GET\x10\x01\x1a;\xca\xf3\x187\n" +
	"\binfo.get\x12\x14ClientGetInfoRequest\x1a\x15ClientGetInfoResponse\x12q\n" +
	"\x1bCLIENT_TOOL_IDENTIFIERS_GET\x10\x02\x1aP\xca\xf3\x18L\n" +
	"\x0fidentifiers.get\x12\x1bClientGetIdentifiersRequest\x1a\x1cClientGetIdentifiersResponse\x12w\n" +
	"\x1dCLIENT_TOOL_DEVICE_STATUS_GET\x10\x03\x1aT\xca\xf3\x18P\n" +
	"\x11device.status.get\x12\x1cClientDeviceStatusGetRequest\x1a\x1dClientDeviceStatusGetResponse\x12i\n" +
	"\x19CLIENT_TOOL_DEVICE_REBOOT\x10\x04\x1aJ\xca\xf3\x18F\n" +
	"\rdevice.reboot\x12\x19ClientDeviceRebootRequest\x1a\x1aClientDeviceRebootResponse\x12\x83\x01\n" +
	" CLIENT_TOOL_DEVICE_FACTORY_RESET\x10\x05\x1a]\xca\xf3\x18Y\n" +
	"\x14device.factory_reset\x12\x1fClientDeviceFactoryResetRequest\x1a ClientDeviceFactoryResetResponse\x12a\n" +
	"\x17CLIENT_TOOL_DEVICE_FIND\x10\x06\x1aD\xca\xf3\x18@\n" +
	"\vdevice.find\x12\x17ClientDeviceFindRequest\x1a\x18ClientDeviceFindResponse\x12i\n" +
	"\x16CLIENT_TOOL_SOUND_PLAY\x10\a\x1aM\xca\xf3\x18I\n" +
	"\n" +
	"sound.play\x12\x1cClientDeviceSoundPlayRequest\x1a\x1dClientDeviceSoundPlayResponse\x12Y\n" +
	"\x15CLIENT_TOOL_WIFI_SCAN\x10\b\x1a>\xca\xf3\x18:\n" +
	"\twifi.scan\x12\x15ClientWifiScanRequest\x1a\x16ClientWifiScanResponse\x12e\n" +
	"\x18CLIENT_TOOL_WIFI_CONNECT\x10\t\x1aG\xca\xf3\x18C\n" +
	"\fwifi.connect\x12\x18ClientWifiConnectRequest\x1a\x19ClientWifiConnectResponse\x12o\n" +
	"\x1bCLIENT_TOOL_WIFI_SAVED_LIST\x10\n" +
	"\x1aN\xca\xf3\x18J\n" +
	"\x0fwifi.saved.list\x12\x1aClientWifiSavedListRequest\x1a\x1bClientWifiSavedListResponse\x12w\n" +
	"\x1dCLIENT_TOOL_WIFI_SAVED_FORGET\x10\v\x1aT\xca\xf3\x18P\n" +
	"\x11wifi.saved.forget\x12\x1cClientWifiSavedForgetRequest\x1a\x1dClientWifiSavedForgetResponse\x12q\n" +
	"\x1bCLIENT_TOOL_FIRMWARE_UPDATE\x10\f\x1aP\xca\xf3\x18L\n" +
	"\x0ffirmware.update\x12\x1bClientFirmwareUpdateRequest\x1a\x1cClientFirmwareUpdateResponse\x12}\n" +
	"\x1bCLIENT_TOOL_AUDIOPLAYER_GET\x10\r\x1a\\\xca\xf3\x18X\n" +
	"\x0faudioplayer.get\x12!ClientDeviceAudioPlayerGetRequest\x1a\"ClientDeviceAudioPlayerGetResponse\x12\x81\x01\n" +
	"\x1cCLIENT_TOOL_AUDIOPLAYER_PLAY\x10\x0e\x1a_\xca\xf3\x18[\n" +
	"\x10audioplayer.play\x12\"ClientDeviceAudioPlayerPlayRequest\x1a#ClientDeviceAudioPlayerPlayResponse\x12\x81\x01\n" +
	"\x1cCLIENT_TOOL_AUDIOPLAYER_STOP\x10\x0f\x1a_\xca\xf3\x18[\n" +
	"\x10audioplayer.stop\x12\"ClientDeviceAudioPlayerStopRequest\x1a#ClientDeviceAudioPlayerStopResponse\x12\x8f\x01\n" +
	" CLIENT_TOOL_AUDIOPLAYER_MODE_SET\x10\x10\x1ai\xca\xf3\x18e\n" +
	"\x14audioplayer.mode.set\x12%ClientDeviceAudioPlayerModeSetRequest\x1a&ClientDeviceAudioPlayerModeSetResponse\x12\x9f\x01\n" +
	"$CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_GET\x10\x11\x1au\xca\xf3\x18q\n" +
	"\x18audioplayer.playlist.get\x12)ClientDeviceAudioPlayerPlaylistGetRequest\x1a*ClientDeviceAudioPlayerPlaylistGetResponse\x12\x9f\x01\n" +
	"$CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_SET\x10\x12\x1au\xca\xf3\x18q\n" +
	"\x18audioplayer.playlist.set\x12)ClientDeviceAudioPlayerPlaylistSetRequest\x1a*ClientDeviceAudioPlayerPlaylistSetResponse\x12\xab\x01\n" +
	"'CLIENT_TOOL_AUDIOPLAYER_PLAYLIST_APPEND\x10\x13\x1a~\xca\xf3\x18z\n" +
	"\x1baudioplayer.playlist.append\x12,ClientDeviceAudioPlayerPlaylistAppendRequest\x1a-ClientDeviceAudioPlayerPlaylistAppendResponse\x12w\n" +
	"\x1dCLIENT_TOOL_RUN_WORKSPACE_SET\x10\x14\x1aT\xca\xf3\x18P\n" +
	"\x11run.workspace.set\x12\x1cClientRunWorkspaceSetRequest\x1a\x1dClientRunWorkspaceSetResponse\x12a\n" +
	"\x17CLIENT_TOOL_SOCIAL_PING\x10\x15\x1aD\xca\xf3\x18@\n" +
	"\vsocial.ping\x12\x17ClientSocialPingRequest\x1a\x18ClientSocialPingResponse:g\n" +
	"\vclient_tool\x12!.google.protobuf.EnumValueOptions\x18\xb9\x8e\x03 \x01(\v2!.gizclaw.rpc.v1.ClientToolOptionsR\n" +
	"clientToolB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_tool_proto_rawDescOnce sync.Once
	file_payload_tool_proto_rawDescData []byte
)

func file_payload_tool_proto_rawDescGZIP() []byte {
	file_payload_tool_proto_rawDescOnce.Do(func() {
		file_payload_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_tool_proto_rawDesc), len(file_payload_tool_proto_rawDesc)))
	})
	return file_payload_tool_proto_rawDescData
}

var file_payload_tool_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payload_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_payload_tool_proto_goTypes = []any{
	(ClientTool)(0),                       // 0: gizclaw.rpc.v1.ClientTool
	(*ClientToolOptions)(nil),             // 1: gizclaw.rpc.v1.ClientToolOptions
	(*ClientToolV0InvokeRequest)(nil),     // 2: gizclaw.rpc.v1.ClientToolV0InvokeRequest
	(*ClientToolV0InvokeResponse)(nil),    // 3: gizclaw.rpc.v1.ClientToolV0InvokeResponse
	(*ClientToolV0ListRequest)(nil),       // 4: gizclaw.rpc.v1.ClientToolV0ListRequest
	(*ClientToolV0ListResponse)(nil),      // 5: gizclaw.rpc.v1.ClientToolV0ListResponse
	(*descriptorpb.EnumValueOptions)(nil), // 6: google.protobuf.EnumValueOptions
}
var file_payload_tool_proto_depIdxs = []int32{
	0, // 0: gizclaw.rpc.v1.ClientToolV0InvokeRequest.tool:type_name -> gizclaw.rpc.v1.ClientTool
	0, // 1: gizclaw.rpc.v1.ClientToolV0ListResponse.tools:type_name -> gizclaw.rpc.v1.ClientTool
	6, // 2: gizclaw.rpc.v1.client_tool:extendee -> google.protobuf.EnumValueOptions
	1, // 3: gizclaw.rpc.v1.client_tool:type_name -> gizclaw.rpc.v1.ClientToolOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payload_tool_proto_init() }
func file_payload_tool_proto_init() {
	if File_payload_tool_proto != nil {
		return
	}
	file_payload_tool_proto_msgTypes[1].OneofWrappers = []any{}
	file_payload_tool_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_tool_proto_rawDesc), len(file_payload_tool_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_payload_tool_proto_goTypes,
		DependencyIndexes: file_payload_tool_proto_depIdxs,
		EnumInfos:         file_payload_tool_proto_enumTypes,
		MessageInfos:      file_payload_tool_proto_msgTypes,
		ExtensionInfos:    file_payload_tool_proto_extTypes,
	}.Build()
	File_payload_tool_proto = out.File
	file_payload_tool_proto_goTypes = nil
	file_payload_tool_proto_depIdxs = nil
}
