FROM ubuntu:24.04
RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates curl libstdc++6 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY bin/ /usr/local/bin/
COPY tests/ tests/
